### PR TITLE
Remove isPositiveInteger() check for third argument to strpos()

### LINKED ISSUE #8303: StrContainsRector incorrectly replaces strpos() when $offset is defined
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.18.6             |

## Minimal PHP Code Causing Issue

```php
$haystack = 'aba';
$needle = 'b';
$offset = 0;
while (strpos($haystack, $needle, $offset) !== false) {
    // do some stuff
    $offset++;
}
```

becomes the following, which will result in an endless loop

```php
$haystack = 'aba';
$needle = 'b';
$offset = 0;
while (str_contains($haystack, $needle)) {
    // do some stuff
    $offset++;
}
```

## Expected Behaviour

I think Rector should skip the change if offset is specified. This is a breaking change to the code as it completely erases the variable from being used.

### PR DESCRIPTION
**Pull request by ikari7789**
Fixes: https://github.com/rectorphp/rector/issues/8303

Removes check that third argument is only a positive integer. Should fix cases where the offset is set dynamically through a variable or expression.

### CODE REVIEW

File: rules/Php80/Rector/NotIdentical/StrContainsRector.php [hunk 1]
```diff
@@ -151,13 +151,4 @@ private function matchIdenticalOrNotIdenticalToFalse(Identical | NotIdentical |
...
         return null;
     }
-
-    private function isPositiveInteger(Expr $expr): bool
-    {
-        if (! $expr instanceof LNumber) {
-            return false;
-        }
-
-        return $expr->value > 0;
```
Comment (samsonasik) [inline rules/Php80/Rector/NotIdentical/StrContainsRector.php:161]: How about direct 0 or negative int, could you add fixture for it to avoid regression?

Comment (ikari7789) [reply rules/Php80/Rector/NotIdentical/StrContainsRector.php:161]: https://www.php.net/manual/en/function.substr.php

0 and negative values are totally valid offsets when considering strings though. I'm not sure why they would be excluded from this check.

Comment (samsonasik) [reply rules/Php80/Rector/NotIdentical/StrContainsRector.php:161]: The fixture is needed to see before vs after with 0 or negative int to see the different

Comment (ikari7789) [reply rules/Php80/Rector/NotIdentical/StrContainsRector.php:161]: Understood! Added. I changed it to remove substr() set if the offset is specified as zero (would be the start of the string).

File: rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/offset_zero_equal_strpos.php.inc [hunk 2]
```diff
@@ -0,0 +1,25 @@
+<?php
+
+namespace Rector\Tests\Php80\Rector\NotIdentical\StrContainsRector\Fixture;
+
+class OffsetZeroStrpos
+{
+    public function run()
+    {
+        $isMatch = strpos('abc', 'a', 0) != false;
```
Comment (samsonasik) [inline rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/offset_zero_equal_strpos.php.inc:9]: How about 0 as variable?

```php
$offset = 0;
strpos('abc', 'a', $offset) != false;
```

**Comment by samsonasik** [comment]
More on looking at it, I think dynamic offset should be skipped, to avoid offset changed, eg: on loop which cause invalid changed

File: rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/offset_zero_equal_strpos.php.inc (hunk 2 above)
Comment (ikari7789) [reply rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/offset_zero_equal_strpos.php.inc:9]: I've added this fixture.

**Comment by ikari7789** [comment]
> More on looking at it, I think dynamic offset should be skipped, to avoid offset changed, eg: on loop which cause invalid changed

After I started looking at the code, I think this isn't the right approach to take. The value of the variable here doesn't matter. The previous code was only adding in the offset if the second argument was explicitly an integer. The code now longer cares what the offset is (unless explicitly a zero integer) and sets that directly into place. Even in places where the offset changes, I don't think it should have any impact, unless I'm wildly misunderstanding how this gets processed.

**Comment by samsonasik** [comment]
I will let @TomasVotruba decide on this.

imo, language features is ok as far as it has safety belt, as old backport to old language will always work.

On dynamic offset usage,  it probably make harder to debug when there is a bug caused by its transformation.

**Comment by TomasVotruba** [comment]
Looks good to me, let's give it a try :+1:

**Comment by TomasVotruba** [comment]
Thank you @ikari7789
