### PR TITLE
[Php82] Handle has only readonly properties but not all promoted property on ReadOnlyClassRector

### LINKED ISSUE #8721: ReadOnlyClassRector doesn't work when class has only readonly properties but not all are promoted in constructor
# Bug Report

My class has two readonly properties `a` and `b`. `a` is a constructor promoted property and `b` is not - it's set inside constructor's body bases on the second argument passed. This class should be marked as readonly. 

## Minimal PHP Code Causing Issue

https://getrector.com/demo/338d8c55-09dc-463a-a9ba-70c1e7ceda23

## Expected Behaviour

Should add readonly to a class.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8721

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @javaDeveloperKid

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

File: src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php [hunk 1]
```diff
@@ -69,26 +69,26 @@
...
+        private ReflectionProvider $reflectionProvider,
         iterable $nodeVisitors,
-        private readonly ScopeFactory $scopeFactory,
-        private readonly PrivatesAccessor $privatesAccessor,
-        private readonly NodeNameResolver $nodeNameResolver,
-        private readonly ClassAnalyzer $classAnalyzer
+        private ScopeFactory $scopeFactory,
+        private PrivatesAccessor $privatesAccessor,
+        private NodeNameResolver $nodeNameResolver,
+        private ClassAnalyzer $classAnalyzer
```
Comment (TomasVotruba) [inline src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:91]: Awesome to see Rector improving itself after rule is fixed :+1:  :tada:
