### PR TITLE
fix: Skip adding string casting to closure return when it returns str…

### LINKED ISSUE #8685: StringableForToStringRector adding cast to incorrect place
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | last dev-main             |

## Minimal PHP Code Causing Issue
See https://getrector.com/demo/c32efdb4-a075-4a39-9686-259bed08325d
```
<?php

declare(strict_types=1);

namespace Rector\Tests\Php80\Rector\Class_\StringableForToStringRector\Fixture;

class View
{
    public function __construct(private string $template, private array $data)
    {
    }

    public static function make(string $template, array $data)
    {
        return new self($template, $data);
    }

    public function render(): string
    {
        return $this->template;
    }
}

class SkipOnAnonymousFunctions implements \Stringable
{
    public function __construct(private array $items)
    {
    }

    public function __toString(): string
    {
        return View::make('index', [
            'only_uppercase' => array_filter(
                $this->items,
                static function (string $item) {
                    return mb_strtoupper($item) === $item;
                }
            ),
        ])->render();
    }
}

```

## Expected Behaviour

Rector should not add string casting to array_filter

### PR DESCRIPTION
**Pull request by nikolicaleksa**
Fixes https://github.com/rectorphp/rector/issues/8685

### CODE REVIEW

File: rules/Php80/Rector/Class_/StringableForToStringRector.php [hunk 1]
```diff
@@ -162,7 +162,7 @@ private function processNotStringType(ClassMethod $toStringClassMethod): void
             }
 
             $type = $this->nodeTypeResolver->getType($subNode->expr);
-            if ($type->isString()->yes()) {
+            if ($type->isVoid()->no()) {
```
Comment (samsonasik) [inline rules/Php80/Rector/Class_/StringableForToStringRector.php]: the solution should can check inner function instead, with verify early **before line 155** before `Return_` check:

```php
            if ($subNode instanceof \PhpParser\Node\Stmt\Class_ || $subNode instanceof \PhpParser\Node\Stmt\Function_ || $subNode instanceof \PhpParser\Node\Expr\Closure) {
                return \PhpParser\NodeTraverser::DONT_TRAVERSE_CURRENT_AND_CHILDREN;
            }
```

so it by pass inner function.

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @nikolicaleksa
