### PR TITLE
[PostRector] Fix unused import not removed on empty generic class name exists

### LINKED ISSUE #8200: [rector-src] removeUnusedImports() not working on packages/Config/RectorConfig.php
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. rector-src main branch             |

## Minimal PHP Code Causing Issue

Running:

```
bin/rector process packages/Config/RectorConfig.php --clear-cache
```

should remove unused imports:

```
use Rector\Core\FileSystem\FilesystemTweaker;
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8200

### CODE REVIEW

File: packages/NodeTypeResolver/Node/AttributeKey.php [hunk 1]
```diff
@@ -4,8 +4,6 @@
 
 namespace Rector\NodeTypeResolver\Node;
 
-use PHPStan\Analyser\Scope;
```
Comment (samsonasik) [inline packages/NodeTypeResolver/Node/AttributeKey.php]: hm.., it seems cause it used as `@see Scope` removed

Comment (samsonasik) [reply packages/NodeTypeResolver/Node/AttributeKey.php]: I see, it because `@see` is exists inside `PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTextNode`:

```
PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTextNode #18819
   text: 'Contains @see Scope'
```

Comment (samsonasik) [reply packages/NodeTypeResolver/Node/AttributeKey.php]: Fixed by make `@see` not part of text, but independent docblock https://github.com/rectorphp/rector-src/pull/5012/commits/ac93c3e0599f48e263bc1a693419ae092add00ff

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Looks good :hugs:
