### PR TITLE
[CodeQuality] Skip method call on else on TernaryFalseExpressionToIfRector

### LINKED ISSUE #8367: Incorrect behavior of TernaryFalseExpressionToIfRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/66f82535-275a-4804-bdbe-cc6b10f9cabc

```php
<?php

final class DemoFile
{
    public function run(bool $param): void
    {
        $param ? $this->a() : $this->b();
    }

    public function a(): void
    {

    }

    public function b(): void
    {

    }
}
```

### Responsible rules

* `TernaryFalseExpressionToIfRector`

## Expected Behavior

Rector should not modify the code. This issue is not related to a specific rector version. Instead it depends on the phpstan version used.
I was able to trace this down to a change introduces in [phpstan version 1.10.49](https://github.com/phpstan/phpstan/releases/tag/1.10.49). And specifically this PR: https://github.com/phpstan/phpstan-src/pull/2778

The problem is basically that rector has changed the return type from a `VoidType` to `NullType` which is an instance of `ConstantType` which then leads to this unexpected refactor.

But I think this is a problem of the `TernaryFalseExpressionToIfRector` in general. Because if method `b` has `null` as return type instead of `void` it happens regardless of the phpstan version used, which is wrong too: https://getrector.com/demo/5d99559b-c987-4e15-9ae8-c44fd2d33023

In my opinion, the rector should never perform a refactor if the `else` of the `Ternary` operator is a function call.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8367

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @gehrisandro

File: rules/DeadCode/SideEffect/SideEffectNodeDetector.php [hunk 1]
```diff
@@ -43,41 +30,10 @@ final class SideEffectNodeDetector
     ];
 
     public function __construct(
-        private readonly NodeTypeResolver $nodeTypeResolver,
         private readonly PureFunctionDetector $pureFunctionDetector
     ) {
     }
 
-    public function detect(Expr $expr, Scope $scope): bool
```
Comment (samsonasik) [inline rules/DeadCode/SideEffect/SideEffectNodeDetector.php]: this `detect` method seems only used by `TernaryFalseExpressionToIfRector`, which there is already `detectCallExpr()` for it, so I removed it and just use `detectCallExpr()`.

Comment (samsonasik) [reply rules/DeadCode/SideEffect/SideEffectNodeDetector.php]: I added more fixture for assign in else, seems some logic need to be merged, eg: `$expr instanceof Assign`

Comment (samsonasik) [reply rules/DeadCode/SideEffect/SideEffectNodeDetector.php]: I changed `detectCallExpr()` to `detect()` with `Assign` check.

**Comment by samsonasik** [comment]
Ok, it seems cause error on `RemoveUnusedVariableDouble`

```diff
There were 4 failures:

1) Rector\Core\Tests\Issues\RemoveUnusedVariableDouble\RemoveUnusedVariableDoubleTest::test with data set #0
Failed on fixture file "fixture.php.inc"

Applied Rector rules:
 * Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector
 * Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector

Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
         $user = ['User' => ['name' => 'John']];
         $objects = [1, 2, 3];
         $groups = [];
+        'default';
```

I will look more.

**Comment by samsonasik** [comment]
Fixed by use both `detect()` and `detectCallExpr()` 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)
