### PR TITLE
Cache on successful file processing

### LINKED ISSUE #7770: Rector appears to be caching files before they've finished processing.
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.13             |

When running Rector for some reason I have a file that is failing to process, with an error very similar to #7586. If there are files which work they pass and then Rector hangs when it gets to the problematic file. If I just try process the problematic file then I get no output whatsoever.

This issue though isn't about _that_ bug, this issue is about incorrect caching of files when Rector hangs.

When Rector does hang, if I quit rector with `Ctrl + C` and then run again it appears as those the file that was problematic has been marked as processed and so running Rector succeeds the second time.

If I run with `vendor/bin/rector process --clear-cache` then I get stuck on the problematic file again, or if I change the list of files to process (which appears to reset the cache) it fails the first run and succeeds the second.

## Minimal PHP Code Causing Issue

Unfortunately I don't have that as the code that is breaking things appears to work on https://getrector.org/demo/ :(

I've set `$rectorConfig->parallel(seconds: 600, maxNumberOfProcess: 1);` to make things easier to debug, but the issue occurs with parallel processes as well.

## Expected Behaviour

When a file is processed it should only be added to the cache when it has successfully finished processing.

### PR DESCRIPTION
**Pull request by yguedidi**
New version of #3604
Closes https://github.com/rectorphp/rector/issues/7770
Now a file will be cached only when not in dry run mode

needs first:
- [x] #3616 
- [x] #3666

### CODE REVIEW

File: packages/Parallel/WorkerRunner.php [hunk 1]
```diff
@@ -85,14 +87,24 @@ public function run(Encoder $encoder, Decoder $decoder, Configuration $configura
...
+
                 try {
                     $file = new File($filePath, FileSystem::read($filePath));
                     $this->currentFileProvider->setFile($file);
 
                     $errorAndFileDiffs = $this->processFiles($file, $configuration, $errorAndFileDiffs);
+
+                    if ($errorAndFileDiffs[Bridge::SYSTEM_ERRORS] !== []) {
+                        $this->changedFilesDetector->invalidateFile($file->getFilePath());
+                    } elseif (! $configuration->isDryRun()) {
```
Comment (yguedidi) [inline packages/Parallel/WorkerRunner.php:100]: here the added condition

File: src/Application/ApplicationFileProcessor.php [hunk 2]
```diff
@@ -128,6 +130,12 @@ public function processFiles(array $files, Configuration $configuration): array
                 $systemErrorsAndFileDiffs = $this->arrayParametersMerger->merge($systemErrorsAndFileDiffs, $result);
             }
 
+            if ($systemErrorsAndFileDiffs[Bridge::SYSTEM_ERRORS] !== []) {
+                $this->changedFilesDetector->invalidateFile($file->getFilePath());
+            } elseif (! $configuration->isDryRun()) {
```
Comment (yguedidi) [inline src/Application/ApplicationFileProcessor.php:138]: here the added condition

**Comment by samsonasik** [comment]
I think this one need e2e test to avoid regression and back and forth check, eg:

- multiple `--dry-run` check should ok.
- multiple succesfull keep changing, eg, the following code got twice changed should ok.

```php
if ($a && $b) {
    return true;
}
```

on config:

```php
<?php

declare(strict_types=1);

use Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector;
use Rector\Config\RectorConfig;
use Rector\EarlyReturn\Rector\If_\ChangeAndIfToEarlyReturnRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->rule(ChangeAndIfToEarlyReturnRector::class);
    $rectorConfig->rule(NewlineAfterStatementRector::class);
};
```

First: https://getrector.com/demo/55b308a8-af17-48cb-b2be-9c0d26ab60c4
Second: https://getrector.com/demo/53cd71fb-1851-44d0-aa1e-ba7e5329db77

**Comment by yguedidi** [comment]
Thanks for guidance! Will work on separate PRs this week-end to add those e2e tests

**Comment by staabm** [comment]
Is this still WIP ?

**Comment by samsonasik** [comment]
It needs one more e2e test for consecutive succesfull.

for consecutive dry-run, there was already PR https://github.com/rectorphp/rector-src/pull/3616

**Comment by yguedidi** [comment]
I planned to work on that e2e test this week-end

**Comment by yguedidi** [comment]
@samsonasik @staabm here it is: #3666

File: packages-tests/Caching/Detector/ChangedFilesDetectorTest.php [hunk 3]
```diff
@@ -32,7 +32,7 @@ public function testHasFileChanged(): void
         $filePath = __DIR__ . '/Source/file.php';
```
Comment (staabm) [inline packages-tests/Caching/Detector/ChangedFilesDetectorTest.php:32]: why are these test-changes required?

existing tests shouldn't be changed with new PRs

**Comment by staabm** [comment]
I think the PR itself needs a new test-case reproducing the issue it is trying to fix

File: packages-tests/Caching/Detector/ChangedFilesDetectorTest.php (hunk 3 above)
Comment (yguedidi) [reply packages-tests/Caching/Detector/ChangedFilesDetectorTest.php:32]: because previous logic is splitted in 2 methods now, I renamed one so maybe it's clearer

**Comment by yguedidi** [comment]
@staabm good point! I'll try to come with a test in following days, but the final code is ready if you want to have a look, see that all tests pass now, even the consecutive runs test.
@samsonasik Idea is to cache files only when Rector didn't changed them, so when they are in their final state. So following runs will still go through previously changed files to attempt to change them again.
Maybe not the best way, but at least it preserve actual Rector vision on multiple runs and makes the cache reliable

Credits to @stof for the idea! Thank you

**Comment by samsonasik** [comment]
Please rename commit message with double quote `""` , that will cause failure build downgrade

**Comment by yguedidi** [comment]
@samsonasik that revert commit is a temporary one just to generate a failing build, to show the issue.
will remove it from the final PR, showing that the PR solves the issue

**Comment by yguedidi** [comment]
Here the failing test without the fix: https://github.com/rectorphp/rector-src/actions/runs/4850942011/jobs/8644319975?pr=3614
See that with the fix by caching at the end instead of caching at the beginning, that previously failing test is now green: https://github.com/rectorphp/rector-src/actions/runs/4850961546/jobs/8644357227?pr=3614

File: e2e/timeout-file-not-cached/expected-output.diff
Comment (yguedidi) [inline e2e/timeout-file-not-cached/expected-output.diff:1]: we expect the timeout error to stay even with cache, and now the timouted files are not cached because we cache on success instead of caching at the beginning of the processing

File: e2e/timeout-file-not-cached/rector.php [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+declare(strict_types=1);
+
+use Rector\Caching\ValueObject\Storage\FileCacheStorage;
+use Rector\Config\RectorConfig;
+use Rector\Set\ValueObject\LevelSetList;
+
+return static function (RectorConfig $rectorConfig): void {
+    $rectorConfig->cacheClass(FileCacheStorage::class);
+    $rectorConfig->parallel(1);
```
Comment (yguedidi) [inline e2e/timeout-file-not-cached/rector.php:11]: used 1 second timeout to maximize chances of timeout

File: e2e/timeout-file-not-cached/rector.php [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+    $rectorConfig->paths([
+        __DIR__ . '/src',
+    ]);
+
+    $rectorConfig->sets([LevelSetList::UP_TO_PHP_82]);
```
Comment (yguedidi) [inline e2e/timeout-file-not-cached/rector.php:17]: used a big rule set to maximize chances of timeout

File: e2e/timeout-file-not-cached/src/BetterStandardPrinter.php
Comment (yguedidi) [inline e2e/timeout-file-not-cached/src/BetterStandardPrinter.php:1]: used a big file from src to maximize chances of timeout

**Comment by yguedidi** [comment]
@TomasVotruba @samsonasik @staabm this is now ready for review!

File: e2e/timeout-file-not-cached/src/BetterStandardPrinter.php [hunk 6]
```diff
@@ -0,0 +1,625 @@
...
+use Rector\Core\ValueObject\Application\File;
+use Rector\Core\ValueObject\Reporting\FileDiff;
+use Rector\NodeTypeResolver\Node\AttributeKey;
+
+/**
+ * @see \Rector\Core\Tests\PhpParser\Printer\BetterStandardPrinterTest
+ *
+ * @property array<string, array{string, bool, string, null}> $insertionMap
+ */
+final class BetterStandardPrinter extends Standard implements NodePrinterInterface
```
Comment (samsonasik) [inline e2e/timeout-file-not-cached/src/BetterStandardPrinter.php]: Please rename so it not make collision when using IDE with the actual inside `src` one, eg:

```suggestion
final class SomeFixturePrinter extends Standard implements NodePrinterInterface
```

Comment (yguedidi) [reply e2e/timeout-file-not-cached/src/BetterStandardPrinter.php]: good catch! just fixed with your proposal

File: e2e/timeout-file-not-cached/src/BetterStandardPrinter.php [hunk 7]
```diff
@@ -0,0 +1,625 @@
+<?php
```
Comment (samsonasik) [inline e2e/timeout-file-not-cached/src/BetterStandardPrinter.php]: file should be renamed to: `SomeFixturePrinter.php`

File: packages/Caching/Detector/ChangedFilesDetector.php [hunk 8]
```diff
@@ -24,13 +34,34 @@ public function __construct(
...
+    {
+        $filePathCacheKey = $this->getFilePathCacheKey($filePath);
+        $this->dependentFiles[$filePathCacheKey] = $dependentFiles;
+    }
+
+    public function cacheFileWithDependencies(string $filePath): void
     {
         $filePathCacheKey = $this->getFilePathCacheKey($filePath);
+
+        if (! array_key_exists($filePathCacheKey, $this->cachableFiles)) {
```
Comment (samsonasik) [inline packages/Caching/Detector/ChangedFilesDetector.php]: probably `isset()` can be used?

File: src/Application/FileProcessor/PhpFileProcessor.php [hunk 9]
```diff
@@ -80,12 +84,19 @@ public function process(File $file, Configuration $configuration): array
             // important to detect if file has changed
             $this->printFile($file, $configuration);
 
+            $fileHasChanged = $fileHasChanged || $file->hasChanged();
+
             if ($file->hasChanged()) {
```
Comment (samsonasik) [inline src/Application/FileProcessor/PhpFileProcessor.php]: Repetitive `$file->hasChanged()` with previous line 87 can be moved to variable.

File: packages/Caching/Detector/ChangedFilesDetector.php (hunk 8 above)
Comment (yguedidi) [reply packages/Caching/Detector/ChangedFilesDetector.php]: I tend to favor being precise using `array_key_exists` when I want to check for the existance of a key.
`isset` will work for sure here as values of the array are anyway always `true`
so up to you

File: e2e/timeout-file-not-cached/src/BetterStandardPrinter.php (hunk 7 above)
Comment (yguedidi) [reply e2e/timeout-file-not-cached/src/BetterStandardPrinter.php]: 🤦🏼

File: src/Application/FileProcessor/PhpFileProcessor.php [hunk 10]
```diff
@@ -80,11 +84,20 @@ public function process(File $file, Configuration $configuration): array
             // important to detect if file has changed
             $this->printFile($file, $configuration);
 
-            if ($file->hasChanged()) {
+            $fileHasChangedInCurrentPass = $file->hasChanged();
+
+            if ($fileHasChangedInCurrentPass) {
```
Comment (samsonasik) [inline src/Application/FileProcessor/PhpFileProcessor.php:89]: immediate assign can be used:

```suggestion
            if ($fileHasChangedInCurrentPass) {
                $fileHasChanged = true;
```

File: src/Application/FileProcessor/PhpFileProcessor.php [hunk 11]
```diff
@@ -80,11 +84,20 @@ public function process(File $file, Configuration $configuration): array
...
                 $file->setFileDiff($this->fileDiffFactory->createTempFileDiff($file));
                 $rectorWithLineChanges = $file->getRectorWithLineChanges();
             }
-        } while ($file->hasChanged());
+
+            $fileHasChanged = $fileHasChanged || $fileHasChangedInCurrentPass;
```
Comment (samsonasik) [inline src/Application/FileProcessor/PhpFileProcessor.php]: this line can be remove:

```suggestion
```

File: src/Console/Command/ProcessCommand.php [hunk 12]
```diff
@@ -89,9 +89,6 @@ protected function execute(InputInterface $input, OutputInterface $output): int
         $processResult = $this->processResultFactory->create($systemErrorsAndFileDiffs);
         $outputFormatter->report($processResult, $configuration);
 
-        // invalidate affected files
-        $this->invalidateCacheForChangedAndErroredFiles($processResult);
```
Comment (samsonasik) [inline src/Console/Command/ProcessCommand.php:93]: is this will work on `NonPhpFileProcessor` as well?

https://github.com/rectorphp/rector-src/blob/0204a2353850c98a38dba36c9a8dd031ae2da0c3/src/NonPhpFile/NonPhpFileProcessor.php#L18

Comment (yguedidi) [reply src/Console/Command/ProcessCommand.php:93]: Yes it should, as the caching/invalidation is done in ApplicationFileProcessor, after the processors are called.
But it seems I missed adding those files as cacheable ones when possible, see [this force-push diff](https://github.com/rectorphp/rector-src/compare/cba16d39eb56c68d4d03b8379d36fd0a35461d5a..cc2811b07fe276eadad802cab6e2a47f2bda23be) (also run rector fixes)

**Review by samsonasik — APPROVED** [review]
Looking good for me 👍

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by staabm** [comment]
I think we need the same fix in https://github.com/easy-coding-standard/easy-coding-standard. @yguedidi could you check that?

**Comment by yguedidi** [comment]
@staabm I'm not using ECS, so I can't guarantee that I can come with a PR any time soon there sorry.
It's fine if some else inspire from this PR to implement it in ECS :)
