### PR TITLE
LocallyCalledStaticMethodToNonStaticRector with method args

### LINKED ISSUE #7992: Incorrect behavior of LocallyCalledStaticMethodToNonStaticRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.17.1, last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a94fe4b3-0e91-4aa2-b298-4ec49c34b32f

```php
<?php

final class DemoFile
{
    public function run(string $var): bool
    {
        $checkRes = self::check($var);
        
        return $checkRes;
    }
    
    private static function check($value): bool
    {
        return true;
    }
}
```

### Responsible rules

* `LocallyCalledStaticMethodToNonStaticRector`

## Actual Behavior
```php
public function run(string $var): bool
     {
-        $checkRes = self::check($var);
+        $checkRes = $this->check();
         
         return $checkRes;
     }
     
-    private static function check($value): bool
+    private function check($value): bool
     {
         return true;
     }
```

## Expected Behavior
```php
public function run(string $var): bool
     {
-        $checkRes = self::check($var);
+        $checkRes = $this->check($var);
         
         return $checkRes;
     }
     
-    private static function check($value): bool
+    private function check($value): bool
     {
         return true;
     }
```

### PR DESCRIPTION
**Pull request by toastedghost**
* keep method args on refactoring

Fixes https://github.com/rectorphp/rector/issues/7992

### CODE REVIEW

File: rules-tests/RemovingStatic/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector/Fixture/method_with_arg.php.inc [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+        self::someStatic($arg);
+    }
+
+    private static function someStatic($arg)
+    {
+    }
+}
+
+?>
+    -----
```
Comment (samsonasik) [inline rules-tests/RemovingStatic/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector/Fixture/method_with_arg.php.inc]:
```suggestion
-----
```

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @toastedghost

**Comment by toastedghost** [comment]
Please, glad to help you @samsonasik for this project
