### PR TITLE
Fix annotation to attribute rector with doctrine table and nested uniqueConstraints option

### LINKED ISSUE #7011: Incorrect behavior of AnnotationToAttributeRector with doctrine @Table annotation and uniqueConstraints option
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.16      |
| Installed as   | composer dependency  |

When converting a `@ORM\Table` annotation with `uniqueConstraints` option, this option is lost after the refactor. I debugged the issue to it's origin but wasn't sure where to submit fixes to as I needed a failing test in `rector/rector-doctrine` and the fix in `rector/rector-src`.

I was able to trace the issue back to this change: https://github.com/rectorphp/rector-src/pull/1766/files#diff-3f761daa31da7830aaefc8ad8ed701778a120a703ad4d205965ecb0f80c52ce8R32. But I'm not sure why is was specifically added for that option and if it can be removed again. If the array item is removed I get the expected result.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/db6e1e00-8128-4647-b391-28e711f077e4

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="categories", uniqueConstraints={@ORM\UniqueConstraint(name="name_idx", columns={"name"})})
 */
class Category
{
    private $name;
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

```php
<?php

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'categories', uniqueConstraints: [new ORM\UniqueConstraint(name: 'name_idx', columns: ['name'])])]
class Category
{
    private $name;
}
```

### PR DESCRIPTION
**Pull request by acrobat**
fixes rectorphp/rector#7011

### CODE REVIEW

File: packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php [hunk 1]
```diff
@@ -45,6 +42,8 @@ public function __construct(
         // nested indexes supported only since PHP 8.1
         if (! $phpVersionProvider->isAtLeastPhpVersion(PhpVersionFeature::NEW_INITIALIZERS)) {
             $this->unwrappedAnnotations['Doctrine\ORM\Mapping\Table'][] = 'indexes';
+            $this->unwrappedAnnotations['Doctrine\ORM\Mapping\Table'][] = 'uniqueConstraints';
+            $this->unwrappedAnnotations['Doctrine\ORM\Mapping\Entity'][] = 'uniqueConstraints';
```
Comment (samsonasik) [inline packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php]: You can tweak the phpstan notice with single assign

Comment (acrobat) [reply packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php]: Fixed!

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:
