### PR TITLE
[TypeDeclaration] Handle infinite loop on array_reverse with index on AddMethodCallBasedStrictParamTypeRector on php8+ feature

### LINKED ISSUE #7896: AddMethodCallBasedStrictParamTypeRector timeout when checking index from array_reverse
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.25 |

When using the `AddMethodCallBasedStrictParamTypeRector` rule and checking the index of an array created from array_reverse, rector ends up getting stuck and eventually triggers the timeout.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/fe336fa4-194f-4bd3-8922-2780d5141d13

Changing:
`$parts = array_reverse(explode('/', '/some/test/url'));` to `$parts = explode('/', '/some/test/url');`

OR removing the lines:
```
if ($index === 0) {
    continue;
}
```

Allows rector to proceed

## Expected Behaviour

Rector should be able to proceed without causing a timeout.

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector/issues/7896
Ref https://getrector.com/demo/fe336fa4-194f-4bd3-8922-2780d5141d13

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed with verify min or max of IntegerRangeType is null /cc @internalsystemerror

**Comment by samsonasik** [comment]
Rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

File: packages/PHPStanStaticTypeMapper/TypeMapper/IntegerRangeTypeMapper.php [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+            return null;
+        }
+
+        if ($type->getMin() === null) {
+            return null;
+        }
+
+        if ($type->getMax() === null) {
+            return null;
+        }
```
Comment (samsonasik) [inline packages/PHPStanStaticTypeMapper/TypeMapper/IntegerRangeTypeMapper.php]: min, max value null seems valid value https://phpstan.org/r/765b0694-8832-4b65-98b7-4944d2914bc3

`getMin()` === null printed as `min`

Comment (samsonasik) [reply packages/PHPStanStaticTypeMapper/TypeMapper/IntegerRangeTypeMapper.php]: all type applied with string type seems also valid https://phpstan.org/r/474c8c8b-1d17-4ba2-b6bf-c243b7390e19 for this type:

```php
^ PHPStan\Type\UnionType^ {#23962
  -sortedTypes: false
  -cachedDescriptions: []
  -types: array:3 [
    0 => PHPStan\Type\IntegerRangeType^ {#22268
      -min: null
      -max: -1
    }
    1 => PHPStan\Type\IntegerRangeType^ {#22323
      -min: 1
      -max: null
    }
    2 => PHPStan\Type\StringType^ {#19486}
  ]
  -normalized: false
}
```

Comment (samsonasik) [reply packages/PHPStanStaticTypeMapper/TypeMapper/IntegerRangeTypeMapper.php]: The issue seems somehow used index as integer on this type:

```
              // here index must be integer...
              $this->someOtherMethod($index, $uri);
        }
    }

    private function someOtherMethod(int $index, string $uri)
    {
        return sprintf('%d-%s', $index, $uri);
    }
```

Comment (samsonasik) [reply packages/PHPStanStaticTypeMapper/TypeMapper/IntegerRangeTypeMapper.php]: I got it, it seems due to combination of `UnionType` + `MixedType`, then it should be skipped, see https://github.com/rectorphp/rector-src/pull/3678/commits/42bcdaa33128b0672796f31e14d1165517c9ce84#diff-42a5a059b66868f3ede960ea9a50a3591de610668457d76063ac2f6dc653dcc3

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by internalsystemerror** [comment]
ty @samsonasik i was still figuring out the problem and you've got the fix already!

File: rules/TypeDeclaration/NodeAnalyzer/ClassMethodParamTypeCompleter.php [hunk 2]
```diff
@@ -38,8 +38,13 @@ public function __construct(
     public function complete(ClassMethod $classMethod, array $classParameterTypes, int $maxUnionTypes): ?ClassMethod
     {
         $hasChanged = false;
+        $totalTypes = count($classParameterTypes);
 
         foreach ($classParameterTypes as $position => $argumentStaticType) {
+            if ($totalTypes > 1 && $argumentStaticType instanceof UnionType) {
+                return null;
+            }
```
Comment (samsonasik) [inline rules/TypeDeclaration/NodeAnalyzer/ClassMethodParamTypeCompleter.php:46]: @internalsystemerror I just re-check that this verify is not valid, because multiple args no longer working now when one of them is UnionType, eg:

```php
final class NarrowUnion
{
    public function run(MethodCall $methodCall, StaticCall $staticCall, String_ $string)
    {
        $this->someExpr($methodCall, $staticCall);
        $this->someExpr($staticCall, $staticCall);
        $this->someExpr($string, $staticCall);
    }

    private function someExpr($expr, $staticCall)
    {
    }
}
```

above is now completely skipped, which actually should be:

```diff
-     private function someExpr($expr, $staticCall)
+    private function someExpr(\PhpParser\Node\Expr\MethodCall|\PhpParser\Node\Expr\StaticCall|\PhpParser\Node\Scalar\String_ $expr, \PhpParser\Node\Expr\StaticCall| $staticCall)
    {
    }
```

I will add separate PR for that :)
