### PR TITLE
[CodingStyle] Fix re-print of self in PreferThisOrSelfMethodCallRector

### LINKED ISSUE #7363: Incorrect behavior of PreferThisOrSelfMethodCallRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.7     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0c8e9f4c-916f-43fb-962e-e50c6b290f95

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoFile extends TestCase
{
    /**
     * @test
     */
    public function sourcesWithoutRight()
    {
        $episode = new Episode();
        self::assertSame(
            ["hls" => [], "hds" => [], "smooth" => [], "dash" => [], "progressive_download" => []], 
            $this->sources->getSourcesByEpisode($episode)
        );
    }
}
```

### Responsible rules

* `PreferThisOrSelfMethodCallRector`

## Expected Behavior

I'm currently upgrading a legacy project which still uses a "max line length of 120" (PSR2 is ... old? wow). I do not want to sacrifice this rule, because there is ongoing development on this project - so I want to use best of both worlds. 

Rector should just skip it. There is effectively no change, since it's already "self".

Btw.: great job. I :heart: rector.

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixes https://github.com/rectorphp/rector/issues/7363

### CODE REVIEW

File: rules/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php [hunk 1]
```diff
@@ -120,10 +120,8 @@ public function configure(array $configuration): void
 
     private function processToSelf(MethodCall | StaticCall $node): ?StaticCall
     {
-        if ($node instanceof StaticCall && ! $this->isNames(
-            $node->class,
-            [ObjectReference::SELF, ObjectReference::STATIC]
-        )) {
+        // class is already "self", let's skip it
+        if ($node instanceof StaticCall && $this->isName($node->class, ObjectReference::SELF)) {
```
Comment (TomasVotruba) [inline rules/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php:124]: @samsonasik I have noticed your PR too late, before I sent this one.
The bug seems here, the `self` name should be skipped here.

**Comment by samsonasik** [comment]
@TomasVotruba I created PR for this, commit https://github.com/rectorphp/rector-src/pull/2758/commits/cfc30b2a21e1c715a8fd28daf58468c4c6092a7f can be cherry-picked in case you prefere this

File: rules/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php (hunk 1 above)
Comment (samsonasik) [reply rules/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php:124]: Please chery-pick commit https://github.com/rectorphp/rector-src/pull/2758/commits/cfc30b2a21e1c715a8fd28daf58468c4c6092a7f to ensure the functionality is same, as it seems due to printing, not different of self/this

Comment (TomasVotruba) [reply rules/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php:124]: I've started with long code, then shorten it. It could be as short as:

```php
self::asertSame(
	'',
	''
);
```

I've added your commit to have it in CI :+1:

File: rules-tests/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Fixture/skip_multi_line_already_this.php.inc [hunk 2]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+namespace Rector\Tests\CodingStyle\Rector\MethodCall\PreferThisOrSelfMethodCallRector\Fixture;
+
+use Rector\Tests\CodingStyle\Rector\MethodCall\PreferThisOrSelfMethodCallRector\Source\SomeAbstractTestCase;
```
Comment (samsonasik) [inline rules-tests/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Fixture/skip_multi_line_already_this.php.inc]: wrong use:

```suggestion
use Rector\Tests\CodingStyle\Rector\MethodCall\PreferThisOrSelfMethodCallRector\Source\BeLocalClass;
```

Comment (TomasVotruba) [reply rules-tests/CodingStyle/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Fixture/skip_multi_line_already_this.php.inc]: I pushed this locally

**Review by samsonasik — APPROVED** [review]
