### PR TITLE
[Php55] Handle crash on ([[:upper:]]+) regex on PregReplaceEModifierRector

### LINKED ISSUE #7573: Crash in PregReplaceEModifierRector
# Bug Report

Running Rector on https://github.com/fossar/selfoss/blob/3ac16cd741f2d6cf591dc17ab5238cd48fbc6f54/src/helpers/Configuration.php makes it crash with:

```
 [ERROR] Could not process "/home/jtojnar/Projects/selfoss/src/helpers/Configuration.php" file, due to:                 
         "System error: "Syntax error, unexpected '$':1"                                                                
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(143):                         
         PhpParser\ParserAbstract->doParse()                                                                            
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(48):                         
         PhpParser\ParserAbstract->parse('<?php _$0;', Object(PhpParser\ErrorHandler\Throwing))                         
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31):                         
         PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php
         _$0;')                                                                                                         
         #3 vendor/rector/rector/src/PhpParser/Parser/SimplePhpParser.php(37): PhpParser\Parser\Multiple->parse('<?php _$0;')
         #4 vendor/rector/rector/rules/Php72/NodeFactory/AnonymousFunctionFactory.php(171):                             
         Rector\Core\PhpParser\Parser\SimplePhpParser->parseString('<?php _$0;')                                        
         #5 vendor/rector/rector/rules/Php55/Rector/FuncCall/PregReplaceEModifierRector.php(103):                       
         Rector\Php72\NodeFactory\AnonymousFunctionFactory->createAnonymousFunctionFromExpr(Object(PhpParser\Node\Scalar\String_
         ))                                                                                                             
         #6 vendor/rector/rector/src/Rector/AbstractRector.php(220):                                                    
         Rector\Php55\Rector\FuncCall\PregReplaceEModifierRector->refactor(Object(PhpParser\Node\Expr\FuncCall))        
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))                             
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #12 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #13 vendor/rector/rector/src/Application/FileProcessor.php(60):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #14 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(133):                              
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #15 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(101):                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObject\Applica
         tion\File), Object(Rector\Core\ValueObject\Configuration))                                                     
         #16 vendor/rector/rector/packages/Parallel/WorkerRunner.php(98):                                               
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #17 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #18 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):                                        
         RectorPrefix202211\Evenement\EventEmitter->emit('data', Array)                                                 
         #19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202211\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #20 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202211\Evenement\EventEmitter->emit('data',
         Array)                                                                                                         
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202211\React\Stream\Util::RectorPrefix202211\React\Stream\{closure}('{"action":"main...')          
         #22 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202211\Evenement\EventEmitter->emit('data', Array)                                                 
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202211\React\Stream\DuplexResourceStream->handleData(Resource id #2766)                            
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202211\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #25 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202211\React\EventLoop\StreamSelectLoop->run()                                                     
         #26 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):                                      
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202211\Symfony\Component\Console\Input\ArgvInput)
         , Object(RectorPrefix202211\Symfony\Component\Console\Output\ConsoleOutput))                                   
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(896):                                          
         RectorPrefix202211\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202211\Symfony\Component\Console\I
         nput\ArgvInput), Object(RectorPrefix202211\Symfony\Component\Console\Output\ConsoleOutput))                    
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(312):                                          
         RectorPrefix202211\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\WorkerCommand
         ), Object(RectorPrefix202211\Symfony\Component\Console\Input\ArgvInput),                                       
         Object(RectorPrefix202211\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #29 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202211\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202211\Symfony\Component\Console\Inp
         ut\ArgvInput), Object(RectorPrefix202211\Symfony\Component\Console\Output\ConsoleOutput))                      
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(208):                                          
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202211\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202211\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #31 vendor/rector/rector/bin/rector.php(128): RectorPrefix202211\Symfony\Component\Console\Application->run()  
         #32 vendor/rector/rector/bin/rector(5): require_once('/home/jtojnar/P...')                                     
         #33 vendor/bin/rector(120): include('/home/jtojnar/P...')                                                      
         #34 {main}". On line: 269                                                                                      
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main@ecee0c released at 2022-11-02 15:41:41    |

## Minimal PHP Code Causing Issue

```php
<?php
preg_replace('([[:upper:]]+)', '_$0', 'foo');
```

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
       LevelSetList::UP_TO_PHP_72
    ]);
};
```

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class SkipNoModifier
{
    public function run()
    {
        echo preg_replace('([[:upper:]]+)', '_$0', 'FOO');
    }
}
```

It currently cause crash:

```bash
There was 1 error:

1) Rector\Tests\Php55\Rector\FuncCall\PregReplaceEModifierRector\PregReplaceEModifierRectorTest::test with data set #0 ('/Users/samsonasik/www/rector-...hp.inc')
PhpParser\Error: Syntax error, unexpected '$' on line 1
```

It should be skipped instead.

Fixes https://github.com/rectorphp/rector/issues/7573

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @jtojnar

**Comment by samsonasik** [comment]
The issue seems on `[[:upper:]]+)` detected as modifier.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

File: rules/Php55/RegexMatcher.php [hunk 1]
```diff
@@ -46,6 +46,10 @@ public function resolvePatternExpressionWithoutEIfFound(Expr $expr): Concat|Stri
                 return null;
```
Comment (jtojnar) [inline rules/Php55/RegexMatcher.php:46]: Won’t this not handle `(…)e` now?

File: rules/Php55/RegexMatcher.php [hunk 2]
```diff
@@ -46,6 +46,10 @@ public function resolvePatternExpressionWithoutEIfFound(Expr $expr): Concat|Stri
...
             }
 
+            if ($delimiter === '(' && $pattern[strlen($pattern) - 1] === ')') {
```
Comment (jtojnar) [inline rules/Php55/RegexMatcher.php]: Also, other brackets can be used as delimiters, to avoid having to escape the characters in the expression: https://www.php.net/manual/en/regexp.reference.delimiters.php

Comment (samsonasik) [reply rules/Php55/RegexMatcher.php]: I add more brackets to handle that https://github.com/rectorphp/rector-src/pull/3037/commits/78553617ca114cc3bf311e8e7cd9f92c28d4e033

File: rules/Php55/RegexMatcher.php (hunk 1 above)
Comment (samsonasik) [reply rules/Php55/RegexMatcher.php:46]: that seems require separate PR as the modifer can not only `e`:

```php
echo preg_replace('{[[:upper:]]+}se', '_$0', 'FOO');
```

which seems needs extra check with `e` modifier which the change must only remove the `e`, to be:

```php
echo preg_replace('{[[:upper:]]+}s', '_$0', 'FOO');
```

Also possibly other use cases for that.

Feel free to provide a different PR for solution for that if you found a solution first for that.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:
