### PR TITLE
[fix] avoid changing generic interface in NarrowObjectReturnTypeRector, focus on objects as in definition

### LINKED ISSUE #9525: NarrowObjectReturnTypeRector replaces interface with implementing concrete class
# Bug Report

| Subject        | Details                                            |
| :------------- | :------------------------------------------------- |
| Rector version | e.g. v2.2.10 (invoke `vendor/bin/rector --version`) |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/c43e917d-7f01-44c0-b43f-426f51ec938c

## Expected Behaviour

No changes in the return type of `Vhost\Healthz::handle`. My expectation here was that Rector would respect the return type and anyone call that method should care about how I get to my return value, only that it implements that interface.

P.S. Not sure how much of this relates to #9489

### PR DESCRIPTION
**Pull request by TomasVotruba**
I've accidenally merged a different feature than intended. The `NarrowObjectReturnTypeRector` replaced not only objects, but also interfaces.  That goes against desired behavior, from PHPStan rule https://github.com/rectorphp/type-perfect#5-narrow-return-types

> "Narrows return type from generic `object` or parent class to specific class in final classes/methods"

It should not replae interfaces, moreover generic ones, as those allow easy replacement with different class and make code readable. That would scope of some `ReplaceInterfaceWithObjectReturnTypeRector` :) but it doesn't make sense for making code less readable.

Saying that, I'm narrowing (pun intended) this rule to handle only `object` and more general/`astract` objects :+1: 

---

Closes https://github.com/rectorphp/rector/issues/9525

### CODE REVIEW

File: rules/TypeDeclaration/Rector/ClassMethod/NarrowObjectReturnTypeRector.php [hunk 1]
```diff
@@ -124,24 +124,35 @@ public function refactor(Node $node): ?Node
...
-            return null;
+            $declaredTypeClassReflection = $this->reflectionProvider->getClass($declaredType);
+
+            // already last final object
+            if ($declaredTypeClassReflection->isFinalByKeyword()) {
+                return null;
+            }
+
+            // this rule narrows only object or class types, not interfaces
+            if (! $declaredTypeClassReflection->isClass()) {
```
Comment (samsonasik) [inline rules/TypeDeclaration/Rector/ClassMethod/NarrowObjectReturnTypeRector.php:153]: On private method, change return interface to actual class should be allowed, since private method usually not be mockable in test, and not follow any contract.

Comment (samsonasik) [reply rules/TypeDeclaration/Rector/ClassMethod/NarrowObjectReturnTypeRector.php:153]: I created PR:

- https://github.com/rectorphp/rector-src/pull/7701

for it.

Comment (staabm) [inline rules/TypeDeclaration/Rector/ClassMethod/NarrowObjectReturnTypeRector.php:153]: I think it should also not narrow on abstract class
