### PR TITLE
[Php85] Skip defined int or string on ArrayKeyExistsNullToEmptyStringRector

### LINKED ISSUE #9560: ArrayKeyExistsNullToEmptyStringRector forces me to cast to string when it is not necessary
# Bug Report

Hello, I am in the process of upgrading to PHP 8.5, and new Rector rules have appeared via the PHP 8.5 set. One of these rules is “ArrayKeyExistsNullToEmptyStringRector.” The presentation of this rule on the website is great, especially since PHP 8.5 has deprecated passing potentially null as the first parameter of array_key_exists.

Except that it occurs even when the value is not necessarily null, for int|string for example.

Is this normal?

| Subject        | Details |
| :------------- | :------------------------------------------------- |
| Rector version | 2.2.14 |
| PHP version | 8.5 |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/50d047e9-daab-4e97-8805-33c2ec9bd3b7

## Expected Behaviour

I don't think it's necessary to cast to string when the input value is typed as int or string or int|string, only when it is nullable. Please let me know if I'm on the wrong track somewhere!

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://getrector.com/demo/5dee0eb0-aea7-4e62-88a4-90f54eae39de
Fixes https://github.com/rectorphp/rector/issues/9560

`array_key_exists` allow both `int` or `string` key.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @MaxencePaulin

**Comment by samsonasik** [comment]
@TomasVotruba ready 👍

**Comment by samsonasik** [comment]
@TomasVotruba mergeable?

File: rules-tests/Php85/Rector/FuncCall/ArrayKeyExistsNullToEmptyStringRector/Fixture/skip_defined_int_or_string.php.inc [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+        }
+
+        if (!array_key_exists($this->todos[$index]['unique_key'], $this->selectedTodos)) {
+            $this->selectedTodos[$this->todos[$index]['unique_key']] = $this->todos[$index]['label'];
+            return 'Todo selected !';
+        }
+
+        return 'Todo already selected !';
+    }
+}
```
Comment (TomasVotruba) [inline rules-tests/Php85/Rector/FuncCall/ArrayKeyExistsNullToEmptyStringRector/Fixture/skip_defined_int_or_string.php.inc:23]: Could you make this fixture simpler, but keep its point? It's quite long to read/understand

Comment (MaxencePaulin) [reply rules-tests/Php85/Rector/FuncCall/ArrayKeyExistsNullToEmptyStringRector/Fixture/skip_defined_int_or_string.php.inc:23]: It's maybe better ?

https://getrector.com/demo/88081cac-0997-42a0-983b-d98928ff6d54

@samsonasik

Comment (samsonasik) [reply rules-tests/Php85/Rector/FuncCall/ArrayKeyExistsNullToEmptyStringRector/Fixture/skip_defined_int_or_string.php.inc:23]: sure, simplified per @MaxencePaulin above https://github.com/rectorphp/rector-src/pull/7758/changes/2f320ba56ffd367c5098796d51159d53b7b67e97 👍

**Comment by samsonasik** [comment]
@TomasVotruba ready 👍

**Comment by TomasVotruba** [comment]
Much better, thank you :+1:
