### PR TITLE
[CodingStyle] Remove usage of Reflection::expandClassName() from nette/utils 4.0 as cause bug on downgrade

### LINKED ISSUE #8565: nette/utils 4.0 cause error RectorPrefix202403\Nette\Utils\Reflection::getUseStatements(): Return value must be of type array, null returned
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

## Minimal PHP Code Causing Issue

Ref https://github.com/rectorphp/getrector-com/issues/2142

also reproducible locally on other project:

```
➜  ErrorHeroModule git:(master) bin/rector 
 58/58 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "/Users/samsonasik/www/GithubModules/ErrorHeroModule/src/Listener/MvcFactory.php" file, due  
         to:                                                                                                            
         "System error: "RectorPrefix202403\Nette\Utils\Reflection::getUseStatements(): Return value must be of type    
         array, null returned"                                                                                          
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 158
```

 The issue seems when it used on `Reflection::expandClassName()` 

https://github.com/rectorphp/rector/blob/dac0717196e2d18bfe84cd2c07d1a8b494358944/rules/CodingStyle/ClassNameImport/ShortNameResolver.php#L208

## Expected Behaviour

It should works.

### PR DESCRIPTION
**Pull request by samsonasik**
The syntax of downgrade `PhpToken::tokenize()` and it usage call another method with `->is()` usage is too complex to downgrade. 

I think this usage can be removed.

Closes https://github.com/rectorphp/getrector-com/issues/2142
Closes https://github.com/rectorphp/rector/issues/8565

### CODE REVIEW

File: tests/Issues/AnnotationToAttributeRenameAutoImport/Fixture/with_existing_attribute.php.inc [hunk 1]
```diff
@@ -20,12 +20,11 @@ class WithExistingAttribute extends AbstractController
 
 namespace Rector\Tests\Issues\RenameAnnotationToAttributeAutoImport\Fixture;
 
-use Symfony\Component\Security\Http\Attribute\IsGranted;
 use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
 use Symfony\Component\Routing\Annotation\Route;
 
 #[Route(path: '/pro/{id}/networks/{networkId}/sectors', name: 'api_network_sectors', requirements: ['id' => '\d+', 'networkId' => '\d+'])]
-#[IsGranted('TEST')]
+#[\Symfony\Component\Security\Http\Attribute\IsGranted('TEST')]
```
Comment (samsonasik) [inline tests/Issues/AnnotationToAttributeRenameAutoImport/Fixture/with_existing_attribute.php.inc:27]: @TomasVotruba this is only drawback for this, as this consist of rename + make attribute, and run twice will auto-import it, see fixture https://github.com/rectorphp/rector-src/pull/5740/files#diff-fe6ad097b1f7d2f4670de3d6f764aabffb83f16862d8d7893e464012e0be1702

which I think it is ok :)

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

File: tests/Issues/AnnotationToAttributeRenameAutoImport/Fixture/with_existing_attribute.php.inc (hunk 1 above)
Comment (samsonasik) [reply tests/Issues/AnnotationToAttributeRenameAutoImport/Fixture/with_existing_attribute.php.inc:27]: It seems it can be tweaked with original name check, I created new PR to cover it:

- https://github.com/rectorphp/rector-src/pull/5741

Comment (TomasVotruba) [reply tests/Issues/AnnotationToAttributeRenameAutoImport/Fixture/with_existing_attribute.php.inc:27]: Looks good to me :)
