### PR TITLE
[Php73] Skip escaped Dash on RegexDashEscapeRector

### LINKED ISSUE #7356: Incorrect behavior of RegexDashEscapeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/f7c15ce4-8dbe-4f79-bd1e-88c7a9d10c3c

```php
<?php

preg_match('/[\-\w]/');
```

### Responsible rules

* `RegexDashEscapeRector`

## Expected Behavior

Rector should skip updating this code

## Regex101.com interpretation of code
**Pre-change PCRE:**
pre_change_pcre
**Pre-change PCRE2:**
pre_change_pcre2
**Post-change PCRE:**
post_change_pcre
**Post-change PCRE2:**
post_change_pcre2

### PR DESCRIPTION
**Pull request by ebrigham1**
# Failing Test for RegexDashEscapeRector

Based on https://getrector.org/demo/f7c15ce4-8dbe-4f79-bd1e-88c7a9d10c3c

Fixes https://github.com/rectorphp/rector/issues/7356

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1: 

Could you add the fix of RegexDashEscapeRector too?

**Comment by ebrigham1** [comment]
@TomasVotruba I can give it a shot, but I'm not sure I know the fix yet. I'll have some time tonight to play with it and see if I can come up with something.

**Comment by ebrigham1** [comment]
### Since I've updated an existing test I think this PR should be reviewed with extra scrutiny.

@TomasVotruba I made some changes that I believe work, but it involves changes to a test case I don't understand. This test was added [here](https://github.com/rectorphp/rector-src/commit/b30eccb246f5ae1349e47046a173e3bf56fdef20) ([PR](https://github.com/rectorphp/rector/pull/3191)) by you which appears to have been spawned by this [issue](https://github.com/rectorphp/rector/issues/3190). I can't see the original use case from the issue as it is no longer linkable. I do however see the [use case](https://3v4l.org/HOedn) you added on the multi php website.

I don't quite understand why we expect rector to update this [code](https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php73/Rector/FuncCall/RegexDashEscapeRector/Fixture/slashes.php.inc) and add a slash. Personally I would expect it not to update it, but maybe I'm missing something?

### Regex101
**Pre-change PCRE:**
pre_change_pcre
**Pre-change PCRE2:**
pre_change_pcre2
**Post-change PCRE:**
post_change_pcre
**Post-change PCRE2:**
post_change_pcre2

To me this is indicating that the change this test is asserting is not desired, but again maybe I've missed something.

File: rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ final class RegexDashEscapeRector extends AbstractRector implements MinPhpVersio
      * @var string
      * @see https://regex101.com/r/TBVme9/8
```
Comment (samsonasik) [inline rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php]: please update the regex101 uri as well to show how it differentiate it, after change, click "Update" instead of "Save" so we have continuity increment number `/9` of path.

Comment (ebrigham1) [reply rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php]: @samsonasik done https://github.com/rectorphp/rector-src/pull/2753/commits/6b223d1d09e7648a63d73925281b7508630c331c

[Regex101](https://regex101.com/r/TBVme9/9)

Comment (samsonasik) [reply rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php]: Could you update the regex101 content too for the failing test case? Or it already covered?

Comment (ebrigham1) [reply rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php]: It's already kinda covered by `[a\-\w]` not being matched its essentially the same thing. Honestly the slashes test case can be removed entirely in my opinion as it is the same as the test case I added at this point. Again this worries me because I didn't see the original use case from the issue as it was a broken link but the test case added from the issue I believe was incorrect from looking at regex101.

Comment (samsonasik) [reply rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php]: Thank you, /cc @sidux could you verify it as the author that create original issue https://github.com/rectorphp/rector/issues/3190 for it? Thank you.

**Comment by samsonasik** [comment]
Btw, could you update PR title to something like : 

```
[Php73] Skip escaped Dash on RegexDashEscapeRector

**Comment by ebrigham1** [comment]
@samsonasik done

**Review by samsonasik — APPROVED** [review]
Skip refactor usually harmless, I am ok with this, we can revert and add test if we have a real use case which double escape actually needed.

**Comment by TomasVotruba** [comment]
Thank you for solving this :+1:
