### PR TITLE
[DeadCode] Handle crash on valid conditional type on RemoveUselessReturnTagRector

### LINKED ISSUE #8907: System error: "Call to undefined method PHPStan\Type\ConditionalTypeForParameter::getItemType()
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | d49ace3c33ae8e662791fd1bb82e1467a0a48530             |

## Stacktrace

```
[ERROR] Could not process "/Volumes/CS/www/cosmos/src/Shared/Infrastructure/Helper/ArrayHelper.php"
         file, due to:
         "System error: "Call to undefined method
         PHPStan\Type\ConditionalTypeForParameter::getItemType()"

         Stack trace:
         #0 vendor/rector/rector/src/NodeTypeResolver/TypeComparator/TypeComparator.php(76):
         Rector\TypeDeclaration\TypeNormalizer->normalizeArrayOfUnionToUnionArray(Object(PHPStan\Type\
         ConditionalTypeForParameter))
         #1 vendor/rector/rector/src/NodeTypeResolver/TypeComparator/TypeComparator.php(87):
         Rector\NodeTypeResolver\TypeComparator\TypeComparator->areTypesEqual(Object(PHPStan\Type\Arra
         yType), Object(PHPStan\Type\ConditionalTypeForParameter))
         #2 vendor/rector/rector/rules/DeadCode/PhpDoc/DeadReturnTagValueNodeAnalyzer.php(85):
         Rector\NodeTypeResolver\TypeComparator\TypeComparator->arePhpParserAndPhpStanPhpDocTypesEqual
         (Object(PhpParser\Node\Identifier),
         Object(PHPStan\PhpDocParser\Ast\Type\ConditionalTypeForParameterNode),
         Object(PhpParser\Node\Stmt\ClassMethod))
         #3 vendor/rector/rector/rules/DeadCode/PhpDoc/TagRemover/ReturnTagRemover.php(31):
         Rector\DeadCode\PhpDoc\DeadReturnTagValueNodeAnalyzer->isDead(Object(PHPStan\PhpDocParser\Ast
         \PhpDoc\ReturnTagValueNode), Object(PhpParser\Node\Stmt\ClassMethod))
         #4
         vendor/rector/rector/rules/DeadCode/Rector/ClassMethod/RemoveUselessReturnTagRector.php(78):
         Rector\DeadCode\PhpDoc\TagRemover\ReturnTagRemover->removeReturnTagIfUseless(Object(Rector\Be
         tterPhpDocParser\PhpDocInfo\PhpDocInfo), Object(PhpParser\Node\Stmt\ClassMethod))
         #5 vendor/rector/rector/src/Rector/AbstractRector.php(111):
         Rector\DeadCode\Rector\ClassMethod\RemoveUselessReturnTagRector->refactor(Object(PhpParser\No
         de\Stmt\ClassMethod))
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(165):
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(90):
         PhpParser\NodeTraverser->traverseArray(Array)
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(90):
         PhpParser\NodeTraverser->traverseArray(Array)
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(71):
         PhpParser\NodeTraverser->traverseArray(Array)
         #12 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(43):
         PhpParser\NodeTraverser->traverse(Array)
         #13 vendor/rector/rector/src/Application/FileProcessor.php(103):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #14 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(174):
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),
         Object(Rector\ValueObject\Configuration))
         #15 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(151):
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Applicatio
         n\File), Object(Rector\ValueObject\Configuration))
         #16 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(128):
         Rector\Application\ApplicationFileProcessor->processFiles(Array,
         Object(Rector\ValueObject\Configuration), Object(Closure), Object(Closure))
         #17 vendor/rector/rector/src/Console/Command/ProcessCommand.php(150):
         Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration),
         Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput))
         #18 vendor/rector/rector/vendor/symfony/console/Command/Command.php(285):
         Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202411\Symfony\Component\Co
         nsole\Input\ArgvInput),
         Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
         #19 vendor/rector/rector/vendor/symfony/console/Application.php(900):
         RectorPrefix202411\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202411\S
         ymfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
         #20 vendor/rector/rector/vendor/symfony/console/Application.php(279):
         RectorPrefix202411\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\
         Command\ProcessCommand), Object(RectorPrefix202411\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
         #21 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202411\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202411\Sym
         fony\Component\Console\Input\ArgvInput),                                                               Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))
         #22 vendor/rector/rector/vendor/symfony/console/Application.php(162):
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202411\Symfony\Component\Console\
         Input\ArgvInput), Object(RectorPrefix202411\Symfony\Component\Console\Output\ConsoleOutput))           #23 vendor/rector/rector/bin/rector.php(130):
         RectorPrefix202411\Symfony\Component\Console\Application->run()
         #24 vendor/rector/rector/bin/rector(5): require_once('/Volumes/CS/www...')                             #25 vendor/bin/rector(119): include('/Volumes/CS/www...')
         #26 {main}". On line: 57
```

Code that errors:
```php
final readonly class ArrayHelper
{
    /**
     * Groups an array by a key returned by a callback.
     *
     * Example:
     *
     * return ArrayHelper::groupBy(
     *     $results,
     *     fn ($ticket) => (string) $ticket->getFile()->getId(),
     * );
     *
     * @template TValue of mixed
     * @template TCallbackValue of mixed
     * @template TKey of array-key
     * @param array<TValue> $input
     * @param callable(TValue): TKey $keyCallback
     * @param null|callable(TValue): TCallbackValue $valueCallback
     *
     * @return ($valueCallback is null ? array<TKey, non-empty-list<TValue>> : array<TKey, non-empty-list<TCallbackValue>>)
     */
    public static function groupBy(array $input, callable $keyCallback, ?callable $valueCallback = null) : array
    {
        $output = [];
        foreach ($input as $result) {
            $output[$keyCallback($result)][] = $valueCallback !== null ? $valueCallback($result) : $result;
        }

        return $output;
    }
}
```

/cc @samsonasik

### PR DESCRIPTION
**Pull request by samsonasik**
Fix crash:

```
There was 1 error:

1) Rector\Tests\DeadCode\Rector\ClassMethod\RemoveUselessReturnTagRector\RemoveUselessReturnTagRectorTest::test with data set #34 ('/Users/samsonasik/www/rector-...hp.inc')
Error: Call to undefined method PHPStan\Type\ConditionalTypeForParameter::getItemType()

/Users/samsonasik/www/rector-src/rules/TypeDeclaration/TypeNormalizer.php:61
/Users/samsonasik/www/rector-src/src/NodeTypeResolver/TypeComparator/TypeComparator.php:60
```

Fixes https://github.com/rectorphp/rector/issues/8907

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @ruudk

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by ruudk** [comment]
🔥 🥷 ⚡

File: rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNewArrayRector.php [hunk 1]
```diff
@@ -147,7 +147,7 @@ private function processAddArrayReturnType(
         ClassMethod|Function_|Closure $node,
         Type $returnType
     ): ClassMethod|Function_|Closure|null {
-        if (! $returnType->isArray()->yes()) {
+        if (! $returnType instanceof ArrayType && ! $returnType instanceof ConstantArrayType) {
```
Comment (staabm) [inline rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNewArrayRector.php:150]: Won't this stop working on a union of arrays?

Comment (staabm) [reply rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNewArrayRector.php:150]: Or on non-empty-array, which is a intersection type

Comment (samsonasik) [reply rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNewArrayRector.php:150]: I talked with @TomasVotruba about this, and more and more we used PHPStan method from Type, it just cause more bugs, so we decide to use instanceof if the variable of call is used next, that's allow for improvement for more types later, rather than cause crash because of method not exists in target PHPStan type.

Comment (staabm) [reply rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNewArrayRector.php:150]: Yeah, as soon as you use methods which are not part of the Type interface you hurt PHPStan guarantees.

It would be great if we could get rid of calls to methods which only exist on certain types

Comment (staabm) [reply rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNewArrayRector.php:150]: see https://github.com/rectorphp/rector-src/pull/6478
