### PR TITLE
[Php70] Handle reverse sorting check on IfToSpaceshipRector

### LINKED ISSUE #6938: `IfToSpaceshipRector` doesn't refactor reverse sorting
# Bug Report

`IfToSpaceshipRector` correctly refactors a sorting method when the test result is `1 : -1` but it does not refactor a test when the result is `-1 : 1`. This should be possible by reversing the order of the comparison during refactoring.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec752c4-31d3-6968-a239-c97530bbb5fa

```php
<?php

class HelloWorld {

	private static function _rsort( $a, $b ) {
		if ( $a['foo'] === $b['foo'] ) {
			return 0;
		} else {
			return ( $a['foo'] > $b['foo'] ) ? -1 : 1;
		}
	}

	private static function _sort( $a, $b ) {
		if ( $a['foo'] === $b['foo'] ) {
			return 0;
		} else {
			return ( $a['foo'] > $b['foo'] ) ? 1 : -1;
		}
	}

}
```

### Responsible rules

* `IfToSpaceshipRector`

## Expected Behavior

I would expect the `_sort()` method to be refactored to the following (note the swapped order of `$a` and `$b`):

```php
return $b['foo'] <=> $a['foo'];
```

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #1674 
Fixes https://github.com/rectorphp/rector/issues/6938

### CODE REVIEW

File: rules-tests/Php70/Rector/If_/IfToSpaceshipRector/Fixture/skip.php.inc [hunk 1]
```diff
@@ -30,14 +30,6 @@ class Skip
             return ($a[0] <= $b[0]) ? 1 : -1;
         });
 
-        usort($languages, function ($a, $b) {
-            if ($a[0] === $b[0]) {
-                return 0;
-            }
-
-            return ($a[0] < $b[0]) ? -1 : 1;
-        });
```
Comment (samsonasik) [inline rules-tests/Php70/Rector/If_/IfToSpaceshipRector/Fixture/skip.php.inc:39]: I removed above skip as it seems applied now:

```diff
-            if ($a[0] === $b[0]) {
-                return 0;
-            }
-
-            return ($a[0] < $b[0]) ? -1 : 1;
+            return $a[0] <=> $b[0];
         });
```

moved to new fixture https://github.com/rectorphp/rector-src/pull/1676/commits/d0e7b445507849607c50b42206a87ad4cf1cb18e

ref https://3v4l.org/6jaK6 and https://3v4l.org/ReF9k for check equal result.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Thank you 😌
