### PR TITLE
[TypeDeclaration] skip variadic constructor param of mixed type on AddParamTypeFromPropertyTypeRector

### LINKED ISSUE #8168: Incorrect behavior of AddParamTypeFromPropertyTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e8b2a468-764d-4031-9dc3-4f5bf587aefd

```php
<?php

final class DemoFile
{
    private array $elements;

    public function __construct(...$elements)
    {
        $this->elements = $elements;
    }
}
```

### Responsible rules

* `AddParamTypeFromPropertyTypeRector`

## Expected Behavior

Rector adds `array` as typehint which is not correct for splat/unpack operator. 

```php
-    public function __construct(...$elements)
+    public function __construct(array ...$elements)
```

It _would_ mean that each incoming item is an array. But it's not necessarily. It can be any type which is stored _inside_ of an array.

If the type would be `Foo` instead of `array`, Rector would not change anything (which is correct):

```php
final class DemoFile
{
    protected Foo $elements;

    public function __construct(...$elements)
    {
        $this->elements = $elements;
    }
}
```

### PR DESCRIPTION
**Pull request by Celebrate-Reinhard**
Fixes https://github.com/rectorphp/rector/issues/8168

### CODE REVIEW

File: rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/skip_variadic_constructor_param_of_mixed_type.php.inc [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+     */
+    private array $elements;
+
+    public function __construct(...$elements)
+    {
+        $this->elements = $elements;
+    }
+}
+
+?>
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/skip_variadic_constructor_param_of_mixed_type.php.inc]: if 2nd part is equal, that can be deleted:

```suggestion
```

File: rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/variadic_constructor_param_of_explicit_type.php [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+     * @var DateTime[]
+     */
+    private array $dates;
+
+    public function __construct(...$dates) {
+        $this->dates = $dates;
+    }
+}
+
+?>
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/variadic_constructor_param_of_explicit_type.php]: if 2nd part is equal, that can be deleted:

```suggestion
```

File: rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/variadic_constructor_param_of_explicit_type.php [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddParamTypeFromPropertyTypeRector\Fixture;
+
+final class SkipVariadicConstructorParamOfExplicitType
+{
+    /**
+     * @var DateTime[]
+     */
+    private array $dates;
+
+    public function __construct(...$dates) {
```
Comment (Celebrate-Reinhard) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/variadic_constructor_param_of_explicit_type.php]: @samsonasik 

Instead of 

`public function __construct(...$dates) {`

`public function __construct(DateTime ...$dates) {`

would be nice. But I couldn't find a way how to read from the dock block comment. 

Any idea?

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector/Fixture/variadic_constructor_param_of_explicit_type.php]: we can't rely on docblock, so skipping is the safest.

File: rules/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector.php [hunk 4]
```diff
@@ -93,7 +93,9 @@ public function refactor(Node $node): ?ClassMethod
             if ($param->type instanceof Node) {
                 continue;
             }
-
+            if ($param->variadic) {
+                continue;
+            }
             if (! $this->paramTypeAddGuard->isLegal($param, $node)) {
```
Comment (samsonasik) [inline rules/TypeDeclaration/Rector/ClassMethod/AddParamTypeFromPropertyTypeRector.php:99]: Looks good 👍 , we can move the variadic check to `$this->paramTypeAddGuard->isLegal()` method if we have another use case in other rule

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @Celebrate-Reinhard
