### PR TITLE
[Parallel] Handle Spaced root project main script on parallel process

### LINKED ISSUE #8005: Cannot process files
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.1          |

Tried to run the `./vendor/bin/rector process ` and got **fatal errors file /media/mac/New does not exist. Could not process some files, due to:                                                                          
         "Child process error: ".** 

I am using Ubuntu 22

### PR DESCRIPTION
**Pull request by samsonasik**
@paulbalandan @sh1hab this is test for https://github.com/rectorphp/rector/issues/8005

I copied existing test so I probablly missing the expecation assertion as currently shows:

```
'/usr/bin/php8.1' 'C:\Users\P\Desktop\Web Dev\vendor\bin\rector' 'packages-tests/Parallel/Command/WorkerCommandLineFactoryTest.php' worker --port 2000 --identifier 'identifier' 'src' --output-format 'json' --no-ansi
.'/usr/bin/php8.1' 'C:\Users\P\Desktop\Web Dev\vendor\bin\rector' 'packages-tests/Parallel/Command/WorkerCommandLineFactoryTest.php' worker --port 2000 --identifier 'identifier' 'src' --output-format 'json' --no-ansi
.'/usr/bin/php8.1' 'C:\Users\P\Desktop\Web Dev\vendor\bin\rector' 'packages-tests/Parallel/Command/WorkerCommandLineFactoryTest.php' worker --debug --port 2000 --identifier 'identifier' 'src' --output-format 'json' --no-ansi
```

Fixes https://github.com/rectorphp/rector/issues/8005

### CODE REVIEW

**Comment by samsonasik** [comment]
Step to reproduce error locally:

1. download https://github.com/rectorphp/rector/files/12210766/spaced.prj.sample.zip
2. extract, then

```
cd spaced\ prj\ sample/
cd target

➜  target git:(main) vendor/bin/rector      
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%{"fatal_errors":["Cannot load resource \"/Users/samsonasik/www/spaced\"."]}
                                                                                                                        
 [ERROR] Could not process some files, due to:                                                                          
         "Child process error: ".                                                                                       ```

**Comment by samsonasik** [comment]
@paulbalandan it seems double quoted is needed for generated main script:

```
➜  rector-src git:(spaced-main-script) mkdir foo\ bar
➜  rector-src git:(spaced-main-script) cd "foo bar"
➜  foo bar git:(spaced-main-script)
```

File: packages/Parallel/Command/WorkerCommandLineFactory.php [hunk 1]
```diff
@@ -61,6 +61,11 @@ public function create(
                 break;
             }
 
+            if ($arg === $mainScript) {
+                $workerCommandArray[] = '"' . $arg . '"';
+                continue;
+            }
```
Comment (samsonasik) [inline packages/Parallel/Command/WorkerCommandLineFactory.php]: @paulbalandan I tried still, still doesn't work

```
➜  spaced prj sample git:(main) ✗ cd target
➜  target git:(main) ✗ ls
composer.json  composer.lock  rector.php  src  vendor
➜  target git:(main) ✗ vendor/bin/rector 
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%{"fatal_errors":["The file \"/home/abdul/Downloads/spaced\" does not exist."]}
                                                                                
 [ERROR] Could not process some files, due to:                                  
         "Child process error: ".                                               
```

Feel free to provide a patch if you found the solution first :)

**Comment by paulbalandan** [comment]
> @paulbalandan it seems double quoted is needed for generated main script:
> 
> ```
> ➜  rector-src git:(spaced-main-script) mkdir foo\ bar
> ➜  rector-src git:(spaced-main-script) cd "foo bar"
> ➜  foo bar git:(spaced-main-script)
> ```

Yes, single quotes won't work

File: packages/Parallel/Command/WorkerCommandLineFactory.php (hunk 1 above)
Comment (paulbalandan) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: What is the drawback of using relative path for main script? Can you give example?

Comment (samsonasik) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: Using relative path will not work for global  usage, see example e2e on rector/rector scoped vendor

https://github.com/rectorphp/rector/blob/ca844057bcb6c096d4380a4a1624914a90b7de4b/.github/workflows/e2e_global.yaml#L39

**Comment by samsonasik** [comment]
@paulbalandan On linux, single quote can go to target dir:

```
➜  ~ mkdir foo\ bar
➜  ~ cd 'foo bar'
➜  foo bar 
```

so the issue is somewhere on extracting space ...

File: packages/Parallel/Command/WorkerCommandLineFactory.php (hunk 1 above)
Comment (samsonasik) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: Also, using relative path make impossible to know the current path that going to be scanned since the parallel is different process

**Comment by samsonasik** [comment]
For side note: this issue is also happen even on Linux and macOs

File: packages/Parallel/Command/WorkerCommandLineFactory.php (hunk 1 above)
Comment (staabm) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: I wonder wheter we need escapeshellcmd on the mainscript instead of escapeshellarg?

https://3v4l.org/XJILI

Comment (samsonasik) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: @staabm I tried that, not working

Comment (samsonasik) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: the root path before project path is probably the one that need `escapeshellcmd()`, I will retry tomorrow

**Comment by samsonasik** [comment]
The issue seems deep on https://github.com/reactphp/child-process, when I replace:

```
/Users/samsonasik/www/spaced prj sample/target/rector.php
```

on https://github.com/rectorphp/rector-src/blob/23840739198816814b463df4a9510bb8f4f5fbda/packages/Parallel/Command/WorkerCommandLineFactory.php#L96-L113

into:

```
/Users/samsonasik/www/spaced\ prj\ sample/target/rector.php
```

it processed as:

```diff
-/Users/samsonasik/www/spaced\ prj\ sample/target/rector.php
+/Users/samsonasik/www/spaced\\ prj\\ sample/target/rector.php

```

**Comment by staabm** [comment]
maybe open a new issue in the component to discuss it?

**Comment by samsonasik** [comment]
The issue seems on `--config '/path/to/rector.php' that the "root" project contains space usage, if that can be trimmed to only relative path, it probably should can be resolved, trying with manually:

```diff
-$workerCommandArray[] = \escapeshellarg((string) $input->getOption(Option::CONFIG));
+$workerCommandArray[] = 'rector.php';
```

solve the issue, so the condition should be:

- is the config root project is equal with project root? If yes, use relative path
- otherwise, back to real path

**Comment by samsonasik** [comment]
@staabm @paulbalandan I tried manually using this change seems solve the issue:

```php
            $config = (string) $input->getOption(Option::CONFIG);
            $filePathHelper = new \Rector\Core\FileSystem\FilePathHelper(new \RectorPrefix202307\Symfony\Component\Filesystem\Filesystem());

            $workerCommandArray[] = escapeshellarg($filePathHelper->relativePath(realpath($config)));
```

I will push a commit.

**Comment by samsonasik** [comment]
@paulbalandan @staabm  @sh1hab it should be working ok now, I will merge it and let you test 5 minutes after it merged:

- 3 minutes on downgrade
- 1-2 minutes to get updated to packagist

to test this, update with the following command:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main
```

**Comment by paulbalandan** [comment]
@samsonasik 

```console
$ composer info -D
codeigniter/coding-standard     v1.7.8           Official Coding Standards for CodeIgniter based on PHP CS Fixer
codeigniter/phpstan-codeigniter v1.1.3.70400     CodeIgniter extensions and rules for PHPStan
ergebnis/composer-normalize     2.36.0           Provides a composer plugin for normalizing composer.json.
fakerphp/faker                  v1.23.0          Faker is a PHP library that generates fake data for you.
kint-php/kint                   5.0.7            Kint - debugging tool for PHP developers
laminas/laminas-escaper         2.12.0           Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
mikey179/vfsstream              v1.6.11          Virtual file system to mock the real file system in unit tests.
nexusphp/cs-config              v3.15.0          A factory for custom rulesets for PHP CS Fixer.
nexusphp/tachycardia            v1.4.0           Detects slow running tests in your PHPUnit-driven test suites.
php-coveralls/php-coveralls     v2.6.0           PHP client library for Coveralls API
phpstan/extension-installer     1.3.1            Composer plugin for automatic installation of PHPStan extensions
phpstan/phpstan                 1.10.34          PHPStan - PHP Static Analysis Tool
phpstan/phpstan-strict-rules    1.5.1            Extra strict and opinionated rules for PHPStan
phpunit/phpcov                  8.2.1            CLI frontend for php-code-coverage
phpunit/phpunit                 9.6.12           The PHP Unit Testing framework.
predis/predis                   v2.2.2           A flexible and feature-complete Redis client for PHP.
psr/log                         1.1.4            Common interface for logging libraries
rector/rector                   dev-main 5f78db9 Instant Upgrade and Automated Refactoring of any PHP code
vimeo/psalm                     5.15.0           A static analysis tool for finding errors in PHP applications
```

```console
$ vendor/bin/rector process system
Could not open input file: C:\Users\P\Desktop\Web
```

**Comment by samsonasik** [comment]
@paulbalandan hm.., that's strange, I can't reproduce on macOS:

```diff
➜  target git:(main) ✗ pwd
/Users/samsonasik/www/spaced prj sample/target

➜  target git:(main) ✗ vendor/bin/rector process --clear-cache --dry-run
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) src/Foo.php:0

    ---------- begin diff ----------
@@ @@
 <?php 

-final class Foo
+final readonly class Foo
 {
-  private readonly int $bar = 1;
+  private int $bar = 1;
 }
    ----------- end diff -----------

Applied rules:
 * ReadOnlyClassRector (https://wiki.php.net/rfc/readonly_classes)


                                                                                                                        
 [OK] 1 file would have changed (dry-run) by Rector                                                                     
                                                                                                                        
```

**Comment by samsonasik** [comment]
@paulbalandan could you probably check if there is something missing on 

https://github.com/rectorphp/rector-src/blob/d188b67d8620ffba4c2488cdaab20853ba804f14/packages/Parallel/Command/WorkerCommandLineFactory.php#L114-L115

it probably some tweak on escapeshellarg vs escapeshellcmd on windows env.

thank you.

**Comment by samsonasik** [comment]
@paulbalandan is changing to `escapeshellcmd` this working?

```diff
-$workerCommandArray[] = \escapeshellarg($this->filePathHelper->relativePath($config));
+$workerCommandArray[] = \escapeshellcmd($this->filePathHelper->relativePath($config));
```

or probably you can check what's wrong there on windows OS :)

**Comment by paulbalandan** [comment]
`escapeshellcmd` does not work either. Does rector prevent xdebug breakpoints?

**Comment by staabm** [comment]
> `escapeshellcmd` does not work either. Does rector prevent xdebug breakpoints?

yes, you need to pass `--xdebug`

**Comment by staabm** [comment]
>     * is the config root project is equal with project root? If yes, use relative path
> 
>     * otherwise, back to real path

this still is just a workaround. I think report a problem to the upstream component is the way to solve the underlying problem, or at least get better feedback on how to fix it on our end

**Comment by samsonasik** [comment]
@staabm sure, I created issue for that:

- https://github.com/reactphp/child-process/issues/104

**Comment by samsonasik** [comment]
@staabm sure, I created issue for that:

- https://github.com/reactphp/child-process/issues/104

**Comment by paulbalandan** [comment]
Okay, some weird changes.

1. I used relative path for `$mainScript`
```diff
/**
     * @param class-string<Command> $mainCommandClass
     */
    public function create(string $mainScript, string $mainCommandClass, string $workerCommandName, InputInterface $input, string $identifier, int $port) : string
    {
+       $mainScript = $this->filePathHelper->relativePath($mainScript);
        $commandArguments = \array_slice($_SERVER['argv'], 1);
        $args = \array_merge([\PHP_BINARY, $mainScript], $commandArguments);
```

2. Run `vendor/bin/rector process system` (Cache cleared)
```console
$ vendor/bin/rector process system --clear-cache
Could not open input file: C:\Users\P\Desktop\Web
```

3. Run `vendor/bin/rector process system --xdebug` (Cache cleared) with **no set breakpoints**
```console
$ vendor/bin/rector process system --xdebug --clear-cache
 437/437 [============================] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                                   
                                                                                                                        

```

**Comment by samsonasik** [comment]
@paulbalandan interesting, you may need to debug in here:

https://github.com/rectorphp/rector-src/blob/d188b67d8620ffba4c2488cdaab20853ba804f14/src/Console/ConsoleApplication.php#L45-L50

**Comment by samsonasik** [comment]
@paulbalandan I am testing on macOS, seems working ok:

```
# here spaced root project 

➜  CodeIgniter4 git:(develop) ✗ pwd
/Users/samsonasik/www/new spaced/CodeIgniter4

➜  CodeIgniter4 git:(develop) ✗ vendor/bin/rector process system 
 437/437 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] Rector is done!                                                                                                                                                                                                                           
```

I don't have windows env so I will check on linux next.

**Comment by samsonasik** [comment]
@paulbalandan I am testing on linux, seems working ok:

```
# here spaced root project 

➜  CodeIgniter4 git:(develop) ✗ pwd
/home/abdul/www/new spaced/CodeIgniter4


➜  CodeIgniter4 git:(develop) ✗ vendor/bin/rector process system 
 437/437 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                
 [OK] Rector is done!                                                           
  ```

**Comment by paulbalandan** [comment]
@samsonasik I have isolated the issue to be from the terminal used.

Your fix seems to be correct. However, the terminal used will be the problem for Windows.
- cmd => ok
- pwsh (Powershell 7) - nope
- bash on windows - ok

However, I am not sure why this is the case 🤷

**Comment by samsonasik** [comment]
@paulbalandan thank you 👍 , well, at least working on other terminal (cmd, bash on windows), I think we can add note as known drawbacks on README.md for running paralle under pwsh (Powershell 7):

https://github.com/rectorphp/rector-src/blob/main/build/target-repository/README.md#known-drawbacks

could you write a PR for it? Thank you :)

**Comment by paulbalandan** [comment]
@samsonasik see https://github.com/rectorphp/rector-src/pull/5022
