### PR TITLE
 [CodeQuality] Skip Generator on SimplifyForeachToCoalescingRector 

### LINKED ISSUE #8774: incorrect rule SimplifyForeachToCoalescingRector with generators
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.2             |

The `SimplifyForeachToCoalescingRector` rule incorrectly replaces foreach with an inline expression because the generator does not support array access

## Minimal PHP Code Causing Issue

https://getrector.com/demo/099bd3d9-a3b4-4796-8219-08e808f22c62

## Expected Behaviour

if source method in `foreach` is generator, need skip this rule

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8774

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @pilot114

File: rules/CodeQuality/Rector/Foreach_/SimplifyForeachToCoalescingRector.php [hunk 1]
```diff
@@ -169,6 +170,11 @@ private function matchForeachReturnOrAssign(Foreach_ $foreach): Expression|Retur
             return null;
         }
 
+        $foreachExprType = $this->nodeTypeResolver->getNativeType($foreach->expr);
+        if (! $foreachExprType->isArray()->yes()) {
+            return null;
+        }
```
Comment (samsonasik) [inline rules/CodeQuality/Rector/Foreach_/SimplifyForeachToCoalescingRector.php:175]: this ensure it only change native array type, as change other type can be any type, eg: `Generator` or object extends `stdClass`, see https://3v4l.org/6i6kj

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)
