### PR TITLE
[Php80][CodeQuality] Handle crash on ChangeSwitchToMatchRector + TernaryFalseExpressionToIfRector on under if else

### LINKED ISSUE #8393: Incorrect behavior of ChangeSwitchToMatchRector, TernaryFalseExpressionToIfRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/db2e7515-e2a2-42f3-9935-4497066b40f0

```php
<?php

$random = rand(1, 3);

if(rand(0, 1)) {
	// this if makes it crash
} else {
	switch($random) {
		case 1:
			$out = 'one';
		break;
		case 2:
			$out = 'two';
		break;
		default:
			$out = 'other';
	}
}
```

### Responsible rules

* `ChangeSwitchToMatchRector`
* `TernaryFalseExpressionToIfRector`

## Expected Behavior

Rector crashes with this code structure if both `ChangeSwitchToMatchRector` and `TernaryFalseExpressionToIfRector` are enabled. It shouldn't crash.

Unfortunately I am not sure how to create a fixture that would be used while both rules are active.

[debug.log](https://github.com/rectorphp/rector/files/13860676/debug.log)

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8393
Ref https://getrector.com/demo/db2e7515-e2a2-42f3-9935-4497066b40f0

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @noother

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

File: src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php [hunk 1]
```diff
@@ -126,6 +127,12 @@ public function processNodes(
                 return;
             }
 
+            if ($node instanceof StmtsAwareInterface && $node->stmts !== null) {
+                foreach ($node->stmts as $stmt) {
+                    $stmt->setAttribute(AttributeKey::SCOPE, $mutatingScope);
```
Comment (samsonasik) [inline src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:132]: Using `$this->nodeScopeResolver->processNodes($node->stmts, $mutatingScope, $nodeCallback);` may probably better for reliable enter scope.

I will check if that may cause some performance hit.

Comment (samsonasik) [reply src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:132]: Testing manually with multi stmts, the scope seems linear, so it seems ok (for now), note to myself: it may need to revisit.

Comment (samsonasik) [reply src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:132]: https://github.com/rectorphp/rector-src/pull/5450
