### PR TITLE
[DeadCode] Fix array callable with constructor args

### LINKED ISSUE #8574: Incorrect behavior of RemoveUnusedPrivateMethodRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/81e4f9cb-57f5-4240-9fb9-73256732da21

```php
<?php

final class SkipArrayCallablesSelfWithConstructor
{
    private array $args;

    public function __construct(...$args)
    {
        $this->args = $args;
    }

    public function run(): array
    {
        $array  = [3, 2, 1];

        usort($array, [self::class, 'sort']);

        return $array;
    }

    private function sort($a, $b)
    {
        return $a <=> $b;
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

Rectorphp should skip it.

## In Addition
* If `$this` is used instead of `self::class` in the above code, it will be skipped as intended. [link](https://getrector.com/demo/ec6a244e-9958-4c74-bf54-95244b939a26)
* If a default argument is specified for `__construct` in the above code, even `self::class` will be skipped as intended. [link](https://getrector.com/demo/e280f8cf-975b-4132-93f3-0d81fc468b37)

### PR DESCRIPTION
**Pull request by hogejiro**
Fix https://github.com/rectorphp/rector/issues/8574

### CODE REVIEW

File: src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php [hunk 1]
```diff
@@ -59,7 +62,7 @@ public function match(Array_ $array, Scope $scope): null | ArrayCallableDynamicM
         // $this, self, static, FQN
         $firstItemValue = $items[0]->value;
 
-        $callerType = $this->resolveCallerType($firstItemValue, $scope);
+        $callerType = $this->resolveCallerType($firstItemValue, $scope, $classMethodName);
```
Comment (samsonasik) [inline src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php:65]: I am on mobile, looks like method name should can be pulled from ` $items[1]->value->value` directly if `$items[1]->value` is a `String_` node

File: rules/DeadCode/NodeAnalyzer/IsClassMethodUsedAnalyzer.php [hunk 2]
```diff
@@ -112,13 +112,14 @@ private function isClassMethodCalledInLocalArrayCall(Class_ $class, ClassMethod
...
         $arrays = $this->betterNodeFinder->findInstanceOf($class, Array_::class);
+        $classMethodName = $this->nodeNameResolver->getName($classMethod);
 
         foreach ($arrays as $array) {
             if ($this->isInArrayMap($class, $array)) {
                 return true;
             }
 
-            $arrayCallable = $this->arrayCallableMethodMatcher->match($array, $scope);
+            $arrayCallable = $this->arrayCallableMethodMatcher->match($array, $scope, $classMethodName);
```
Comment (hogejiro) [inline rules/DeadCode/NodeAnalyzer/IsClassMethodUsedAnalyzer.php:122]: (note)
If it use `$secondItemValue` instead of `$classMethodName`, then cause regression below.

```
There were 2 failures:

1) Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\CallableThisArrayToAnonymousFunctionRectorTest::test with data set #20 ('...')
Failed on fixture file "skip_other_class_has_construct_parameter.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function run()
     {
-        return [OtherClass::class, 'someMethod'];
+        return function () {
+            return (new \Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\Source\OtherClass())->someMethod();
+        };
     }
 }
 ?>

2) Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\CallableThisArrayToAnonymousFunctionRectorTest::test with data set #21 ('...')
Failed on fixture file "skip_same_class_has_construct_parameter.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@

 public function run()
 {
- return [SkipSameClassHasConstructParameter::class, 'someMethod'];
+ return function () {
+ return (new \Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\Fixture\SkipSameClassHasConstructParameter())->someMethod();
+ };
 }

 public function someMethod()
```

File: src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php (hunk 1 above)
Comment (hogejiro) [reply src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php:65]: Thank you for your reply. I tried but PHPUnit failed. (https://github.com/rectorphp/rector-src/pull/5770#discussion_r1536821064)

Comment (samsonasik) [reply src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php:65]: I see, it seems due to current class method vs in 2nd arg is different 👍

File: src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php [hunk 3]
```diff
@@ -162,6 +168,10 @@ private function resolveClassConstFetchType(ClassConstFetch $classConstFetch, Sc
             return new ObjectType($classConstantReference, null, $classReflection);
         }
 
+        if (is_string($classMethodName) && $classReflection->hasMethod($classMethodName)) {
```
Comment (samsonasik) [inline src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php]: Could you use `hasNativeMethod()`? ensure to not rely on `@method` definition fallback when possible

Comment (hogejiro) [reply src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php]: Thank you. Fixed.

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Let's give it a try, thank you @hogejiro
