### PR TITLE
[PHP81] Skip after is_string on object call on NullToStrictStringFuncCallArgRector

### LINKED ISSUE #8468: Incorrect behavior of `NullToStrictStringFuncCallArgRector`
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.19.8      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/78c7508a-f3eb-4b7e-a148-cdc8f9acf41e

```php
<?php

final class DemoFile
{
    public ?string $stringNull = 'foo';
}

$demo = new DemoFile();

if (is_string($demo->stringNull)
    && trim($demo->stringNull) !== ''
   ) {
    echo $demo->stringNull;
}
```

### Responsible rules

* `NullToStrictStringFuncCallArgRector`

## Expected Behavior

No Change

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8468

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @OskarStark

File: rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/skip_after_is_string_on_object_call.php.inc [hunk 1]
```diff
@@ -0,0 +1,14 @@
+<?php
+
+namespace Rector\Tests\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector\Fixture;
+
+final class SkipAfterIsStringOnObjectCall
+{
+    public ?string $stringNull = 'foo';
```
Comment (OskarStark) [inline rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/skip_after_is_string_on_object_call.php.inc:7]: does this also work with a method instead of a property?

Comment (samsonasik) [reply rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/skip_after_is_string_on_object_call.php.inc:7]: should be work if native type defined, the `NullToStrictStringFuncCallArgRector` is to work with safe change, 

- with `@param string`, it means already string, to avoid too many change,
- with native type, it means already string as well.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it;)

File: rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/skip_after_is_string_on_object_call.php.inc (hunk 1 above)
Comment (staabm) [reply rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/skip_after_is_string_on_object_call.php.inc:7]: @OskarStark you can try on https://getrector.com/demo whether you find another case :)

shortly after a PR is merged the demo is updated

Comment (OskarStark) [reply rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/skip_after_is_string_on_object_call.php.inc:7]: Thanks for the info
