### PR TITLE
[Kaizen] Save kaizen applied rules into cache to make works on parallel

### LINKED ISSUE #9231: `--kaizen` not working when using `withParallel()`
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.1.0            |

When using `--kaizen=1` with `->withoutParallel()`, it works as expected. And I love it!
But with `->withParallel()` more than one rule is applied (but only one rule per file).

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/7045#issuecomment-3041299146

Closes https://github.com/rectorphp/rector-src/pull/7045
Closes Closes https://github.com/rectorphp/rector/issues/9231

### CODE REVIEW

**Comment by samsonasik** [comment]
I've added e2e test for it with `maxNumberOfProcess: 2, jobSize: 1` on 4 files for it https://github.com/rectorphp/rector-src/pull/7046/commits/b53b595ca63264b62e0cd3a3b1dff1ee6237af45 with kaizen 1, it seems cause error on CI (applied 2 rules), while working on locally.

Ref https://github.com/rectorphp/rector-src/actions/runs/16101183170/job/45430530419?pr=7046

It can possibly due to on CI, the cache overlapped call

**Comment by samsonasik** [comment]
I got it, it seems due to default CI use `MemoryCacheStorage`, I updated to use `FileCacheStorage` on e2e config and it seems working ok now 👍 https://github.com/rectorphp/rector-src/actions/runs/16101393029/job/45431005381?pr=7046

**Comment by samsonasik** [comment]
All checks have passed 🎉 @gharlan @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba let's merge to have faster feedback to test ;)

File: src/Caching/Detector/KaizenRulesDetector.php [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+    {
+        $this->cache->clean(CacheKey::KAIZEN_RULES);
+    }
+
+    public function addRule(string $rectorClass): void
+    {
+        $cachedValue = $this->loadRules();
+
+        $appliedRectorClasses = array_unique(array_merge($cachedValue, [$rectorClass]));
+        $this->cache->save($this->getCacheKey(), CacheKey::KAIZEN_RULES, $appliedRectorClasses);
```
Comment (TomasVotruba) [inline src/Caching/Detector/KaizenRulesDetector.php:37]: Nice trick :clap: :partying_face:

**Comment by gharlan** [comment]
Thanks! I tried it in my project (via rector/rector dev-main, which is already updated: https://github.com/rectorphp/rector/commit/c243796b35fa46cb68ca08b4386931e1e1c3b05f).

The first run of `rector process --kaizen=1` now works correctly 👍  Only one rule is applied. In my case that rule changed 16 files of 747.


```
$ rector process --kaizen=1
[EXPERIMENTAL] Running Kaizen mode. Only first 1 rule will be applied

 747/747 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%16 files with change

[...]

 [OK] 16 files have been changed by Rector
``` 

But the next run only "looks" at the 16 changed files:

```
$ rector process --kaizen=1
[EXPERIMENTAL] Running Kaizen mode. Only first 1 rule will be applied

 16/16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [OK] Rector is done!
```

**Comment by samsonasik** [comment]
@gharlan thank you for verify, that's expected, or we may need to force clear cache when `--kaizen` used.

The combination with `--clear-cache` is needed for now, and we can discuss about whether cache need to be cleared when `kaizen` is used. 

Please create new feature request for that so this can be discussed further.

**Comment by samsonasik** [comment]
nvm, I created PR for that :)

- https://github.com/rectorphp/rector-src/pull/7050
