### PR TITLE
[CodeQuality][Strict] Handle infinite loop on SimplifyDeMorganBinaryRector+SimplifyIfReturnBoolRector+DisallowedEmptyRuleFixerRector

### LINKED ISSUE #8094: rector endless loop/segfault
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v. 017.7            |

Rector got stuck (macos 13.4.1) or segfaults (docker php-cli 8.1 image)

## Minimal PHP Code Causing Issue

https://getrector.com/demo/a286068e-5b27-436c-92a3-e6df24d2cc71

## Expected Behaviour

no segfault

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8094
Ref https://getrector.com/demo/1a837c54-bbbc-4885-8a16-cac8caf7fdc1

### CODE REVIEW

File: tests/Issues/SimplifyEmpty/Fixture/fixture.php.inc [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    }
+
+    public function getString2(): ?string
+    {
+        return $this->string2;
+    }
+
+    public function check(): bool
+    {
+        return !($this->getString() === null || $this->getString() === '' || (($this->getString2() === null || $this->getString2() === '') && !is_numeric($this->getString2())));
```
Comment (samsonasik) [inline tests/Issues/SimplifyEmpty/Fixture/fixture.php.inc:57]: the transformation still invalid with skip re-print handling

https://3v4l.org/UHLOP

Comment (samsonasik) [reply tests/Issues/SimplifyEmpty/Fixture/fixture.php.inc:57]: I missread it, the open close parentheses is on the right, seems still invalid https://3v4l.org/ZT7Gm or I just missread it.

I think the rule for `SimplifyDeMorganBinaryRector` actually need to be skipped for this case as it is very hard to read, even correct transform.

Comment (samsonasik) [reply tests/Issues/SimplifyEmpty/Fixture/fixture.php.inc:57]: oh, I see, the transformation is correct, it just hard to read as it direct return after false vs true negated.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)
