### PR TITLE
[DeadCode] Skip with different default param value child vs parent on RemoveParentDelegatingConstructorRector

### LINKED ISSUE #9571: Incorrect behavior of RemoveParentDelegatingConstructorRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/46ca86bb-337a-4bad-81af-40d1ab7929c8

```php
<?php
class InternalServerException
{
    private Throwable $stack = [];
    public function __construct(string $message = 'Server error', int $code = 500, ?Throwable $previous = null)
    {
        echo 'Error thrown : ' . $message . ' (' . $code . ')';
	if (!is_null($previous)) {
            $this->stack[] = $previous;
        }
    }
}

class BlogException extends InternalServerException
{
    public function __construct(string $message = 'Blog handling error', int $code = 570, ?Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
}
```

### Responsible rules

* `RemoveParentDelegatingConstructorRector`

## Expected Behavior

As the child constructor provide default parameters' values (which may be different than parent's ones) if necessary, I think that the child constructor is still relevant.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/9571

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @franck-paul

**Comment by samsonasik** [comment]
@TomasVotruba ready 👍

**Comment by franck-paul** [comment]
Nice, it's Christmas before Christmas \o/

File: rules/DeadCode/Rector/ClassMethod/RemoveParentDelegatingConstructorRector.php [hunk 1]
```diff
@@ -230,6 +235,29 @@ private function areConstructorAndParentParameterTypesMatching(
...
+                        continue;
+                    }
+
+                    $parentDefault = $nativeParentParameterReflection->getDefaultValue();
+                    $currentDefault = $this->valueResolver->getValue($param->default);
+
+                    if ($parentDefault !== $currentDefault) {
+                        return false;
+                    }
+                }
```
Comment (TomasVotruba) [inline rules/DeadCode/Rector/ClassMethod/RemoveParentDelegatingConstructorRector.php]: Looks good 👍 

Could you extract method here to make code more readable?

Comment (samsonasik) [reply rules/DeadCode/Rector/ClassMethod/RemoveParentDelegatingConstructorRector.php]: sure, extracted logic to different method 👍 https://github.com/rectorphp/rector-src/pull/7776/changes/fded30994c63566267acef4b8e18ff8f0302d217

**Comment by samsonasik** [comment]
@TomasVotruba ready 👍

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:
