### PR TITLE
fix: Skip remove always true condition on method calls

### LINKED ISSUE #8700: RemoveAlwaysTrueIfConditionRector removes conditions when comparing method call and constant
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | last dev-main             |

## Minimal PHP Code Causing Issue
See https://getrector.com/demo/2b19a5fb-5e83-4b97-9968-a7cda22b54f3

```
<?php

namespace Rector\Tests\DeadCode\Rector\If_\RemoveAlwaysTrueIfConditionRector\Fixture;

class ApiException extends \Exception
{
    public function __construct(
        string $message,
        ?string $code = null,
        ?\Throwable $previous = null
    ) {
        parent::__construct($message, 0, $previous);

        $this->code = $code;
    }
}

class SkipMethodCall {
    private const WEBSITE_ALREADY_EXISTS = 'website_already_exists';

    public function run()
    {
        try {
            return $this->someApiAction();
        } catch (ApiException $ex) {
            if ($ex->getCode() !== self::WEBSITE_ALREADY_EXISTS) {
                throw $ex;
            }
        }
    }

    private function someApiAction()
    {
        if (rand() % 2) {
            throw new ApiException('API Action failed', 'website_already_exists');
        }

        return 1;
    }
}
```
## Expected Behaviour
Rector should not remove the condition as we cannot know what method call will return

### PR DESCRIPTION
**Pull request by nikolicaleksa**
Fixes https://github.com/rectorphp/rector/issues/8700

### CODE REVIEW

File: rules/DeadCode/Rector/If_/RemoveAlwaysTrueIfConditionRector.php [hunk 1]
```diff
@@ -143,7 +145,13 @@ private function shouldSkipExpr(Expr $expr): bool
     {
         return (bool) $this->betterNodeFinder->findInstancesOf(
             $expr,
-            [PropertyFetch::class, StaticPropertyFetch::class, ArrayDimFetch::class]
+            [
+                PropertyFetch::class,
+                StaticPropertyFetch::class,
+                ArrayDimFetch::class,
+                MethodCall::class,
+                StaticMethodCallableNode::class,
```
Comment (samsonasik) [inline rules/DeadCode/Rector/If_/RemoveAlwaysTrueIfConditionRector.php]: `StaticMethodCallableNode` seems phpstan node, rector rule should only check native phpparser node

**Comment by TomasVotruba** [comment]
Thank you 👍
