### PR TITLE
Fix php 7.4 regression on strtolower to false on ClassLikeNameClassNameImportSkipVoter

### LINKED ISSUE #9405: System error: "strtolower() expects parameter 1 to be string, bool given
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.2.0            |
| PHP Version | 7.4.33 |

When running rector on a file, I will get the error:
```
[ERROR] Could not process "/path/to/file.php" file, due to:                                                                               11:51:04 [93/4883]
         "System error: "strtolower() expects parameter 1 to be string, bool given"

         Stack trace:
         #0
         tools/rector/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php(48): strtolower()
         #1 tools/rector/vendor/rector/rector/rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php(39):
         Rector\CodingStyle\ClassNameImport\ClassNameImportSkipVoter\ClassLikeNameClassNameImportSkipVoter->shouldSkip(
         )
         #2 tools/rector/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(94):
         Rector\CodingStyle\ClassNameImport\ClassNameImportSkipper->shouldSkipNameForFullyQualifiedObjectType()
         #3 tools/rector/vendor/rector/rector/rules/CodingStyle/Node/NameImporter.php(55):
         Rector\CodingStyle\Node\NameImporter->importNameAndCollectNewUseStatement()
         #4 tools/rector/vendor/rector/rector/src/PostRector/Rector/NameImportingPostRector.php(52):
         Rector\CodingStyle\Node\NameImporter->importName()
```
NOTE: The above has been trimmed 

## Minimal PHP Code Causing Issue

Not able to reproduce the issue there. I did notice that when `getClassName` and `getShortName` are the same, this is where it will have a fatal error. Not sure how it gets those, but I can tell you that the name giving me issues is `Exception`.

## Expected Behaviour

Not crash ;p

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/9405
Ref https://github.com/rectorphp/rector-src/pull/7235#issuecomment-3372456206

### CODE REVIEW

File: rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php [hunk 1]
```diff
@@ -47,7 +47,7 @@ public function shouldSkip(File $file, FullyQualifiedObjectType $fullyQualifiedO
 
         $shortNameLowered = $fullyQualifiedObjectType->getShortNameLowered();
         $fullyQualifiedObjectTypeNamespace = strtolower(
-            substr($fullyQualifiedObjectType->getClassName(), 0, -strlen($fullyQualifiedObjectType->getShortName()) - 1)
+            substr($fullyQualifiedObjectType->getClassName(), 0, -strlen($fullyQualifiedObjectType->getShortName()) - 1) ?: ''
```
Comment (TomasVotruba) [inline rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: Can you add a note about PHP 7.4? So we don't accidentally remove it :)

Comment (TomasVotruba) [inline rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: Might be also good candidate for a downgrade rule

Comment (samsonasik) [reply rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: sure, I created new PR to add note for it

- https://github.com/rectorphp/rector-src/pull/7438

the `RecastingRemovalRector` needs also improvement for it, currently skipped

https://github.com/rectorphp/rector-src/blob/21b60910ad5526c24c3b812c7dec754e1be9ef52/rector.php#L57-L60

**Comment by samsonasik** [comment]
@TomasVotruba I need to create immediate release 2.2.1 for it :)

File: rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php (hunk 1 above)
Comment (clxmstaab) [reply rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: I wonder why this problem is not patched by PHPStan. is it reproducible on the phpstan playground, that we are missing a error here?

Comment (samsonasik) [reply rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: It seems on phpstan.org, it shows

on php 8.0+, show empy string
on php 7.2+, show false

see https://phpstan.org/r/6c0960c9-23d9-4387-8f95-f13f2f50f33b

Comment (clxmstaab) [reply rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: ohh I just see rector-src does not run PHPStan on PHP7.x.. you are only using [a single PHP 8.2 job](https://github.com/rectorphp/rector-src/blob/366f32951bcc0d882618cc2df4ead64c55b975c6/.github/workflows/code_analysis.yaml#L78) and therefore miss PHPStan errors on all other PHP versions

Comment (samsonasik) [reply rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php:50]: I created PR to skip remove `(string)` case on `substr()` on `RecastingRemovalRector` on `getNativeType()` method:

- https://github.com/rectorphp/rector-src/pull/7442
