### PR TITLE
Reduce ConstExprClassNameDecorator overhead

### LINKED ISSUE #8079: ConstExprClassNameDecorator is slow
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.6 (invoke `vendor/bin/rector --version`)             |

when running rector across the whole kunzmann codebase, I can see `ConstExprClassNameDecorator`'`-traverseWithCallable`-calls are slow

grafik

maybe we can find some shortcuts to make it faster

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/rectorphp/rector/issues/8079

15% faster

before 

```
$ time php vendor/bin/rector --dry-run --clear-cache
 1476/1476 [============================] 100%

 [OK] Rector is done!                                                                                                   

real    3m18.464s
user    0m0.000s
sys     0m0.000s

```

after

```
$ time php vendor/bin/rector --dry-run --clear-cache
 1476/1476 [============================] 100%
                                                                                                                        
 [OK] Rector is done!                                                                                                   

real    2m50.044s
user    0m0.015s
sys     0m0.000s
```

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @staabm

File: packages/BetterPhpDocParser/PhpDocParser/ConstExprClassNameDecorator.php [hunk 1]
```diff
@@ -27,6 +27,11 @@ public function __construct(
 
     public function decorate(PhpDocNode $phpDocNode, PhpNode $phpNode): void
     {
+        // iterating all phpdocs has big overhead. peek into the phpdoc to exit early
+        if (str_contains($phpDocNode->__toString(), '::') === false) {
+            return;
+        }
```
Comment (TomasVotruba) [inline packages/BetterPhpDocParser/PhpDocParser/ConstExprClassNameDecorator.php:33]: Neat :+1:
