### PR TITLE
[Php80] Handle crash parent default empty array/string param on AddParamBasedOnParentClassMethodRector

### LINKED ISSUE #8149: Crash and Incorrect behavior of AddParamBasedOnParentClassMethodRector
# Bug Report

Rector crashes with PHPStan exception

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/e913f712-f893-4504-a26d-1e73c3892e0d

```php
<?php

class Foo{
    public function baz($default = []) {
        return implode('', $default);
    }
    
    public function boo($default = '') {
        return $default;
    }
}

class Bar extends Foo {
    public function baz() {
        echo parent::baz();
    }
    
    public function boo() {
        echo parent::boo();
    }
}
```

### Responsible rules

* `AddParamBasedOnParentClassMethodRector`

## Expected Behavior
It should not crash and should produce the following diff:
```diff
@@ -11,11 +11,11 @@
 }
 
 class Bar extends Foo {
-    public function baz() {
+    public function baz($default = []) {
         echo parent::baz();
     }
     
-    public function boo() {
+    public function boo($default = '') {
         echo parent::boo();
     }
 }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://getrector.com/demo/e913f712-f893-4504-a26d-1e73c3892e0d
Fixes https://github.com/rectorphp/rector/issues/8149

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @klimslim

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

File: rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php [hunk 1]
```diff
@@ -239,6 +240,21 @@ function (Node $subNode) use ($parentClassMethodParam): bool {
...
     }
 
+    private function resolveParamDefault(Expr $expr): Expr
+    {
+        // re-create to avoid TokenStream error
+        if ($expr instanceof Array_) {
+            return new Array_($expr->items);
+        }
+
+        if ($expr instanceof String_) {
```
Comment (staabm) [inline rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: I wonder, when we need a special case for string here, do we also need one for int/float?

or would the string case also be handled by the BetterStandardPrinter?

https://getrector.com/demo/6bf890b2-8642-421a-bda6-e9b6914af37b

Comment (samsonasik) [reply rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: I updated to ensure printed first https://github.com/rectorphp/rector-src/pull/4833/commits/620db90fb0c57eae4190862553345829cd0ae3f1

Identifier can't be empty `''` or `[]`

Comment (staabm) [reply rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: in case we don't have a test for the int/float case and it crashes as can be seen for the above link, we should add a test-case

Comment (samsonasik) [reply rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: Oh, I see, I will add test for it.

Comment (samsonasik) [reply rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: I added failing tset case for default int https://github.com/rectorphp/rector-src/pull/4833/commits/94389713244396c00c374ee8c12981fa8df0d9de

Comment (samsonasik) [reply rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: Fixed :) https://github.com/rectorphp/rector-src/pull/4833/commits/525442f088545e243430a9e85fae1760d83b90a2

**Comment by samsonasik** [comment]
@staabm the `int`/`float` handling already covered https://github.com/rectorphp/rector-src/pull/4833/commits/525442f088545e243430a9e85fae1760d83b90a2

File: rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php (hunk 1 above)
Comment (staabm) [reply rules/Php80/Rector/ClassMethod/AddParamBasedOnParentClassMethodRector.php]: Thanks

**Review by TomasVotruba — APPROVED** [review]
Go for merge when ready :+1:
