### PR TITLE
ExplicitReturnNullRector: skip on goto

### LINKED ISSUE #9224: Skip ExplicitReturnNullRector on code which contains `goto`
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

writing a simple "retry"-function is most efficiently done [using `goto`](https://github.com/igorw/retry/issues/3#issuecomment-56448334) - even though most people hate it.

rector adds a `return null` at the bottom of the function, which is dead code in this regard.
I think `ExplicitReturnNullRector` should stop trying to add return statements, when a single `goto` is met in the function/method scope it currently works on

## Minimal PHP Code Causing Issue

https://getrector.com/demo/2f66102f-2dcd-4468-a142-794ec56ae9e6

## Expected Behaviour

no return added

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/rectorphp/rector/issues/9224

### CODE REVIEW

File: rules/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector.php [hunk 1]
```diff
@@ -112,9 +112,14 @@ public function refactor(Node $node): ?Node
...
         $hasChanged = false;
+        $containsGoto = false;
         $this->traverseNodesWithCallable((array) $node->stmts, static function (Node $node) use (
-            &$hasChanged
+            &$hasChanged, &$containsGoto
         ): int|null|Return_ {
+            if ($node instanceof Node\Stmt\Goto_) {
+                $containsGoto = true;
+                return NodeVisitor::DONT_TRAVERSE_CURRENT_AND_CHILDREN;
+            }
```
Comment (samsonasik) [inline rules/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector.php]: this may cause overlapped on next direct change, just use simple `$this->betterNodeFinder->findInstancesOfScoped()` early before traverse change.

```php
$hasGoto = (bool) $this->betterNodeFinder->findInstancesOfScoped($node, Goto_::class);

if ($hasGoto) {
    return null;
}
```

File: rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc [hunk 2]
```diff
@@ -17,28 +17,3 @@ final class DoWhileMaybeReturned4
...
-
-			return 2;
-		} while (++$i < 1);
-		execute:
-			echo 'test';
-            return null;
-    }
-}
-
-?>
```
Comment (staabm) [inline rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: hopefully its fine to skip this case, as I think it is not very useful

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: add `return null` after `echo 'test'` is valid here, so probably verify if it has label.

It also probably more verifiable via `TerminatedNodeAnalyzer` service

https://github.com/rectorphp/rector-src/blob/341fbe7020e075e807e2debb45b6c5b9cfafaa51/src/NodeAnalyzer/TerminatedNodeAnalyzer.php#L48

Comment (staabm) [reply rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: I agree it is technically allowed, but I think its not valuable to complicate the rector for goto cases.

I would just leave code with goto alone as it might have suprising logic

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: I will check if that can be covered via `TerminatedNodeAnalyzer` service :), otherwise, I can just merge it later if that too complex to cover

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: I created PR with utilize `TerminatedNodeAnalyzer` at:

- https://github.com/rectorphp/rector-src/pull/6990

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: After some try, it indeed to complicated to tweak, I can merge this for now :)

**Comment by samsonasik** [comment]
Thank you @staabm

**Comment by staabm** [comment]
Thx

File: rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc (hunk 2 above)
Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/ClassMethod/ExplicitReturnNullRector/Fixture/do_while_maybe_returned4.php.inc:44]: @staabm I created properly new PR to handle this:

- https://github.com/rectorphp/rector-src/pull/7018

which check on SilentVoidResolver instead.
