### PR TITLE
StaticMapper: added fast path for IdentifierTypeNode

### LINKED ISSUE #8077: NameImportingPostRector is slow
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.6            |

when `$rectorConfig->importNames();` is enabled running rector across the otherwise identical codebase is 42% slower.

grafik

grafik

is it a known problem that `$rectorConfig->importNames()` is such a performance hit?

do we actually need `$rectorConfig->importNames()` in our projects when we run ECS right after we ran rector?

## Minimal PHP Code Causing Issue

my rector command on the [kunzmann private repo](https://github.com/complex-gmbh/kunzmann/pull/4453):

`blackfire run php vendor/bin/rector process app/admin --ansi --clear-cache` 

config
```
$rectorConfig->importNames();
$rectorConfig->disableParallel();
```

## Expected Behaviour

fast CI :)

### PR DESCRIPTION
**Pull request by staabm**
the idea behind this method is: 

- we see in https://github.com/rectorphp/rector/issues/8077#issuecomment-1645081188 that name scope creation is slow
- IdentifierTypeMapper does not need the name-scope for its inner workings -> lets try a separate fast path in case we know the `$typeNode=IdentifierTypeNode` so we can skip name scope creation

----

Result: 1 minute faster rector runs ; additionally we are saving 11% on memory usage
 
grafik

closes https://github.com/rectorphp/rector/issues/8077

### CODE REVIEW

File: packages/StaticTypeMapper/StaticTypeMapper.php [hunk 1]
```diff
@@ -112,4 +115,9 @@ public function mapPHPStanPhpDocTypeNodeToPHPStanType(TypeNode $typeNode, Node $
         $nameScope = $this->nameScopeFactory->createNameScopeFromNode($node);
         return $this->phpDocTypeMapper->mapToPHPStanType($typeNode, $node, $nameScope);
     }
+
+    public function mapIdentifierTypeNodeToPHPStanType(IdentifierTypeNode $typeNode, Node $node): Type
```
Comment (staabm) [inline packages/StaticTypeMapper/StaticTypeMapper.php:119]: the idea behind this method is: 

- we see in https://github.com/rectorphp/rector/issues/8077#issuecomment-1645081188 that name scope creation is slow
- IdentifierTypeMapper does not need the name-scope for its inner workings -> lets try a separate fast path in case we know the `TypeNode` so we can skip name scope creation

**Comment by staabm** [comment]
I guess the test-suite segfaults because of a infinite loop. I couldn't identify yet why this happens. I can also see it locally but wanted to verify in CI whether the problem also happens

**Comment by staabm** [comment]
updated the initial description with our results. with this change rector runs 23% faster in our use-case which means saving 1 minute on a 4 minute job

additionally we are saving 11% on memory usage

**Comment by staabm** [comment]
I think we are good to go

**Review by samsonasik — APPROVED** [review]

File: packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php [hunk 2]
```diff
@@ -53,6 +53,11 @@ public function getNodeType(): string
      * @param IdentifierTypeNode $typeNode
      */
     public function mapToPHPStanType(TypeNode $typeNode, Node $node, NameScope $nameScope): Type
+    {
+        return $this->mapIdentifierTypeNode($typeNode, $node);
+    }
+
+    public function mapIdentifierTypeNode(IdentifierTypeNode $typeNode, Node $node): Type
```
Comment (samsonasik) [inline packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php:60]: I think new `mapIdentifierTypeNode()` method can be reverted, use back `mapToPHPStanType()` seems ok

Comment (samsonasik) [reply packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php:60]: Oh, I see, you don't want `NameScope` to be involved here, so it seems ok then 👍

**Comment by samsonasik** [comment]
Let's give it a try, thank you @staabm
