### PR TITLE
fix: skip variable assignments in get_defined_vars

### LINKED ISSUE #9298: Incorrect behavior of RemoveUnusedVariableAssignRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d41fab65-6532-483d-a019-b82beac55caa

```php
<?php

final class DemoFile
{
    public function example(): array
    {
        $value = 42;
        return get_defined_vars();
    }
}
```

### Responsible rules

* `RemoveUnusedVariableAssignRector`

## Expected Behavior

Variable should not be removed because of the `get_defined_vars()`

### PR DESCRIPTION
**Pull request by calebdw**
Closes https://github.com/rectorphp/rector/issues/9298

Thanks!

### CODE REVIEW

File: rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php [hunk 1]
```diff
@@ -154,7 +154,7 @@ private function shouldSkip(array $stmts): bool
                 return false;
             }
 
-            return $this->isName($node, 'compact');
+            return $this->isName($node, 'compact') || $this->isName($node, 'get_defined_vars');
```
Comment (samsonasik) [inline rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: use `isNames()`:

```suggestion
            return $this->isNames($node, ['compact', 'get_defined_vars']);
```

**Comment by samsonasik** [comment]
Thank you @calebdw

File: rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php (hunk 1 above)
Comment (calebdw) [reply rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: Ah, good to know!

File: rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_get_defined_vars.php.inc [hunk 2]
```diff
@@ -0,0 +1,14 @@
+<?php
+
+namespace Rector\Tests\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector\Fixture;
+
+class SkipInCompact
```
Comment (samsonasik) [inline rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_get_defined_vars.php.inc:5]: oh, fixture class need to be renamed:

```suggestion
class SkipInGetDefinedVars
```

Comment (samsonasik) [reply rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_get_defined_vars.php.inc:5]: https://github.com/rectorphp/rector-src/pull/7107

Comment (calebdw) [reply rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_get_defined_vars.php.inc:5]: would be nice if this was checked in ci

Comment (samsonasik) [reply rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_get_defined_vars.php.inc:5]: That was exists, but removed as become maintenance burden due to many "on purpose" usage to be skipped iirc, manual verification is fine :)

**Comment by TomasVotruba** [comment]
:+1:
