### PR TITLE
[CodingStyle] Skip Method target not found or defined only via @method on FunctionLikeToFirstClassCallableRector

### LINKED ISSUE #9460: FunctionLikeToFirstClassCallableRector incompatible with reflection-based parameter resolution
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version |  2.2.5      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/245339d1-1138-434b-a7a4-8ca8c320ebc4

```php
<?php

function value($value, ...$args)
{
    return $value instanceof Closure ? $value(...$args) : $value;
}

trait EvaluatesClosures
{
    protected string $evaluationIdentifier;

    /**
     * @template T
     *
     * @param T|callable(): T $value
     * @param array<string, mixed> $namedInjections
     * @return T
     */
    public function evaluate(mixed $value, array $namedInjections = []): mixed
    {
        if (! $value instanceof Closure) {
            return $value;
        }

        $dependencies = [];

        foreach ((new ReflectionFunction($value))->getParameters() as $parameter) {
            $dependencies[] = $this->resolveClosureDependencyForEvaluation($parameter, $namedInjections);
        }

        return $value(...$dependencies);
    }

    /**
     * @param array<string, mixed> $namedInjections
     */
    protected function resolveClosureDependencyForEvaluation(ReflectionParameter $parameter, array $namedInjections): mixed
    {
        $parameterName = $parameter->getName();

        if (array_key_exists($parameterName, $namedInjections)) {
            return value($namedInjections[$parameterName]);
        }

        if ($parameter->isDefaultValueAvailable()) {
            return $parameter->getDefaultValue();
        }

        if ($parameter->isOptional() || $parameter->allowsNull()) {
            return null;
        }

        $staticClass = static::class;

        throw new Exception("An attempt was made to evaluate a closure for [{$staticClass}], but [\${$parameterName}] was unresolvable.");
    }
}
/**
 * @method static array name(mixed $name)
 */
class A
{
    public static function __callStatic($name, $arguments)
    {
        return [$name, $arguments];
    }
}

/**
 * @method static array test(mixed $value)
 */
class Foo
{
    use EvaluatesClosures;

    public static function __callStatic($name, $arguments)
    {
        return [$name, $arguments];
    }

    public function callTest(Closure $callback)
    {
        $test = array_map(fn($value) => Foo::test($value), [1, 2, 3, 4]);
        return $this->evaluate($callback, ['test' => $test, 'name' => 'name value']);
    }
}

$class = new Foo();
echo json_encode($class->callTest(fn($name) => A::name($name)));
```

### Responsible rules

* `FunctionLikeToFirstClassCallableRector`

* `NewMethodCallWithoutParenthesesRector`

* `KnownMagicClassMethodTypeRector`

* `ReturnTypeFromStrictTypedCallRector`

* `AddArrayFunctionClosureParamTypeRector`

## Expected Behavior

In this context, Rector should not use the First-Class Callable syntax, as it will cause the application to fail to execute correctly.

```diff
 $class = new Foo();
-echo json_encode($class->callTest(fn($name) => A::name($name)));
+echo json_encode($class->callTest(A::name(...)));
```

Before processing output:
`["name", ["name value"]]`

After processing output:
`["name", [null]]`

Additionally, PHPStan reports the following errors:

```error
::error file=test.php,line=83,col=0::Creating callable from a non-native static method Foo::test().
::error file=test.php,line=89,col=0::Creating callable from a non-native static method A::name().
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/9460

When target method not found or found but only via `@method`, it can be magic based method, and not safe, so this PR skip it.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @zishang520

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

File: rules/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector.php [hunk 1]
```diff
@@ -185,6 +186,18 @@ private function shouldSkip(
...
+
+        // not exists, probably by magic method
+        if ($reflection === null) {
+            return true;
+        }
+
+        // exists, but by @method annotation
+        if ($reflection instanceof AnnotationMethodReflection) {
+            return true;
+        }
```
Comment (TomasVotruba) [inline rules/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector.php:199]: 👍
