### PR TITLE
Fix/early return inline constructor default 7319

### LINKED ISSUE #7319: Incorrect behavior of InlineConstructorDefaultToPropertyRector: do not inline conditional values
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.9      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/a2abb0f1-85f0-437a-9ab0-d6d240928307

```php
<?php

final class A
{
    public bool $foo = false;

    /** @param string[] $tags */
    public function __construct(
        private readonly DateTimeImmutable|null $to = null
    ) {
        if ($this->to === null) {
            return;
        }

        $this->foo = true;
    }
}
```

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

Do not touch the property since the value is set conditionally (not in every path).

### PR DESCRIPTION
**Pull request by kpn13**
This PR should fix https://github.com/rectorphp/rector/issues/7319 by searching a "return stmt" if a "if stmt" is found.

### CODE REVIEW

File: rules/CodeQuality/NodeAnalyzer/ConstructorPropertyDefaultExprResolver.php [hunk 1]
```diff
@@ -33,6 +35,10 @@ public function resolve(ClassMethod $classMethod): array
         $defaultPropertyExprAssigns = [];
 
         foreach ($stmts as $stmt) {
+            if ($stmt instanceof If_ && $this->hasReturnStmt($stmt)) {
+                break;
```
Comment (samsonasik) [inline rules/CodeQuality/NodeAnalyzer/ConstructorPropertyDefaultExprResolver.php]: I think better to use "break;" when $stmt is not Expression, so handle in next code to use break; instead of continue.

File: rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_early_return.php.inc [hunk 2]
```diff
@@ -0,0 +1,47 @@
+<?php
+
+namespace Rector\Tests\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector\Fixture;
+
+final class SkipEarlyReturn
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_early_return.php.inc]: as partial changed, please rename class name along with file name to something like "DonotChangeHasBeforeIf" -> "do_not_change_has_before_if.php.inc"

File: rules/CodeQuality/NodeAnalyzer/ConstructorPropertyDefaultExprResolver.php (hunk 1 above)
Comment (kpn13) [reply rules/CodeQuality/NodeAnalyzer/ConstructorPropertyDefaultExprResolver.php]: OK, simplier than i thought, thx.

File: rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_early_return.php.inc (hunk 2 above)
Comment (kpn13) [reply rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_early_return.php.inc]: Done

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you @kpn13
