### PR TITLE
Fix platform version resolution, use require first

### LINKED ISSUE #8455: Could not resolve PHP level set list for "80199"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.19.6           |

When using Rector with the default config and the option `->withPhpSets()` to let Rector figure out the PHP version on its own, I get this error:
>[ERROR] Could not resolve PHP level set list for "80199"

```
        "platform": {
            "php": "8.1.99"
        }
```

This is because in composer.json I have 

I would expect Rector to pick PHP 8.1 set.

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes https://github.com/rectorphp/rector/issues/8455

### CODE REVIEW

File: src/Php/PhpVersionResolver/ProjectComposerJsonPhpVersionResolver.php [hunk 1]
```diff
@@ -28,21 +28,21 @@ public static function resolve(string $composerJson): ?int
...
 
-        $requirePhpVersion = $projectComposerJson['require']['php'] ?? null;
-        if ($requirePhpVersion === null) {
-            return self::$cachedPhpVersions[$composerJson] = null;
-        }
-
-        self::$cachedPhpVersions[$composerJson] = self::createIntVersionFromComposerVersion($requirePhpVersion);
-
-        return self::$cachedPhpVersions[$composerJson];
+        return null;
```
Comment (samsonasik) [inline src/Php/PhpVersionResolver/ProjectComposerJsonPhpVersionResolver.php:45]: null result still need to be cached:

```suggestion
        return self::$cachedPhpVersions[$composerJson] = null;
```

I will create new PR for it.

Comment (TomasVotruba) [reply src/Php/PhpVersionResolver/ProjectComposerJsonPhpVersionResolver.php:45]: Thanks

Comment (samsonasik) [reply src/Php/PhpVersionResolver/ProjectComposerJsonPhpVersionResolver.php:45]: https://github.com/rectorphp/rector-src/pull/5559
