### PR TITLE
fix: EnumCaseToPascalCaseRector skips existing pascal case

### LINKED ISSUE #9374: Incorrect behavior of EnumCaseToPascalCaseRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/53ea352a-9226-4472-9b52-d4a1de9bacf7

```php
<?php

enum TrackingSummaryStatus
{
    case OrderReceived;
    case InProcess;
    case PreparingToShip;
}
```

### Responsible rules

* `EnumCaseToPascalCaseRector`

## Expected Behavior

There should not be any changes

### PR DESCRIPTION
**Pull request by calebdw**
Closes https://github.com/rectorphp/rector/issues/9374

Thanks!

### CODE REVIEW

File: rules/CodingStyle/Rector/Enum_/EnumCaseToPascalCaseRector.php [hunk 1]
```diff
@@ -187,7 +187,28 @@ private function refactorClassConstFetch(ClassConstFetch $classConstFetch): ?Nod
 
     private function convertToPascalCase(string $name): string
     {
+        if ($this->isPascalCase($name)) {
```
Comment (samsonasik) [inline rules/CodingStyle/Rector/Enum_/EnumCaseToPascalCaseRector.php]: use existing `convertToPascalCase()` method, compare, if same, then skip

Comment (calebdw) [reply rules/CodingStyle/Rector/Enum_/EnumCaseToPascalCaseRector.php]: That's not going to work here, the `convertToPascalCase()` method is not idempotent

Comment (samsonasik) [reply rules/CodingStyle/Rector/Enum_/EnumCaseToPascalCaseRector.php]: that strange that the check already there

https://github.com/rectorphp/rector-src/blob/87d442710e116b0141ed8961a3f1b56311785534/rules/CodingStyle/Rector/Enum_/EnumCaseToPascalCaseRector.php#L104-L107

I am on mobile, I will check when I am back to PC

Comment (samsonasik) [reply rules/CodingStyle/Rector/Enum_/EnumCaseToPascalCaseRector.php]: I've updated to use existing `convertToPascalCase` method https://github.com/rectorphp/rector-src/pull/7264/commits/2a86213b3828dab9b9e99caa4097750931d928c4

**Comment by samsonasik** [comment]
@calebdw this should be ok now :)

**Comment by samsonasik** [comment]
Thank you @calebdw
