### PR TITLE
Fix no return in ChangeSwitchToMatchRector

### LINKED ISSUE #7621: Incorrect behavior of ChangeSwitchToMatchRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/b0968c60-f99e-4b57-9d41-2676a4b6c423

```php
<?php

final class DemoFile
{
    public function run(): string
    {
        $url = '';
        switch ($foo) {
            case 1:
                $url .= '1';
                break;
            case 2:
                $url .= '2';
                break;
        }

		return $url;
    }
}
```

Another example is
https://getrector.org/demo/f04068ec-1688-4b73-bd39-c736d3fb6e5a

### Responsible rules

* `ChangeSwitchToMatchRector`

## Expected Behavior

The method shouldn't loose the `return` values.

### PR DESCRIPTION
**Pull request by TomasVotruba**
* Closes https://github.com/rectorphp/rector-src/pull/3176
* Fixes https://github.com/rectorphp/rector/issues/7621

### CODE REVIEW

File: rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_unrelated_return.php.inc [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+namespace Rector\Tests\Php80\Rector\Switch_\ChangeSwitchToMatchRector\Fixture;
+
+final class UnrelatedReturn
+{
+    public function run($data, $proxyQuery, $alias): bool
+    {
+        match ($data->getValue()) {
+            ProductService::SPECIAL_GESTION_CAPSULE => $proxyQuery->getQueryBuilder()->andWhere($alias . '.collectionCapsule = true'),
+            ProductService::SPECIAL_GESTION_PRESTIGE => $proxyQuery->getQueryBuilder()->andWhere($alias . '.editionPrestige = true'),
+            default => true,
```
Comment (VincentLanglet) [inline rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_unrelated_return.php.inc:35]:
```suggestion
```
Wouldn't it be better without this line ? @TomasVotruba

Comment (TomasVotruba) [reply rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_unrelated_return.php.inc:35]: That would lead to crash, as match need always to find a value.

Comment (VincentLanglet) [reply rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_unrelated_return.php.inc:35]: Oh, good to know ^^'

File: rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_unrelated_return.php.inc [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+-----
+<?php
+
+namespace Rector\Tests\Php80\Rector\Switch_\ChangeSwitchToMatchRector\Fixture;
+
+final class UnrelatedReturn
+{
+    public function run($data, $proxyQuery, $alias): bool
+    {
+        match ($data->getValue()) {
```
Comment (staabm) [inline rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_unrelated_return.php.inc:32]: @samsonasik something is wrong with this test. either its not a skip-test (and the filename is wrong), or the expectations are wrong
