### PR TITLE
always make paths absolute before processing files

### LINKED ISSUE #4301: [BUG]: FilesystemInterface prefix (if file is selected instead of path)
### Minimal PHP Code Causing Issue

given:
file in `/app/src/extensions/aus_project/ext_tables.php` with content:
````php
<?php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('tx_ausproject_domain_model_slide,tx_ausproject_domain_model_teaser');
````

running `rector process --debug src/extensions/aus_project/ext_tables.php` in /app directory.

Producess:
````
[ERROR] Could not process "src/extensions/aus_project/ext_tables.php" file, due to:
         "System error: "Unable to create a directory at /src/extensions/aus_project/Configuration/TCA/Overrides.
         mkdir(): Permission denied"

         Stack trace:
         #0 vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php(297):
         League\Flysystem\UnableToCreateDirectory::atLocation('/src/extensions...', 'mkdir(): Permis...')
         #1 vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php(116):
         League\Flysystem\Local\LocalFilesystemAdapter->ensureDirectoryExists('/src/extensions...', 448)
         #2 vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php(102):
         League\Flysystem\Local\LocalFilesystemAdapter->writeToFile('src/extensions/...', '<?php\n\n// Inclu...',
         Object(League\Flysystem\Config))
         #3 vendor/league/flysystem/src/Filesystem.php(41):
         League\Flysystem\Local\LocalFilesystemAdapter->write('src/extensions/...', '<?php\n\n// Inclu...',
         Object(League\Flysystem\Config))
         #4 vendor/ssch/typo3-rector/src/Filesystem/FlysystemFilesystem.php(24):
         League\Flysystem\Filesystem->write('src/extensions/...', '<?php\n\n// Inclu...')
         #5
         vendor/ssch/typo3-rector/rules/CodeQuality/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesR
         ector.php(121): Ssch\TYPO3Rector\Filesystem\FlysystemFilesystem->write('src/extensions/...', '<?php\n\n//
         Inclu...')
         #6 vendor/rector/rector/src/Rector/AbstractRector.php(136):
         Ssch\TYPO3Rector\CodeQuality\General\MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector->refact
         or(Object(PhpParser\Node\Stmt\Expression))
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176):
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Expression))
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Closure))
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
````

this bug is only cased if the rector config as Paths specified directly to a PHP file.
eg through the cli: `rector process src/extension/test_extension/ext_tables.php`
or by a config line like this: in the `rector.php`
````php
$rectorConfig->paths(
    array_filter(explode("\n", (string)shell_exec("git ls-files | xargs ls -d 2>/dev/null | grep -E '\.(php)$'")))
);
````

### Applied rules

`MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector` but this should affect every Rector rule that writes files the same way.

### Expected Behaviour

But should try to create files in `/app/src/...`

### Package Version

<2.6.1 && > 2.6.4

### PHP Version

*

### TYPO3 Version

*

### Notes

Related Issues:
- initial fix attempt: #4277
- Issue with the fixed version: #4291
- "reverse of the fix": #4292 (discussion why the fix was there in the first place)

### PR DESCRIPTION
**Pull request by Kanti**
The path is currently only an absolute path if you call rector with a directory like this
`rector process pathToFile/`.
If you call it with a filename instead, the path will be relative. 
`rector process pathToFile/File.php`.
This makes implementing RectorRules with path usage more difficult than necessary.

fixes: https://github.com/sabbelasichon/typo3-rector/issues/4301

### CODE REVIEW

File: src/FileSystem/FilePathHelper.php [hunk 1]
```diff
@@ -45,6 +45,15 @@ public function relativePath(string $fileRealPath): string
         return $this->relativeFilePathFromDirectory($fileRealPath, getcwd());
     }
 
+    public function absolutePath(string $fileRealPath): string
+    {
+        if ($this->filesystem->isAbsolutePath($fileRealPath)) {
+            return $fileRealPath;
+        }
+
+        return getcwd() . '/' . $fileRealPath;
```
Comment (samsonasik) [inline src/FileSystem/FilePathHelper.php]: Just a quick look, `realpath()` should be used, directly use `getcwd()` may cause invalid path, for example, when using as standalone or global path

https://getrector.com/documentation/how-to-run-on-php-53

This must be tested carefully tho /cc @llaville

File: src/FileSystem/FilesFinder.php [hunk 2]
```diff
@@ -39,6 +39,7 @@ public function findInDirectoriesAndFiles(array $source, array $suffixes = [], b
 
         // filtering files in files collection
         $filteredFilePaths = $this->fileAndDirectoryFilter->filterFiles($filesAndDirectories);
+        $filteredFilePaths = array_map($this->filePathHelper->absolutePath(...), $filteredFilePaths);
```
Comment (samsonasik) [inline src/FileSystem/FilesFinder.php]: just use `realpath()` should be enough:

```php
        $filteredFilePaths = array_map(realpath(...), $filteredFilePaths);
```

also, place after last `$filteredFilePaths` after line 69 so less IO used

Comment (samsonasik) [reply src/FileSystem/FilesFinder.php]: Ok, using here seems fine, as on directory filter, the path is got realpath first before next PathSkipper usage

https://github.com/rectorphp/rector-src/blob/a4545b6fccbc6698fadce47a8454ce3acebf97ac/src/FileSystem/FilesFinder.php#L132-L149

Comment (samsonasik) [inline src/FileSystem/FilesFinder.php]: Just change to `realpath()` is enough:

```suggestion
        $filteredFilePaths = array_map(realpath(...), $filteredFilePaths);
```

File: src/FileSystem/FilePathHelper.php [hunk 3]
```diff
@@ -45,6 +45,15 @@ public function relativePath(string $fileRealPath): string
...
     }
 
+    public function absolutePath(string $fileRealPath): string
+    {
+        if ($this->filesystem->isAbsolutePath($fileRealPath)) {
+            return $fileRealPath;
+        }
+
+        return realpath($fileRealPath);
+    }
```
Comment (samsonasik) [inline src/FileSystem/FilePathHelper.php]: this is not needed, just use `realpath()` on per my suggestion on https://github.com/rectorphp/rector-src/pull/6293/files#r1749022916 is enough

File: src/FileSystem/FilePathHelper.php [hunk 4]
```diff
@@ -45,6 +45,15 @@ public function relativePath(string $fileRealPath): string
...
+
```
Comment (samsonasik) [inline src/FileSystem/FilePathHelper.php]:
```suggestion
```

**Comment by samsonasik** [comment]
Thank you @Kanti

**Comment by TomasVotruba** [comment]
Thanks 👍
