### PR TITLE
[CodeQuality] Skip with ascii on JoinStringConcatRector

### LINKED ISSUE #7667: Unexpected behavior with JoinStringConcatRector rule
# Bug Report

| Subject | Details |
| :--------| :--------|
| Rector  | v0.15.0  |
| PHP      | v8.1.0    |

## Minimal PHP Code Causing Issue
`rector --dry-run` in terminal of VS Code:
```php
protected function isGzipped(string $content): bool
     {
-        return mb_strpos($content, "\x1f" . "\x8b" . "\x08") === 0; // phpcs:ignore Generic.Strings.UnnecessaryStringConcat.Found
+        return mb_strpos($content, ') === 0; // phpcs:ignore Generic.Strings.UnnecessaryStringConcat.Found
     }
```
It is not entirely clear whether the Rector breaks the code, or whether these are output features in the terminal. The changes look unusable, so no action has been taken.

## Expected Behaviour
Multibyte characters must remain unchanged in the code and for display in the terminal.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7667

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @vralle

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

File: rules/CodeQuality/Rector/Concat/JoinStringConcatRector.php [hunk 1]
```diff
@@ -126,6 +126,10 @@ private function joinConcatIfStrings(Concat $node): Concat | String_
         }
 
         $resultString = new String_($leftValue . $rightValue);
+        if (! ctype_print($resultString->value)) {
```
Comment (samsonasik) [inline rules/CodeQuality/Rector/Concat/JoinStringConcatRector.php]: symfony/polyfill-ctype may need to be enabled for it 

https://github.com/rectorphp/rector-src/blob/6481ecdb4f118da8e42e1d7123fc21e6fac21a7f/composer.json#L72

Comment (samsonasik) [reply rules/CodeQuality/Rector/Concat/JoinStringConcatRector.php]: mb_* functions possibly can be used and available as prefixed vendor symfony/polyfill-mbstring

https://github.com/rectorphp/rector/tree/main/vendor/symfony/polyfill-mbstring

https://stackoverflow.com/questions/6497685/how-do-i-detect-non-ascii-characters-in-a-string

Comment (samsonasik) [reply rules/CodeQuality/Rector/Concat/JoinStringConcatRector.php]: it seems can be verified with ascii regex https://github.com/rectorphp/rector-src/pull/3497/commits/bda01fb3e16321e92bd764d40cb9559fec97676c

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)
