### PR TITLE
[DeadCode] Handle same namespace param type on RemoveUselessParamTagRector

### LINKED ISSUE #8732: DeadCode rule fail to remove some params
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.0            |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/b073cf8f-02c0-4874-9de7-708671d245c2

In the project, the `MyParameters` is in the same folder, hence no import used.
But it doesn't seem to be related to the lack of import though, here is a demo with an import and rector still dooesn't remove the `@param`
https://getrector.com/demo/5d195468-5383-40e0-ab10-d66f1266e98f

And here is a light config repro : https://getrector.com/demo/932a2e33-39a4-4e47-8d29-a00f9f38a6b8

## Expected Behaviour

The same with `Filesystem` the `@param` match the type-hint, so `@param MyParameters` should be removed
Recotr should have done that.
```diff
-    /**
-     * @param string $filename
-     * @param Filesystem $filesystem
-     * @param MyParameters $parameters
-     * @return bool
-     */
     public function export(string $filename, Filesystem $filesystem, MyParameters $parameters): bool;
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8732

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @etshy

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

File: rules/TypeDeclaration/PHPStan/ObjectTypeSpecifier.php [hunk 1]
```diff
@@ -55,6 +55,17 @@ public function narrowToFullyQualifiedOrAliasedObjectType(
...
+        // probably in same namespace
+        if ($scope instanceof Scope) {
+            $namespaceName = $scope->getNamespace();
+            if ($namespaceName !== null) {
+                $newClassName = $namespaceName . '\\' .$className;
+                if ($this->reflectionProvider->hasClass($newClassName)) {
+                    return new FullyQualifiedObjectType($newClassName);
+                }
+            }
+        }
```
Comment (TomasVotruba) [inline rules/TypeDeclaration/PHPStan/ObjectTypeSpecifier.php:67]: I was suspecting the redundant `use` import in the same namespace. Awesome :+1:
