### PR TITLE
[CodeQuality] Skip nullable mixed on ReturnTypeFromStrictScalarReturnExprRector

### LINKED ISSUE #7501: ReturnTypeFromStrictScalarReturnExprRector adds invalid return type ?mixed
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.0            |

When a function returns either `null` or `mixed`, the `ReturnTypeFromStrictScalarReturnExprRector` rule adds `?mixed`. This causes a fatal error:
```
Type mixed cannot be marked as nullable since mixed already includes null  
```

## Minimal PHP Code Causing Issue

[Reproduction](https://getrector.org/demo/6be915d3-bdd3-47f5-a6b4-9163739b063c)
```php
<?php

function returnsNullOrMixed()
{
    if (rand() < 0.5) {
        return null;
    }

    return json_decode('something', null, 512, JSON_THROW_ON_ERROR);
}
```

## Expected Behaviour

Should add `mixed` instead of `?mixed`.

### PR DESCRIPTION
**Pull request by thomasschiet**
Fixes https://github.com/rectorphp/rector/issues/7501.

I went with a slightly different approach than suggested by @samsonasik by mapping `?mixed` to `mixed` in `UnionTypeMapper`.

### CODE REVIEW

**Comment by samsonasik** [comment]
Please add test for under php 7.4 config which mixed is skipped, you can add test case class with own config for php 7.4 feature and fixture directory like in 

https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector

One more thing, you can solve phpstan notice with move some logic to separate private method so CI can green

**Comment by samsonasik** [comment]
After some thinking, this change is invalid, it should be skipped, as this `ReturnTypeFromStrictScalarReturnExprRector` is handle scalar return, while `mixed` can be anything

**Comment by thomasschiet** [comment]
I am not too familiar with Rector yet, but that sounds right. I adjusted the test to not add `mixed` as a return type. It seems to me like the problem is on the following line

https://github.com/rectorphp/rector-src/blob/main/rules/TypeDeclaration/TypeAnalyzer/AlwaysStrictScalarExprAnalyzer.php#L56

`resolveFuncCallType` just resolves the type, even if it's non-scalar. I added a check to see if the return type is scalar. I am not sure if this is the cleanest way of doing this, because I basically just copied code from a method in `UnionTypeAnalyzer`.

PS:
I find it a bit odd that Rector produces `?mixed`. Is it still a welcome change to absorb the null value in `?mixed` and map it to `mixed` in `UnionTypeMapper`?

File: rules-tests/CodeQuality/Rector/ClassMethod/ReturnTypeFromStrictScalarReturnExprRector/Fixture/nullable_mixed.php.inc [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+function y()
+{
+    if (rand() < 0.5) {
+        return null;
+    }
+
+    return json_decode('something', null, 512, JSON_THROW_ON_ERROR);
+}
+
+?>
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/ClassMethod/ReturnTypeFromStrictScalarReturnExprRector/Fixture/nullable_mixed.php.inc]: the second part can be removed as skipped.

```suggestion
```

File: rules-tests/CodeQuality/Rector/ClassMethod/ReturnTypeFromStrictScalarReturnExprRector/Fixture/nullable_mixed.php.inc [hunk 2]
```diff
@@ -0,0 +1,29 @@
+<?php
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/ClassMethod/ReturnTypeFromStrictScalarReturnExprRector/Fixture/nullable_mixed.php.inc]: please rename fixture name to something like `skip_nullable_mixed.php.inc`

File: packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php [hunk 3]
```diff
@@ -128,6 +128,11 @@ public function mapToPhpParserNode(Type $type, string $typeKind): ?Node
             return null;
         }
 
+        // null is already part of mixed
+        if ($nullabledType instanceof MixedType) {
+            return new Name('mixed');
```
Comment (samsonasik) [inline packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php]: this should re-assign so validation of Node result based on latest php feature can be re-checked on `$this->phpStanStaticTypeMapper->mapToPhpParserNode()` on next line:

```suggestion
            $nullableType = new MixedType();
```

**Comment by samsonasik** [comment]
You can move some of code to private method to make CI green:

```


 ------------------------------------------------------------------------
  packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php:99
 ------------------------------------------------------------------------
  - '#Cognitive complexity for "Rector\\PHPStanStaticTypeMapper\\TypeMapper\\UnionTypeMapper\:\:mapToPhpParserNode\(\)" is 11, keep it under 10#'
 ------------------------------------------------------------------------
```

**Comment by thomasschiet** [comment]
I noticed that the variables are called `$nullabledType` and `$nullabledTypeNode` instead of `$nullableType` and `$nullableTypeNode`, is that a typo?

File: packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php [hunk 4]
```diff
@@ -123,11 +123,21 @@ public function mapToPhpParserNode(Type $type, string $typeKind): ?Node
...
+    {
         // void cannot be nullable
         if ($nullabledType instanceof VoidType) {
             return null;
         }
 
+        // null is already part of mixed
+        if ($nullabledType instanceof MixedType) {
+            $nullabledType = new MixedType();
+        }
```
Comment (samsonasik) [inline packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php]:
```suggestion
        $nullabledType = $nullabledType instanceof MixedType
            ? new MixedType()
            : $nullabledType;
```

File: packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php [hunk 5]
```diff
@@ -123,11 +123,21 @@ public function mapToPhpParserNode(Type $type, string $typeKind): ?Node
             return $this->matchTypeForUnionedObjectTypes($type, $typeKind);
         }
 
+        return $this->mapNullabledType($nullabledType, $typeKind);
+    }
+
+    private function mapNullabledType(Type $nullabledType, string $typeKind): ?Node
```
Comment (samsonasik) [inline packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php:132]:
```suggestion
    /** 
     * @param TypeKind::* $typeKind
     */
    private function mapNullabledType(Type $nullabledType, string $typeKind): ?Node
```

File: rules/TypeDeclaration/TypeAnalyzer/AlwaysStrictScalarExprAnalyzer.php [hunk 6]
```diff
@@ -53,12 +54,43 @@ public function matchStrictScalarExpr(Expr $expr): ?Type
...
+
+        if ($type instanceof IntegerType) {
+            return true;
+        }
+
+        if ($type instanceof BooleanType) {
+            return true;
+        }
+
+        return false;
```
Comment (samsonasik) [inline rules/TypeDeclaration/TypeAnalyzer/AlwaysStrictScalarExprAnalyzer.php:91]:
```suggestion
        if (! $type instanceof Scalar) {
            return false;
        }

        return $this->resolveTypeFromScalar($type) instanceof Type;
```

**Comment by samsonasik** [comment]
That were typos, but I think CI need to be green first :), you can run phpstan locally for specific file with, eg:

```
composer phpstan -- packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php
```

File: packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php (hunk 4 above)
Comment (samsonasik) [inline packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php]: my original suggestion at https://github.com/rectorphp/rector/issues/7501#issuecomment-1254730274 is the correct way for it, if the type is `MixedType`, the tranfsormed parsed node can be `null` or `Name('mixed')` based on php version feature enabled.

so, this should be removed:

```suggestion
```

and add check : 

```diff
-        if (! $this->nodeNameResolver->isName($nullabledTypeNode, 'false')) {
+        if (! $this->nodeNameResolver->isNames($nullabledTypeNode, ['false', 'mixed'])) {
```

in line 151 before apply Nullable into parsed Node.

**Comment by samsonasik** [comment]
Please update PR title to something like:

```
[CodeQuality] Skip nullable mixed on ReturnTypeFromStrictScalarReturnExprRector

File: packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php (hunk 4 above)
Comment (thomasschiet) [reply packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php]: In that case I think we lose information in newer PHP versions that do support `mixed`, right? Something that could have been `mixed` will have no type instead. That is similar to how the `mapToPhpParserNode` method changes `true|false` to `bool`, since they are equivalent. Similarly, `null|mixed` is equivalent to `mixed`.

Comment (samsonasik) [reply packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php]: That's different possible feature to implement, that require failing test case to avoid regression apply `mixed` everywhere, this PR should solve only the issue related.

Comment (thomasschiet) [reply packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php]: Ok, clear. I will go with your original suggestion and finish up the PR. Thanks for the help!

File: rules/TypeDeclaration/TypeAnalyzer/AlwaysStrictScalarExprAnalyzer.php (hunk 6 above)
Comment (thomasschiet) [reply rules/TypeDeclaration/TypeAnalyzer/AlwaysStrictScalarExprAnalyzer.php:91]: This always returns false because the `$type` is `PHPStan\Type\Type` and that is never `PhpParser\Node\Scalar`.

Comment (samsonasik) [reply rules/TypeDeclaration/TypeAnalyzer/AlwaysStrictScalarExprAnalyzer.php:91]: Ok 👍

**Review by samsonasik — APPROVED** [review]

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you
