### PR TITLE
AddParamTypeBasedOnPHPUnitDataProviderRector: Check all data providers

### LINKED ISSUE #8221: Incorrect behavior of AddParamTypeBasedOnPHPUnitDataProviderRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/29a9e8cd-e456-4e85-a7dd-6ac069d875bd

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoTest extends TestCase {
    public function dataProvider1() {
        yield [1];
        yield [null];
    }

    public function dataProvider2() {
        yield ['foo'];
    }

    /**
     * @dataProvider dataProvider1
     * @dataProvider dataProvider2
     * @param int|string|null $value
     */
    public function testSomething($value): void {
    }
}
```

### Responsible rules

* `AddParamTypeBasedOnPHPUnitDataProviderRector`

## Expected Behavior

Do nothing or change to `int|string|null` depending on PHP version. Maybe the rule only looks at the first data provider.

### PR DESCRIPTION
**Pull request by jlherren**
Fixes rectorphp/rector#8221

### CODE REVIEW

File: packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php [hunk 1]
```diff
@@ -189,11 +189,6 @@ public function hasByName(string $name): bool
         return (bool) $this->getTagsByName($name);
     }
 
-    public function getByName(string $name): ?Node
```
Comment (samsonasik) [inline packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php:192]: I think you can mark this as `@api` so it can be keep as `getByName()` seems usefull to be kept

Comment (jlherren) [reply packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php:192]: Thanks!

**Comment by TomasVotruba** [comment]
Thank you :clap:
