### PR TITLE
[DeadCode] Skip Class Constant used in Enum on RemoveUnusedPrivateCla…

### LINKED ISSUE #7651: Incorrect behavior of RemoveUnusedPrivateClassConstantRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/2333a008-e4b0-4d11-9ade-3b37412193d2

```php
<?php

enum UtilizationType: string
{
    case Apartment = 'apartment';
    case Commerce = 'commerce';
    case Flat = 'flat';
    case Garage = 'garage';
    case Garden = 'garden';
    case Hospitality = 'hospitality';
    case House = 'house';
    case Investment = 'investment';
    case Office = 'office';
    case Retirement = 'retirement';
    case Warehouse = 'warehouse';

    private const BUSINESS_TYPES = [
        self::Commerce,
        self::Hospitality,
        self::Office,
        self::Warehouse,
    ];

    public function isBusiness(): bool
    {
        return in_array($this, self::BUSINESS_TYPES, true);
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateClassConstantRector`

## Expected Behavior

The private constant must not be removed as it's used in the `isBusiness()` method.

PR with failing test: rectorphp/rector-src#3174

### PR DESCRIPTION
**Pull request by eliashaeussler**
Based on https://getrector.org/demo/2333a008-e4b0-4d11-9ade-3b37412193d2

Fixes https://github.com/rectorphp/rector/issues/7651

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you try to provide a patch for it? It seems you can check on `ClassConstManipulator` by **remove** the following check:

https://github.com/rectorphp/rector-src/blob/863fee39147717a4f85c42eacaec28fe6971ac52/src/NodeManipulator/ClassConstManipulator.php#L28-L31

```diff
-        $class = $this->betterNodeFinder->findParentType($classConst, Class_::class);
-        if (! $class instanceof Class_) {
-            return false;
-        }
```

since it already check on next `$classReflection->getAncestors()` which fallback to return false in the end.

**Comment by eliashaeussler** [comment]
@samsonasik Thanks for the hint, I'm already on it and will provide a fix soon.

File: rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc [hunk 1]
```diff
@@ -0,0 +1,31 @@
+<?php
```
Comment (samsonasik) [inline rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc]: please rename file name to : `skip_class_constant_used_in_enum.php.inc`

File: rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+enum UtilizationType: string
```
Comment (samsonasik) [inline rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc]:
```suggestion
enum SkipClassConstantUsedInEnum: string
```

File: rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    ];
+
+    public function isBusiness(): bool
+    {
+        return in_array($this, self::BUSINESS_TYPES, true);
+    }
+}
+
+?>
+-----
```
Comment (samsonasik) [inline rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc]: this part can be removed:

```suggestion
```

File: rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc [hunk 4]
```diff
@@ -0,0 +1,31 @@
+<?php
+
```
Comment (samsonasik) [inline rules-tests/DeadCode/Rector/ClassConst/RemoveUnusedPrivateClassConstantRector/Fixture/demo_fixture.php.inc]: please add namespace here:

```suggestion
namespace Rector\Tests\DeadCode\Rector\ClassConst\RemoveUnusedPrivateClassConstantRector\Fixture;
```

**Comment by samsonasik** [comment]
After fix applied, please rename PR title to something like:

```
[DeadCode] Skip Class Constant used in Enum on RemoveUnusedPrivateClassConstantRector
```

File: src/NodeManipulator/ClassConstManipulator.php [hunk 5]
```diff
@@ -25,8 +26,8 @@ public function __construct(
 
     public function hasClassConstFetch(ClassConst $classConst, ClassReflection $classReflection): bool
     {
-        $class = $this->betterNodeFinder->findParentType($classConst, Class_::class);
-        if (! $class instanceof Class_) {
+        $class = $this->betterNodeFinder->findParentByTypes($classConst, [Class_::class, Enum_::class]);
+        if ($class === null) {
             return false;
         }
```
Comment (samsonasik) [inline src/NodeManipulator/ClassConstManipulator.php:32]: this check can just be removed, the `ClassReflection->getAncestors()` already check current class and parent class.

```suggestion
```

**Review by samsonasik — APPROVED** [review]

File: src/NodeManipulator/ClassConstManipulator.php [hunk 6]
```diff
@@ -25,8 +26,8 @@ public function __construct(
 
     public function hasClassConstFetch(ClassConst $classConst, ClassReflection $classReflection): bool
     {
-        $class = $this->betterNodeFinder->findParentType($classConst, Class_::class);
-        if (! $class instanceof Class_) {
+        $class = $this->betterNodeFinder->findParentByTypes($classConst, [Class_::class, Enum_::class]);
+        if ($class === null) {
```
Comment (samsonasik) [inline src/NodeManipulator/ClassConstManipulator.php]:
```suggestion
        if (! $class instanceof \PhpParser\Node\Stmt\ClassLike) {
```

File: src/NodeManipulator/ClassConstManipulator.php [hunk 7]
```diff
@@ -25,8 +26,8 @@ public function __construct(
...
             return false;
```
Comment (samsonasik) [inline src/NodeManipulator/ClassConstManipulator.php]: `return true` can be used since it can be trait, which consumeable by other class:

```suggestion
            return true;
```

Comment (samsonasik) [reply src/NodeManipulator/ClassConstManipulator.php]: see https://3v4l.org/pJo9C#v8.2.0 on php 8.2

File: src/NodeManipulator/ClassConstManipulator.php [hunk 8]
```diff
@@ -25,9 +26,9 @@ public function __construct(
 
     public function hasClassConstFetch(ClassConst $classConst, ClassReflection $classReflection): bool
     {
-        $class = $this->betterNodeFinder->findParentType($classConst, Class_::class);
-        if (! $class instanceof Class_) {
-            return false;
+        $class = $this->betterNodeFinder->findParentByTypes($classConst, [Class_::class, Enum_::class]);
+        if (! $class instanceof \PhpParser\Node\Stmt\ClassLike) {
```
Comment (samsonasik) [inline src/NodeManipulator/ClassConstManipulator.php]: `ClassLike` already in use statement, can just use as is:

```suggestion
        if (! $class instanceof ClassLike) {
```

**Review by samsonasik — APPROVED** [review]
Looks good 👍

**Comment by TomasVotruba** [comment]
Thanks 🙏
