### PR TITLE
[Config] Add merging of rules configuration, call configure() just once

### LINKED ISSUE #8150: AnnotationToAttributeRector misbehaves since v0.18.0
# Bug Report

| Subject        | Details |
|:-------------- |:------- |
| Rector version | v0.18.0 |

As of Rector v0.18.0, when using multiple set lists containing `AnnotationToAttributeRector` rules, only some of them gets applied.

It seems that one set list overwrites this rule's configuration instead of "appending" / "merging" it.

Rector v0.17.13 works as expected.

`disableParallel` doesn't fix the problem.

## Minimal PHP Code Causing Issue

Example using 2 set lists : https://getrector.com/demo/f6e6bf2b-d116-4fb3-924f-4947cf77eb5e

Example using 1 set list : https://getrector.com/demo/3d8941dc-d136-4892-939f-e8c747bcc551

## Expected Behaviour

All annotations handled by the enabled set lists should be converted to attributes (in this case : `ORM`, `Gedmo`, etc.).

Using the same PHP demo file on my machine, Rector v0.17.13 produces this output, which is the intended behavior :

```php
<?php

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Table(name: 'test')]
#[ORM\Entity]
final class Test
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\Column(type: 'string')]
    protected string $id;

    #[Gedmo\SortablePosition]
    #[ORM\Column(type: 'integer', nullable: false)]
    protected int $position;

    public function getId(): string
    {
        return $this->id;
    }

    public function getPosition(): int
    {
        return $this->position;
    }

    public function setPosition(int $position): static
    {
        $this->position = $position;

        return $this;
    }
}
```

Thank you for your work on Rector, tell me if you need any additional information 👍

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixes https://github.com/rectorphp/rector/issues/8150

Closes https://github.com/rectorphp/rector-src/pull/4831

### CODE REVIEW

File: packages/Config/RectorConfig.php [hunk 1]
```diff
@@ -163,14 +168,28 @@ public function ruleWithConfiguration(string $rectorClass, array $configuration)
...
+
+        $isBound = $this->bound($rectorClass);
+
+        // avoid double registration
+        if ($isBound) {
+            return;
+        }
 
+        $this->singleton($rectorClass);
         $this->tagRectorService($rectorClass);
```
Comment (TomasVotruba) [inline packages/Config/RectorConfig.php:185]: Without this check, the same Rector rule would be registered twice. That could lead to unexpected changes and waste of resources.

File: packages/Config/RectorConfig.php [hunk 2]
```diff
@@ -163,14 +168,28 @@ public function ruleWithConfiguration(string $rectorClass, array $configuration)
...
+
+        $this->afterResolving($rectorClass, function (ConfigurableRectorInterface $configurableRector) use (
+            $rectorClass
+        ): void {
+            $ruleConfiguration = $this->ruleConfigurations[$rectorClass];
+            $configurableRector->configure($ruleConfiguration);
+        });
```
Comment (TomasVotruba) [inline packages/Config/RectorConfig.php:192]: The `configure()` is now called exactly once with the full configuration.

We might check for the configuration override and have custom property to add this after resolving too. In case of non-configurable rules, but it might be too defensive. Let's see how it performs :)

**Comment by TomasVotruba** [comment]
Thanks for the solution @samsonasik :+1:

**Comment by samsonasik** [comment]
@TomasVotruba this cause a bug in rector-doctrine, see

- https://github.com/rectorphp/rector-doctrine/pull/221#discussion_r1309081757

I will remove the `$isBound` usage at PR:

- https://github.com/rectorphp/rector-src/pull/4880
