### PR TITLE
fix: remove empty construct when parent has no construct

### LINKED ISSUE #9369: Incorrect behaviour of EmptyClassMethodRector
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v1.0.0 (invoke `vendor/bin/rector --version`)             |

Hello!

In the example below, the constructor should be removed but it isn't.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/aabe02b5-61af-4109-9972-3af2b4e882f9

Thanks!

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

Closes https://github.com/rectorphp/rector/issues/9369

This fixes cases where an empty constructor isn't removed even when the parent does not have a constructor.

It turns out that the removed `if` statement is not needed, the previous conditions already prevent overridden methods from being removed.

Thanks!

### CODE REVIEW

File: rules/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector.php [hunk 1]
```diff
@@ -157,11 +157,6 @@ private function shouldSkipClassMethod(Class_ $class, ClassMethod $classMethod):
             return true;
         }
 
-        if ($this->isName($classMethod, MethodName::CONSTRUCT)) {
```
Comment (samsonasik) [inline rules/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector.php:160]: check from ClassReflection->getAncestors(), exclude current ClassReflection,lookup hasNativeMethod __construct

Comment (samsonasik) [reply rules/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector.php:160]: see exclusion check 

https://github.com/rectorphp/rector-src/blob/78fd064bd347d3a529883933c2e4afe4a76684c5/rules/DeadCode/Rector/ClassMethod/RemoveArgumentFromDefaultParentCallRector.php#L105-L108

Loop check hasNativeMethod

File: rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/removed_empty_construct_when_no_parent.php.inc [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+namespace Rector\Tests\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector\Fixture;
+
+class RemovedEmptyConstructWhenNoParent extends ParentWithoutConstruct
+{
+    public function __construct()
+    {
+    }
+}
+
+abstract class ParentWithoutConstruct
```
Comment (samsonasik) [inline rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/removed_empty_construct_when_no_parent.php.inc]: Move parent to Source directory, add example to skip if parent has __construct

File: rules/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector.php (hunk 1 above)
Comment (samsonasik) [reply rules/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector.php:160]: Oh, I see, it covered at hasParentMethodOrInterfaceMethod

File: rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/removed_empty_construct_when_no_parent.php.inc (hunk 2 above)
Comment (samsonasik) [reply rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/removed_empty_construct_when_no_parent.php.inc]: Also probably worth add check override from trait's construct, which may be on purpose, so "trait" actually a "parent", but check needs in the last resort on

`hasParentMethodOrInterfaceMethod()`

method..

Comment (calebdw) [reply rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/removed_empty_construct_when_no_parent.php.inc]: > add example to skip if parent has __construct

There's already tests for this

Comment (calebdw) [reply rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/removed_empty_construct_when_no_parent.php.inc]: Traits are already handled, I added a test for this

**Review by samsonasik — APPROVED** [review]
Looks good, let's give it a try, thank you @calebdw

**Comment by samsonasik** [comment]
I see for trait use why already checked, there is `IsClassMethodUsedAnalyzer::isClassMethodUsed()` that check on trait already :)

**Comment by samsonasik** [comment]
Oh, it seems private empty __construct should be skipped as used on purpose to avoid instantiation

**Comment by samsonasik** [comment]
Ok, there is fixture for that already

https://github.com/rectorphp/rector-src/blob/e00f52f2bf65bb3ba9a810ea4b806cd1887df3b5/rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/keep_private_constructor.php.inc#L5-L10

that checked on `ClassMethodManipulator::isNamedConstructor()`
