### PR TITLE
 [CodeQuality] Skip different value left and right on SimplifyEmptyArrayCheckRector

### LINKED ISSUE #7543: SimplifyEmptyArrayCheckRector checks unrelated variable for empty array
# Bug Report

## Minimal PHP Code Causing Issue

https://getrector.org/demo/ad7024a9-7588-4c19-81bf-414fedb11ba0

## Expected Behaviour

Don't break the code, it's comparing a completely unrelated variable against empty array.

Created test fixture:
https://github.com/rectorphp/rector-src/pull/2997

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #2997 Fixes https://github.com/rectorphp/rector/issues/7543

### CODE REVIEW

File: rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php [hunk 1]
```diff
@@ -138,14 +138,19 @@ public function refactor(Node $node): ?array
...
 
             if ($rangeLine > 1) {
                 return null;
             }
         }
 
+        // skip same line that cause infinite loop
+        if ($rangeLine === 0) {
+            return null;
+        }
```
Comment (samsonasik) [inline rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php:152]: Given the following code:

```php
if ($node->expr instanceof FuncCall) {
    return ! $node->expr->isFirstClassCallable() && $this->isName($node->expr, 'array_filter') && isset($node->expr->args[0]);
}
```
it cause infinite loop during extracting `&&` operator to each stmt and add new line after it, this handle it.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:
