### PR TITLE
[Php81][CodingStyle] Skip callable param assign with signature multi params on FunctionLikeToFirstClassCallableRector

### LINKED ISSUE #9453: Incorrect behavior of FunctionLikeToFirstClassCallableRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/371133f2-0c1c-4d0f-8e5c-958d89098e39

```php
<?php

class SkipCallableParamAssignFluentMultiParams
{
    private $transform;

    /**
     * @param callable(mixed $datum, int|string|null $key): mixed $callable
     */
    public function withTransform(callable $callable)
    {
        $this->transform = $callable;
        return $this;
    }

    public function run($value, $optionalData = [])
    {
        var_dump(($this->transform)($value, $optionalData));
    }
}

(new SkipCallableParamAssignFluentMultiParams())
    ->withTransform(fn (string $datum): string => trim($datum))
    ->run('  some data  ');
```

### Responsible rules

* `FunctionLikeToFirstClassCallableRector`

## Expected Behavior

should be skipped to avoid error:

```
Fatal error: Uncaught TypeError: trim(): Argument #2 ($characters) must be of type string, array given in /in/aWNCA:15
Stack trace:
#0 /in/aWNCA(15): trim('  some data  ', Array)
#1 /in/aWNCA(21): SkipCallableParamAssignFluent->run('  some data  ')
#2 {main}
  thrown in /in/aWNCA on line 15
```

see 

original: works: https://3v4l.org/SqOPO
changed: error https://3v4l.org/8kku6

I think based on signature docblock, the `@param callable(mixed $datum, int|string|null $key): mixed $callable` should make it skipped.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/9453

original: works: https://3v4l.org/SqOPO
changed: error https://3v4l.org/8kku6

Ref https://getrector.com/demo/371133f2-0c1c-4d0f-8e5c-958d89098e39

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @calebdw

File: rules-tests/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector/Fixture/skip_callable_param_assign_with_signature_multi_params.php.inc [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+    public function run($value, $optionalData = [])
+    {
+        var_dump(($this->transform)($value, $optionalData));
+    }
+}
+
+(new SkipCallableParamAssignWithSignatureMultiParams())
+    ->withTransform(fn (string $datum): string => trim($datum))
+    ->run('  some data  ');
```
Comment (calebdw) [inline rules-tests/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector/Fixture/skip_callable_param_assign_with_signature_multi_params.php.inc:26]: @samsonasik, you should also test that this does convert to first class callable when both params are used:

```diff
function foo(mixed $datum, int|string|null $key) {}

(new SkipCallableParamAssignWithSignatureMultiParams())
-   ->withTransform(fn ($datum, $key) => foo($datum, $key))
+   ->withTransform(foo(...))
    ->run('  some data  ');
```

Comment (samsonasik) [reply rules-tests/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector/Fixture/skip_callable_param_assign_with_signature_multi_params.php.inc:26]: @calebdw I am going to skip for now :), this is already too complex to cover, the issue is not in the `withTransform()`, but on usage, as `run()` has default value, see original issue comment https://github.com/rectorphp/rector/issues/9449#issuecomment-3431615361

Comment (calebdw) [reply rules-tests/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector/Fixture/skip_callable_param_assign_with_signature_multi_params.php.inc:26]: We should not care about the usage in `run` as long as the callable conforms to the signature that's specified on `withTransform`

Comment (samsonasik) [reply rules-tests/CodingStyle/Rector/FunctionLike/FunctionLikeToFirstClassCallableRector/Fixture/skip_callable_param_assign_with_signature_multi_params.php.inc:26]: I prefer to only check multi params when dealing with native function, otherwise, skip for now, as that become hard to review changed code.
