### PR TITLE
fix: Skip refactoring when foreach if statement contains calls to met…

### LINKED ISSUE #8686: ForeachToInArrayRector changing code that cannot be changed to in_array approach
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | last dev-main             |

## Minimal PHP Code Causing Issue
See https://getrector.com/demo/eb744759-eea9-40c4-b502-93615d95761e
```
<?php

namespace Rector\Tests\CodeQuality\Rector\Foreach_\ForeachToInArrayRector\Fixture;

use Rector\Tests\CodeQuality\Rector\Foreach_\ForeachToInArrayRector\Source\Collection;

final class SkipMethodCalls
{
    public function foreachToInArray($items): bool
    {
        foreach ($items as $item) {
            if ($item == $this->strtoupper($item)) {
                return true;
            }
        }

        return false;
    }

    public function strtoupper($item): bool
    {
        return strtoupper((string) $item);
    }
}
```

## Expected Behaviour
Rector should not change the code as it cannot be changed to the in_array approach

### PR DESCRIPTION
**Pull request by nikolicaleksa**
Fixes https://github.com/rectorphp/rector/issues/8686

### CODE REVIEW

File: rules/CodeQuality/Rector/Foreach_/ForeachToInArrayRector.php [hunk 1]
```diff
@@ -157,10 +157,27 @@ private function shouldSkipForeach(Foreach_ $foreach): bool
...
+
+        if ($ifCondition instanceof Expr\BinaryOp && (
+            $ifCondition->left instanceof FuncCall
+            || $ifCondition->left instanceof Expr\MethodCall
+            || $ifCondition->left instanceof Expr\NullsafeMethodCall
+            || $ifCondition->left instanceof Expr\StaticCall
+            || $ifCondition->right instanceof FuncCall
+            || $ifCondition->right instanceof Expr\MethodCall
+            || $ifCondition->right instanceof Expr\NullsafeMethodCall
+            || $ifCondition->right instanceof Expr\StaticCall
```
Comment (samsonasik) [inline rules/CodeQuality/Rector/Foreach_/ForeachToInArrayRector.php]: you may can check when foreach variable value is used instead, that may can be checked by line 104, because this change should be valid on outer value:

```diff
       $outervalue = 'value';
-       foreach ($items as $item) {
-            if ($item == strtoupper($outervalue)) {
-                return true;
-            }
-        }
-        return false;
+        return in_array(strtoupper($outervalue), $items);
```

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @nikolicaleksa
