### PR TITLE
[CodeQuality] Handle crash on variable variable on OptionalParametersAfterRequiredRector

### LINKED ISSUE #7991: Processing phpseclib XML.php file fails with message Scope not available
Parsing file https://github.com/phpseclib/phpseclib/blob/3.0/phpseclib/Crypt/EC/Formats/Keys/XML.php fails with message:
[ERROR] Could not process "phpseclib/Crypt/EC/Formats/Keys/XML.php" 
         file, due to:                                                                                                  
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node with parent node of               
         "PhpParser\Node\Expr\PropertyFetch", but is required by a refactorWithScope() method of                        
         "Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector" rule. Fix scope refresh on       
         changed nodes first"                                                                                           
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(220):                                                    
         Rector\Core\Rector\AbstractScopeAwareRector->refactor()                                                        
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Core\Rector\AbstractRector->enterNode()                                                                 
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #19 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #20 vendor/rector/rector/src/Application/FileProcessor.php(60):                                                
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                            
         #21 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(106):                              
         Rector\Core\Application\FileProcessor->refactor()                                                              
         #22 vendor/rector/rector/packages/Parallel/WorkerRunner.php(130):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #23 vendor/rector/rector/packages/Parallel/WorkerRunner.php(106): Rector\Parallel\WorkerRunner->processFiles() 
         #24 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
         #25 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202304\Evenement\EventEmitter->emit()                                                              
         #26 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202304\Clue\React\NDJson\Decoder->handleData()                                                     
         #27 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202304\Evenement\EventEmitter->emit()                                                              
         #28 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202304\React\Stream\Util::RectorPrefix202304\React\Stream\{closure}()                              
         #29 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202304\Evenement\EventEmitter->emit()                                                              
         #30 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202304\React\Stream\DuplexResourceStream->handleData()                                             
         #31 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202304\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #32 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202304\React\EventLoop\StreamSelectLoop->run()                                                     
         #33 vendor/rector/rector/vendor/symfony/console/Command/Command.php(311):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #34 vendor/rector/rector/vendor/symfony/console/Application.php(899):                                          
         RectorPrefix202304\Symfony\Component\Console\Command\Command->run()                                            
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(320):                                          
         RectorPrefix202304\Symfony\Component\Console\Application->doRunCommand()                                       
         #36 vendor/rector/rector/src/Console/ConsoleApplication.php(49):                                               
         RectorPrefix202304\Symfony\Component\Console\Application->doRun()                                              
         #37 vendor/rector/rector/vendor/symfony/console/Application.php(206):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #38 vendor/rector/rector/bin/rector.php(128): RectorPrefix202304\Symfony\Component\Console\Application->run()  
         #39 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #40 vendor/bin/rector(117): include('...')                                                                     
         #41 {main}". On line: 55

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://getrector.com/demo/6ac5df8b-2058-4b72-83e9-646614ef6b00
Fixes https://github.com/rectorphp/rector/issues/7991

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @alphpkeemik

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

File: packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php [hunk 1]
```diff
@@ -145,6 +146,19 @@ public function processNodes(
                 $node->expr->setAttribute(AttributeKey::SCOPE, $mutatingScope);
             }
 
+            $expr = $node;
```
Comment (samsonasik) [inline packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:149]: this may need to be cloned to avoid object changed, ref https://3v4l.org/BU1O0

Comment (samsonasik) [reply packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:149]: I tried debug after while, and it seems the object is followed, and target change is different with original node, so it actually ok, see https://3v4l.org/lR4mF
