### PR TITLE
[TypeDeclaration] Skip possible array on StrictStringParamConcatRector

### LINKED ISSUE #8636: Incorrect behavior of StrictStringParamConcatRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

I think no type should be inferred when the variable involved is checked via one of the `is_` functions

See https://getrector.com/demo/9be58231-7607-4cc6-94f5-fb5b061396b6

```php
<?php

final class DemoFile
{
    public function run($key): void
    {
        if (\is_array($key)) {
            $dayKey = [$key[0], $key[1] . '_day'];
        } else {
            $dayKey = $key . '_day';
        }        
    }
}
```

### Responsible rules

* `StrictStringParamConcatRector`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8636

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @staabm

File: rules/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector.php [hunk 1]
```diff
@@ -101,16 +101,22 @@ public function refactor(Node $node): ?Node
...
+                continue;
+            }
 
-            if ($nativeType instanceof MixedType && $nativeType->getSubtractedType() instanceof Type && TypeCombinator::containsNull(
-                $nativeType->getSubtractedType()
-            )) {
-                $param->type = new NullableType(new Identifier('string'));
-            } else {
+            $subtractedType = $nativeType->getSubtractedType();
+            if (! $subtractedType instanceof Type) {
```
Comment (staabm) [inline rules/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector.php:109]: ahh this looks smart.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)
