### PR TITLE
 [DeadCode] Skip sub type false => bool on RemoveUselessVarTagRector 

### LINKED ISSUE #8475: Incorrect behavior of RemoveUselessVarTagRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a3439a03-dc38-4b51-94cd-4b186f066762

```php
<?php

class UrlTest extends AbstractTestCase
 {
     /** @var string|false|null */
     private static string|bool|null $inputArgSeparator = null;
}
```

### Responsible rules

* `RemoveUselessVarTagRector`

## Expected Behavior

I would expect no change. The docbloc type is narrowing the type down. There are reasons why the native type is wider, so it's not unthinkable to have a narrower docbloc.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8475

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @kamil-tekiela

File: src/NodeTypeResolver/TypeComparator/TypeComparator.php [hunk 1]
```diff
@@ -87,10 +84,6 @@ public function arePhpParserAndPhpStanPhpDocTypesEqual(
             $node
         );
 
-        // normalize bool union types
-        $phpParserNodeType = $this->normalizeConstantBooleanType($phpParserNodeType);
-        $phpStanDocType = $this->normalizeConstantBooleanType($phpStanDocType);
```
Comment (samsonasik) [inline src/NodeTypeResolver/TypeComparator/TypeComparator.php]: this apparently, make the valid removal skipped for super type:

```
     /** @var string|bool|null */
     private static string|false|null $inputArgSeparator = null;
```

which docblok is super type, I will look more.

Comment (samsonasik) [reply src/NodeTypeResolver/TypeComparator/TypeComparator.php]: I added failing test case for valid removal super type https://github.com/rectorphp/rector-src/pull/5588/commits/0c89834ab73ba3384c74d729d227c533cce5b5db

Comment (samsonasik) [reply src/NodeTypeResolver/TypeComparator/TypeComparator.php]: Fixed with equal and sub type check https://github.com/rectorphp/rector-src/pull/5588/commits/3690cad412c0a2c9632c128c3c129c573ad79fc0

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)
