### PR TITLE
fix(ArrayKeyFirstLastRector): Skip exection when pointer is changed

### LINKED ISSUE #8203: Incorrect behavior of ArrayKeyFirstLastRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | v0.18.3 dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ed24d5ae-efa7-447a-884e-9e8b1ef04e84

```php
<?php

function a(array $arr) {
    reset($arr);
    while(true) {
        $key = key($arr);
        $value = current($arr);
        if ($key === null) {
            break;
        }
        echo $key . ": " . $value . PHP_EOL;
        next($arr);
    }
}
$arr = [1, 2, 3];
a($arr);
```

### Responsible rules

* `ArrayKeyFirstLastRector`

The proposed change creates an infinite loop.
## Expected Behavior

Rector should probably skip applying this rule if the `key()` function call is used in a loop context.

### PR DESCRIPTION
**Pull request by scyzoryck**
Hello! 

Fix https://github.com/rectorphp/rector/issues/8203
It looks like skipping next node was also causing the issue - next call was not checked inside the loop.

### CODE REVIEW

File: rules-tests/Php73/Rector/FuncCall/ArrayKeyFirstLastRector/Fixture/skip_next_call_after.php.inc [hunk 1]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+function a(array $arr) {
```
Comment (samsonasik) [inline rules-tests/Php73/Rector/FuncCall/ArrayKeyFirstLastRector/Fixture/skip_next_call_after.php.inc]:
```suggestion
<?php

namespace Rector\Tests\Php73\Rector\FuncCall\ArrayKeyFirstLastRector\Fixture;

function skipExecutionHasNextNext(array $arr) {
```

File: rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php [hunk 2]
```diff
@@ -200,8 +200,9 @@ function (Node $subNode) use ($funcCall): bool {
                     if (! $subNode instanceof FuncCall) {
                         return false;
                     }
+                    echo $subNode->name;
```
Comment (samsonasik) [inline rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php]: remove this debug:

```suggestion
```

File: rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php [hunk 3]
```diff
@@ -137,7 +137,7 @@ private function processArrayKeyFirstLast(
                 continue;
             }
 
-            if ($this->hasPrevCallNext($stmtsAware, $key + 2, $totalKeys, $keyFuncCall)) {
+            if ($this->hasInternalPointerChangeNext($stmtsAware, $key + 1, $totalKeys, $keyFuncCall)) {
```
Comment (samsonasik) [inline rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php:140]: old + 2 is the correct way afaik, as it check next after

File: rules-tests/Php73/Rector/FuncCall/ArrayKeyFirstLastRector/Fixture/skip_next_call_after.php.inc [hunk 4]
```diff
@@ -0,0 +1,19 @@
+<?php
+<?php
```
Comment (samsonasik) [inline rules-tests/Php73/Rector/FuncCall/ArrayKeyFirstLastRector/Fixture/skip_next_call_after.php.inc]:
```suggestion
<?php

```

File: rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php (hunk 3 above)
Comment (samsonasik) [reply rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php:140]: keep using + 2 since it validate after the next of next

```suggestion
            if ($this->hasInternalPointerChangeNext($stmtsAware, $key + 2, $totalKeys, $keyFuncCall)) {
```

Comment (scyzoryck) [reply rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php:140]: Thanks for feedback. I was trying to understand what exactly it does. 
+2 was causing the issues in the case when call to `key` was inside `while` loop. It was working fine for:
```
function skipExecutionHasNextNext(array $arr) {
    reset($arr);
    $key = key($arr);
    $value = current($arr);
    echo $key . ": " . $value . PHP_EOL;
    next($arr);
}
```
So as I understand on the function level there were only 2 stmts - `reset` & `while` loop. However after my changes it might also look for calls that are happening before `key`, but inside the while loop.

Comment (samsonasik) [reply rules/Php73/Rector/FuncCall/ArrayKeyFirstLastRector.php:140]: I see, let's give it a try 👍

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @scyzoryck
