### PR TITLE
[DeadCode][Privatization] Handle crash on RemoveDeadZeroAndOneOperationRector+ChangeReadOnlyPropertyWithDefaultValueToConstantRector

### LINKED ISSUE #7503: RemoveDeadZeroAndOneOperationRector and ChangeReadOnlyPropertyWithDefaultValueToConstantRector don't work together in specific case
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

Rector fails with specific combination of rules and specific code.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f13e68a7-53c7-473e-a307-0e7268e188f0

## Expected Behaviour

Not really sure, probably `return self::PRICE * self::VAT` in the method. 

But more importantly, it shouldn't result in error.

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class OnVariable
{
    private ?int $price = null;
    private int $vat = 1;

    public function run()
    {
        $priceWithVat = (int)round($this->price * (1 + ($this->vat / 100)));
    }
}
```

It currently make crash:

```
1) Rector\Core\Tests\Issues\Issue7503\RemoveDeadZeroChangeReadOnlyPropertyTest::test with data set #1 ('/Users/samsonasik/www/rector-...hp.inc')
Rector\Core\Exception\ShouldNotHappenException: Complete class parent node for to class const fetch, so "self" or "static" references is resolvable to a class name
```

see https://getrector.org/demo/27616c4c-4b24-4b2c-8fc7-9f96db366e62

This PR try to fix it. 

Fixes https://github.com/rectorphp/rector/issues/7503

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @noximo

File: packages/PhpDocParser/NodeTraverser/SimpleCallableNodeTraverser.php [hunk 1]
```diff
@@ -34,6 +35,7 @@ public function traverseNodesWithCallable(Node | array | null $nodes, callable $
         $nodeTraverser = new NodeTraverser();
         $callableNodeVisitor = new CallableNodeVisitor($callable);
         $nodeTraverser->addVisitor($callableNodeVisitor);
+        $nodeTraverser->addVisitor(new ParentConnectingVisitor());
```
Comment (samsonasik) [inline packages/PhpDocParser/NodeTraverser/SimpleCallableNodeTraverser.php:38]: this is ensure fill parent Node when replacing Node with other Node via `traverseNodesWithCallable()` 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]
