### PR TITLE
[AutoImport] Do not add cast on valid Integer type on Name Node on auto import enabled

### LINKED ISSUE #8793: Incorrect behavior of ConsoleExecuteReturnIntRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/753c3d4f-c1c8-4e40-aa91-96a739734d7e

```php
<?php

namespace App\Command\User;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    private ?OutputInterface $outputInterface = null;

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        return Command::SUCCESS;
    }
}
```

### Responsible rules

* `ConsoleExecuteReturnIntRector`

## Expected Behavior

Rector changes the line
```
        return Command::SUCCESS;
```
to
```
        return (int) Command::SUCCESS;
```
And it shouldn't

I have tried to investigate the issue and as far as I can tell what happens is:
- Rector applies the rules and on this first run the `Command:SUCCESS` expression (a `ClassConstantFetch` node) has the property `class` equal to "Symfony\Component\Console\Command\Command". The `ConsoleExecuteReturnIntRector` correctly identifies the type of this expression as an integer and does not change the code
- The post rectors are applied and the `NameImportingPostRector` rector is called. This changes the `class` property of this expression to `Command`
- Since there were changes applied, the rector rules are applied again. On this second run, when the `ConsoleExecuteReturnIntRector` rector tries to identify the type of the expression, since the node does not have the FQN, the `getType()` function in the `MutatingScope` returns an `ErrorType` and, since this is not an int, the `(int)` cast is added

I tried to figure out a solution but was unable to decide how to go about adding one, hope all these details can help someone else decide how to tackle this

Note: there needs to be another rector rule that changes this file for these erroneous changes to show, could be any rule, I used `RemoveUnusedPrivatePropertyRector` but any other that changes the file will do. Seems that if the only rector to change the file is `ConsoleExecuteReturnIntRector` then these changes are not applied

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8793

### CODE REVIEW

**Comment by samsonasik** [comment]
@carlos-granados @TomasVotruba I added `ClassConstFetchTypeResolver` which verify its `$node->class` is a `Name` with `namespacedName` attribute to cover it

https://github.com/rectorphp/rector-src/pull/6236/commits/a0bef122c375e1fdd7f3770007df044194104b2f

I will add more test for direct `Name` usage when possible, eg: on `Some\StaticClass::execute()` to cast not casted to`int` while `Some\StaticClass` already imported to verify that `namespacedName` attribute is needed on `NameTypeResolver`

**Comment by samsonasik** [comment]
I added failing fixture for from `StaticCall` https://github.com/rectorphp/rector-src/pull/6236/commits/6a28fe4000546b098b1b3052d588ad6b67218468  which got cast int because of it read a `Name`

https://github.com/rectorphp/rector-src/blob/3ed476b9ab65958d85416e48a810b11dbaf4283a/src/NodeTypeResolver/NodeTypeResolver/StaticCallMethodCallTypeResolver.php#L72

which has `namespacedName` which should pull it from it.

**Comment by samsonasik** [comment]
Fixed 🎉

File: src/NodeTypeResolver/NodeTypeResolver/NameTypeResolver.php [hunk 1]
```diff
@@ -37,6 +37,11 @@ public function getNodeClasses(): array
      */
     public function resolve(Node $node): Type
     {
+        // not instanceof FullyQualified means it is a Name
+        if (! $node instanceof FullyQualified && $node->hasAttribute(AttributeKey::NAMESPACED_NAME)) {
+            return $this->resolve(new FullyQualified($node->getAttribute(AttributeKey::NAMESPACED_NAME)));
+        }
```
Comment (samsonasik) [inline src/NodeTypeResolver/NodeTypeResolver/NameTypeResolver.php:43]: this is really needed to patch `StaticCall` that imported fixture https://github.com/rectorphp/rector-src/pull/6236/files#diff-ec6cd31df51e19b0199b350a318339fbc3e2b1aa740593511a466849e7fc5289 as a proof that `namespacedName` attribute is needed on `NameTypeResolver` 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)
