### PR TITLE
Do not apply property promotion to parameters with the SensitiveParameter attribute

### LINKED ISSUE #7644: Incorrect behavior of ClassPropertyAssignToConstructorPromotionRector with SensitiveParameter attribute
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.15.0      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cd6191ec-6e65-4c8c-882f-7e69c3ed6808

```php
<?php

final class ApiClient
{
    private readonly string $apiKey;

    public function __construct(
        #[\SensitiveParameter] string $apiKey,
    ) {
        $this->apiKey = $apiKey;
    }
}
```

### Responsible rules

* `ClassPropertyAssignToConstructorPromotionRector`

## Expected Behavior

The `SensitiveParameter` attribute only targets parameters, so constructor arguments with this attribute should not use property promotion.

### PR DESCRIPTION
**Pull request by mbabker**
Fixes https://github.com/rectorphp/rector/issues/7644

### CODE REVIEW

File: rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/property_with_sensitiveparameter_attribute.php.inc [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+final class PropertyWithSensitiveParameterAttribute
+{
+    private string $password;
+
+    public function __construct(#[\SensitiveParameter] string $password)
+    {
+        $this->password = $password;
+    }
+}
+?>
```
Comment (samsonasik) [inline rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/property_with_sensitiveparameter_attribute.php.inc]: The second part can be removed:

```suggestion
```

File: rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/property_with_sensitiveparameter_attribute.php.inc [hunk 2]
```diff
@@ -0,0 +1,33 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Rector\Tests\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector\Fixture;
+
+final class PropertyWithSensitiveParameterAttribute
```
Comment (samsonasik) [inline rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/property_with_sensitiveparameter_attribute.php.inc]:
```suggestion
final class SkipPropertyPromotionWithSensitiveParameterAttribute
```

File: rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/property_with_sensitiveparameter_attribute.php.inc [hunk 3]
```diff
@@ -0,0 +1,33 @@
+<?php
```
Comment (samsonasik) [inline rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/property_with_sensitiveparameter_attribute.php.inc]: please rename the file to `skip_property_promotion_with_sensitive_parameter_attribute.php.inc`

File: rules/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector.php [hunk 4]
```diff
@@ -224,6 +226,10 @@ private function shouldSkipParam(Param $param): bool
             return true;
         }
 
+        if ($this->phpAttributeAnalyzer->hasPhpAttribute($param, \SensitiveParameter::class)) {
```
Comment (samsonasik) [inline rules/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector.php]: please use string value: "SensitiveParameter" to avoid prefixed on downgrade

```suggestion
        if ($this->phpAttributeAnalyzer->hasPhpAttribute($param, 'SensitiveParameter')) {
```

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by TimWolla** [comment]
FWIW: Putting the `#[\SensitiveParameter]` attribute onto promoted properties should be fine as of https://github.com/php/php-src/pull/9661.

See: https://3v4l.org/laljt

**Comment by samsonasik** [comment]
The actual bug seems the Attribute removed during converting to property promotion, which should be kept, I will re-open the issue.
