### PR TITLE
[CodeQuality] Handle throw after if on ConsecutiveNullCompareReturnsToNullCoalesceQueueRector

### LINKED ISSUE #7976: Incorrect behavior of ConsecutiveNullCompareReturnsToNullCoalesceQueueRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/8420e8f2-769b-453b-b2cb-b4289a8cb15c

```php
<?php

class MyClass {
    protected ?stdClass $prop1 = null;
    protected ?stdClass $prop2 = null;

    public function getProp(): stdClass {
        if ($this->prop1 !== null) {
            return $this->prop1;
        }
        if ($this->prop2 !== null) {
            return $this->prop2;
        }
        throw new RuntimeException('No prop is set');
    }
}
```

### Responsible rules

* `ConsecutiveNullCompareReturnsToNullCoalesceQueueRector`

## Expected Behavior

Desired behavior is either to do nothing at all, or transform to something like the following (throw expression requires PHP 8):

```php
    public function getProp(): stdClass {
        return $this->prop1 ?? $this->prop2 ?? throw new RuntimeException('No prop is set');
    }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7976

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @jlherren

File: rules-tests/CodeQuality/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/throw_after_if.php.inc [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+namespace Rector\Tests\CodeQuality\Rector\If_\ConsecutiveNullCompareReturnsToNullCoalesceQueueRector\Fixture;
+
+final class ThrowAfterIf
+{
+    protected ?\stdClass $prop1 = null;
+    protected ?\stdClass $prop2 = null;
+
+    public function getProp(): \stdClass
+    {
+        return ($this->prop1 ?? $this->prop2) ?? new \RuntimeException('No prop is set');
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/throw_after_if.php.inc]: return throw seems got fatal error, with or without parentheses:

ref https://3v4l.org/JKLAh vs https://3v4l.org/V9iA1

so probably better to skip it.

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/throw_after_if.php.inc]: I updated to skip instead https://github.com/rectorphp/rector-src/pull/4107/commits/0c2710fd35fa4de73427d6795792ed6cfdfc6d53

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/throw_after_if.php.inc]: Oh, I see, throw Expr can actually be used

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/throw_after_if.php.inc]: see https://3v4l.org/9FAt4

Comment (samsonasik) [reply rules-tests/CodeQuality/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/throw_after_if.php.inc]: Fixed https://github.com/rectorphp/rector-src/pull/4107/commits/8b73ec29a8f5f5684996e6c066803c7c6588918c

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)
