### PR TITLE
[DX] Depreate heavy and conflicting Symfony/Twig/PHPUnit level sets

### LINKED ISSUE #8403: [ERROR] Rector timeout after upgrading it to 0.19.0
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.19.0            |

Since the upgrade of rector (from 0.18.13 to 0.19.0) I have this big error :
image

I also try to folow these intructions without sucess
https://getrector.com/documentation/troubleshooting-parallel

## Minimal PHP Code Causing Issue

1. Edit cmposer.json file

```.json
{
    "require-dev": {
        "rector/rector": "^0.19.0"
    }
}

```

2. Run `composer update`

**This is the 1st time I've had this at an rector update.**

## Expected Behaviour
Job passing like in version `0.18.13`, just before upgrading rector to the `0.19.0`

### PR DESCRIPTION
**Pull request by TomasVotruba**
It's not best practise to use `UP_TO_*` sets in `rector.php` longer than is their single-run. They run dozens of rules with very complex logic, as it take to get from Symfony 2 to 7. It's like running a Tesla control and checking all elements available since the first horse ride :) 

Also, the tools we build upon - php-parser and PHPStan - traverse tree from top to bottom. That means if Symfony 4.4 changes a class, and then Symfony 3.4 changed a method, the changes would crash with each other.

We published post about this, but we should do more to have a DX that is useful and practical:
https://getrector.com/blog/5-common-mistakes-in-rector-config-and-how-to-avoid-them

The best practice - and we use it this way since the first Symfony rule set - to run those just once and remove :+1: 

<br>

Instead use only the latest major sets, to keep up to date and get fast and reliable Rector run  :rocket: 

Thank you

* Resolves https://github.com/rectorphp/rector/issues/8403
* Resolves https://github.com/rectorphp/rector-symfony/pull/547

### CODE REVIEW

File: src/Config/RectorConfig.php [hunk 1]
```diff
@@ -66,6 +69,25 @@ public function sets(array $sets): void
...
+                continue;
+            }
+
+            // display only on main command run, skip spamming in workers
+            $commandArguments = $_SERVER['argv'];
+            if (! in_array('worker', $commandArguments, true)) {
+                // show warning, to avoid confusion
+                $symfonyStyle = new SymfonyStyle(new ArrayInput([]), new ConsoleOutput());
+                $symfonyStyle->warning(
+                    "The Symfony/Twig/PHPUnit level sets are deprecated since Rector 0.19.2, because of heavy performance load and conflicting overrides. Instead, use latest major set instead.\n\nFor more, see https://getrector.com/blog/5-common-mistakes-in-rector-config-and-how-to-avoid-them"
```
Comment (samsonasik) [inline src/Config/RectorConfig.php]: double `instead`:

```suggestion
                    "The Symfony/Twig/PHPUnit level sets have been deprecated since Rector 0.19.2 due to heavy performance loads and conflicting overrides. Instead, please use the latest major set.\n\nFor more information, visit https://getrector.com/blog/5-common-mistakes-in-rector-config-and-how-to-avoid-them"
```

Comment (TomasVotruba) [reply src/Config/RectorConfig.php]: Thanks :+1:

**Comment by jackbentley** [comment]
This "best practice" is silly. If I'm running rector in CI then I want it to prevent known deprecated code from being introduced.

Changing from `UP_TO_SYMFONY_54` to `SYMFONY_54` will only find deprecations in that single minor release. Any deprecations in prior minor versions won't be checked. This means any new code which is deprecated in any version prior to the current can unknowingly get introduced.

The only way to make sure this new already deprecated code gets fixed is to run periodic `UP_TO_*` - which is not good as it will now include more changes than necessary.

Not to mention you've **_removed_** not deprecated the `UP_TO_*` functionality... This is not what deprecated means. **If it was deprecated it would still work.**

I agree running for example Symfony 3.3 rules on Symfony 5.4 is silly, unnecessary and intensive. You're essentially running fixes for code which is impossible to have implemented. What we actually need is sets which include fixes for all deprecations in the current major versions (if the package follows semver that is). For example, `SYMFONY_5` to include `51`, `52`, `53` and `54` sets.

**Comment by TomasVotruba** [comment]
> For example, SYMFONY_5 to include 51, 52, 53 and 54 sets.

I like this option 👍
How can we implement it to keep easy to maintain and setup in rector config?

**Comment by jackbentley** [comment]
If you're able to use glob patterns (or can enable it to be allowed) then you could set it up so the constant is pointed to all the sets in that version - for example, `final public const SYMFONY_5 = __DIR__ . '/../../config/sets/symfony/symfony5*.php';` here https://github.com/rectorphp/rector-symfony/blob/main/src/Set/SymfonySetList.php

Worth mentioning an edge case might be someone running Symfony 6.1 when Symfony 6.2 is available with rectors. The rectors may add code which won't function. However, I'd expect in most cases people will be upgrading to the latest minor version at the same time as when they upgrade rector. Regardless such a feature is useful for running older versions like Symfony 5.4.

**Comment by samsonasik** [comment]
`RectorConfig->import()` no longer support fnmatch, see

https://github.com/rectorphp/rector-src/blob/f03a6fd7d060535a5c124fe461190aafc527364e/src/Config/RectorConfig.php#L227-L231

so if that needed, the collection of explicit paths need to be registered
