### PR TITLE
[TypeDeclaration] Keep constant false return type from strict native call

### LINKED ISSUE #8291: Incorrect behavior of ReturnTypeFromStrictNativeCallRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/1d9acf5c-0268-4a8e-b3d4-991ce1864347

```php
<?php

namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;

final class SomeNativeMethodCall
{
    public function run()
    {
        return ob_get_clean();
    }
}
```

### Responsible rules

* `ReturnTypeFromStrictNativeCallRector`

## Expected Behavior

I think Rector should keep constant `false` return type.

```php
<?php

namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;

final class SomeNativeMethodCall
{
    public function run(): string|false
    {
        return ob_get_clean();
    }
}
```

### PR DESCRIPTION
**Pull request by tomi85**
close [rectorphp/rector#8291](https://github.com/rectorphp/rector/issues/8291)

### CODE REVIEW

**Review by staabm — APPROVED** [review]

File: rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+-----
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;
+
+final class SomeNativeMethodCall
+{
+    public function run(): string|false
+    {
+        return ob_get_clean();
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc:23]: could you add 1 more fixture?

```
if (rand(0,1)) {
    return ob_get_clean();
}

return in_array($a, $b, true)

File: rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union.php.inc [hunk 2]
```diff
@@ -0,0 +1,27 @@
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;
+
+final class SomeNativeMethodCall
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union.php.inc]:
```suggestion
final class NativeMethodCallReturningUnion
```

File: rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union.php.inc [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+    }
+}
+
+?>
+-----
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;
+
+final class SomeNativeMethodCall
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union.php.inc]:
```suggestion
final class NativeMethodCallReturningUnion
```

File: rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc [hunk 4]
```diff
@@ -0,0 +1,27 @@
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;
+
+final class SomeNativeMethodCall
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc]:
```suggestion
final class NativeMethodCallReturningUnionFalse
```

File: rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+    }
+}
+
+?>
+-----
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector\Fixture;
+
+final class SomeNativeMethodCall
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc]:
```suggestion
final class NativeMethodCallReturningUnionFalse
```

File: rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc (hunk 1 above)
Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc:23]: The new fixture required for check:

```php
if (rand(0,1)) {
    return ob_get_clean();
}

return in_array($a, $b, true)
```

should keep:

```php
string|bool
```

could you add it?

Comment (tomi85) [reply rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictNativeCallRector/Fixture/native_method_call_returning_union_false.php.inc:23]: I've added 2 fixtures because the result depends on the order in which the functions are called, and I've modified the function to merge constant and removed-constant types if necessary.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:
