### PR TITLE
Fix multi property default assign

### LINKED ISSUE #7541: Incorrect behavior of InlineConstructorDefaultToPropertyRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

```php
<?php

final class DemoFile
{
    private $thing1, $thing2, $thing3;
    
    public function __construct()
    {
        $this->thing1 = 1;
        $this->thing2 = 2;
        $this->thing3 = 3;
    }
}
```

See https://getrector.org/demo/cdfb2192-cb53-4dda-891f-056fc92a43ac for what happens

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

I guess changing it to `private $thing1 = 1, $thing2 = 2, $thing3 = 3;` would be the smallest end code change, although my preference (and I think the more common standard) would be to put each property on their own lines. Either way the code should probably work at the end! 😉

### PR DESCRIPTION
**Pull request by TomasVotruba**
FIxes https://github.com/rectorphp/rector/issues/7541

### CODE REVIEW

File: rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_joined_property.php.inc [hunk 1]
```diff
@@ -0,0 +1,32 @@
+<?php
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_joined_property.php.inc]: fixture file name should not start with `skip_`, as it not skipped.

Comment (TomasVotruba) [reply rules-tests/CodeQuality/Rector/Class_/InlineConstructorDefaultToPropertyRector/Fixture/skip_joined_property.php.inc]: Good catch :+1:
