### PR TITLE
[PhpParser] Re-add back get value from __DIR__ and __FILE__ on ValueResolver

### LINKED ISSUE #9035: ValueResolver confused by __DIR__ constant
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.0.9             |

I am trying to upgrade a custom Rector rule from old version of Rector in https://github.com/j0k3r/graby/pull/365 but in 2.0, it no longer appears to be able to handle `__DIR__` constant.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/4c428282-bbc7-46b6-9db4-eab6d9e90f2f

Inserting `var_dump` (not allowed on the demo server) would show:

```php
array(1) {
  ["bar"]=>
  NULL
}
```

## Expected Behaviour

It should resolve the `__DIR__` constant in the context of refactored file:

```php
array(1) {
  ["bar"]=>
  array(1) {
    ["foo"]=> "/home/jtojnar/Projects/graby/tests/bar"
  }
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/9035

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba this is bring test on first commit for https://github.com/rectorphp/rector/issues/9035, without the patch, the result test will failure:

```diff
There was 1 failure:

1) Rector\Tests\Issues\GetValueMagicDir\GetValueMagicDirTest::test with data set #0 ('/home/runner/work/rector-src/...hp.inc')
Failed on fixture file "fixture.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function run()
     {
-        'tests/Issues/GetValueMagicDir/Fixture';
-        'tests/Issues/GetValueMagicDir/Fixture/fixture.php';
+        '__DIR__';
+        '__FILE__';
```

see https://github.com/rectorphp/rector-src/actions/runs/13496093011/job/37703584689?pr=6756

**Comment by samsonasik** [comment]
Fixed /cc @jtojnar with add back CurrentFileProvider to it ;) https://github.com/rectorphp/rector-src/pull/6756/commits/8ca2ffd9be9c61c60ca52e908d622d37d6e6a411

**Comment by samsonasik** [comment]
Add more use case for array [add more use case for inside array](https://github.com/rectorphp/rector-src/pull/6756/commits/d033eaf33c3b433a364152554fa695c52fe8e333)

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
:+1:

File: tests/Issues/GetValueMagicDir/Fixture/fixture.php.inc [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+-----
+<?php
+
+namespace Rector\Tests\Issues\GetValueMagicDir\Fixture;
+
+class Fixture
+{
+    public function run()
+    {
+        'tests/Issues/GetValueMagicDir/Fixture';
```
Comment (staabm) [inline tests/Issues/GetValueMagicDir/Fixture/fixture.php.inc:26]: why is `strlen(__DIR__);` turned into `'tests/Issues/GetValueMagicDir/Fixture';`?

should it be `strlen('tests/Issues/GetValueMagicDir/Fixture');` instead?

Comment (samsonasik) [reply tests/Issues/GetValueMagicDir/Fixture/fixture.php.inc:26]: this just for "test" get value, so make it as simple as possible to demonstrate it, and value is transformed into relative path so works on any system, see custom rule for testing it https://github.com/rectorphp/rector-src/pull/6756/files#diff-e0b7be3278d23771d5ff968abb282736b6f811d41bd4404922dbfd1b15e85aeb
