### PR TITLE
[Php70] Handle empty branch crash on unprintable char \x0C on EregToPregMatchRector

### LINKED ISSUE #8854: [ERROR] Could not process "/src/phpcms/parser/include/class.pax_phpcms.php" file, due to: "System error: "empty branch"
DEBUG:
 [ERROR] Could not process "/src/phpcms/parser/include/class.pax_phpcms.php" file, due to:
         "System error: "empty branch"

         Stack trace:
         #0 vendor/rector/rector/rules/Php70/EregToPcreTransformer.php(89):
         Rector\Php70\EregToPcreTransformer->_ere2pcre()
         #1 vendor/rector/rector/rules/Php70/EregToPcreTransformer.php(73):
         Rector\Php70\EregToPcreTransformer->ere2pcre()
         #2 vendor/rector/rector/rules/Php70/Rector/FuncCall/EregToPregMatchRector.php(91):
         Rector\Php70\EregToPcreTransformer->transform()
         #3 vendor/rector/rector/rules/Php70/Rector/FuncCall/EregToPregMatchRector.php(172):
         Rector\Php70\Rector\FuncCall\EregToPregMatchRector->processStringPattern()
         #4 vendor/rector/rector/rules/Php70/Rector/FuncCall/EregToPregMatchRector.php(64):
         Rector\Php70\Rector\FuncCall\EregToPregMatchRector->refactorFuncCall()
         #5 vendor/rector/rector/src/Rector/AbstractRector.php(140):
         Rector\Php70\Rector\FuncCall\EregToPregMatchRector->refactor()
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114):
         Rector\Rector\AbstractRector->enterNode()
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(134):
         PhpParser\NodeTraverser->traverseNode()
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(198):
         PhpParser\NodeTraverser->traverseNode()
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #14 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(47):
         PhpParser\NodeTraverser->traverse()
         #15 vendor/rector/rector/src/Application/FileProcessor.php(113):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #16 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(184):
         Rector\Application\FileProcessor->processFile()
         #17 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(161):
         Rector\Application\ApplicationFileProcessor->processFile()
         #18 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(138):
         Rector\Application\ApplicationFileProcessor->processFiles()
         #19 vendor/rector/rector/src/Console/Command/ProcessCommand.php(156):
         Rector\Application\ApplicationFileProcessor->run()
         #20 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):
         Rector\Console\Command\ProcessCommand->execute()
         #21 vendor/rector/rector/vendor/symfony/console/Application.php(960):
         RectorPrefix202410\Symfony\Component\Console\Command\Command->run()
         #22 vendor/rector/rector/vendor/symfony/console/Application.php(333):
         RectorPrefix202410\Symfony\Component\Console\Application->doRunCommand()
         #23 vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202410\Symfony\Component\Console\Application->doRun()
         #24 vendor/rector/rector/vendor/symfony/console/Application.php(216):
         Rector\Console\ConsoleApplication->doRun()
         #25 vendor/rector/rector/bin/rector.php(130): RectorPrefix202410\Symfony\Component\Console\Application->run()
         #26 vendor/rector/rector/bin/rector(5): require_once('...')
         #27 vendor/bin/rector(120): include('...')
         #28 {main}". On line: 149

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8854

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @bisenegger

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

File: rules/Php70/EregToPcreTransformer.php [hunk 1]
```diff
@@ -189,11 +191,15 @@ private function _ere2pcre(string $content, int $i): array
...
 
-        return [$this->normalize(implode('|', $r)), $i];
+        return [$this->normalize(implode('|', $r), $normalizeUnprintableChar), $i];
     }
 
-    private function normalize(string $content): string
+    private function normalize(string $content, bool $normalizeUnprintableChar): string
     {
+        if ($normalizeUnprintableChar) {
+            $content = str_replace("\x0C", '\\\f', $content);
```
Comment (samsonasik) [inline rules/Php70/EregToPcreTransformer.php:200]: On scoper downgrade, it seems replaced with 

```php
        if ($normalizeUnprintableChar) {
            $content = \str_replace("\f", '\\\\f', $content);
        }
```

I will check when it deployed to getrector.com

Comment (samsonasik) [reply rules/Php70/EregToPcreTransformer.php:200]: It seems working ok https://getrector.com/demo/b1ed83c8-c2a0-40bb-b3d4-0e098573f462

@bisenegger please try latest `"rector/rector": "dev-main"` and test if the issue persist, better if you can provide reproducible code like the link above, and better, provide patch as well if possible, thank you
