### PR TITLE
Fix SingleInArrayToCompareRector if array item is variadic

### LINKED ISSUE #7893: Incorrect behavior of SingleInArrayToCompareRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/001ae62c-7857-4ce2-b4c1-8be77fd37568

```php
<?php

final class DemoFile
{
    public function run()
    {
        $a = ['a', 'b'];
        echo in_array('a', [...$a]);
    }
}
```

### Responsible rules

* `SingleInArrayToCompareRector`

## Expected Behavior
Either no change or
```php
<?php

final class DemoFile
{
    public function run()
    {
        $a = ['a', 'b'];
        echo in_array('a', $a);
    }
}
```

### PR DESCRIPTION
**Pull request by raoz**
Based on https://getrector.com/demo/001ae62c-7857-4ce2-b4c1-8be77fd37568

Closes https://github.com/rectorphp/rector/issues/7893

### CODE REVIEW

File: rules-tests/CodeQuality/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/variadic.php.inc [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+final class DemoFile
+{
+    public function run()
+    {
+        $a = ['a', 'b'];
+        echo in_array('a', [...$a]);
+    }
+}
+
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/variadic.php.inc]: from this line below is unneded, can be removed

File: rules-tests/CodeQuality/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/variadic.php.inc [hunk 2]
```diff
@@ -0,0 +1,29 @@
+<?php
+
+namespace Rector\Tests\CodeQuality\Rector\FuncCall\SingleInArrayToCompareRector\Fixture;
+
+final class DemoFile
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/variadic.php.inc]:
```suggestion
final class SkipUnpackArrayItemExists
```

File: rules-tests/CodeQuality/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/variadic.php.inc [hunk 3]
```diff
@@ -0,0 +1,29 @@
+<?php
```
Comment (samsonasik) [inline rules-tests/CodeQuality/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/variadic.php.inc]: please rename fixture to `skip_unpack_array_item_exists.php.inc`

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @raoz
