### PR TITLE
Merge only if one item follow next to avoid skipping a type in MultiExceptionCatchRector

### LINKED ISSUE #8771: Incorrect behavior of MultiExceptionCatchRector with inherited exceptions and orders
# Bug Report

Incorrect behaviour when an order is important.

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.0     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d085aaf1-187f-47c7-a65b-8d9093cd28c3

```php
<?php

try {
    // some
} catch(RuntimeException $e) {
   throw new Exception(); 
} catch(TypeError $e) {
    echo 123;
    
    throw new Exception();
} catch(Error $e) {
    throw new Exception();
}
```

### Responsible rules

* `MultiExceptionCatchRector`

## Expected Behavior
Leave as is or:
```php
<?php

try {
    // some
} catch(RuntimeException|Error $e) {
   if ($e instanceof TypeError) {
       echo 123;
   }

   throw new Exception(); 
}
```

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixes https://github.com/rectorphp/rector/issues/8771

### CODE REVIEW

File: rules-tests/Php71/Rector/TryCatch/MultiExceptionCatchRector/Fixture/multiple_items.php.inc [hunk 1]
```diff
@@ -1,43 +0,0 @@
...
-    {
-        try {
-            // Some code...
-        } catch (ExceptionType1 $e) {
-            // Code to handle the exception
-        } catch (ExceptionType2 $e) {
-            // Code to handle the exception
-        } catch (ExceptionType3 $e) {
-            // Code to handle the exception
-        } finally {
```
Comment (samsonasik) [inline rules-tests/Php71/Rector/TryCatch/MultiExceptionCatchRector/Fixture/multiple_items.php.inc:17]: this should still be covered, current solution will make only works once next iteration, because once merged, it no longer equal print. 

I will looking into it :)

Comment (samsonasik) [reply rules-tests/Php71/Rector/TryCatch/MultiExceptionCatchRector/Fixture/multiple_items.php.inc:17]: https://github.com/rectorphp/rector-src/pull/6218
