### PR TITLE
RemoveUnusedNonEmptyArrayBeforeForeachRector: skip array dim fetch

### LINKED ISSUE #8264: Incorrect behavior of RemoveUnusedNonEmptyArrayBeforeForeachRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/ce3bf51a-6f56-45c7-a044-8c90fdd59dec

```php
<?php

final class DemoFile
{
    public const DEFAULT_GROUP = 'default';
    
    /**
     * @var array<string, list<self>>
     */
    private static $groups = [];

    public static function getFootnotes($group = self::DEFAULT_GROUP): array
    {
        if (! empty(self::$groups[$group])) {
            foreach (self::$groups[$group] as $note) {
                echo "hello";
            }
        }

        return [];
    }
}
```

### Responsible rules

* `RemoveUnusedNonEmptyArrayBeforeForeachRector`

## Expected Behavior

the `if (! empty(self::$groups[$group])) {` block should not be removed, because we don't know whether `self::$groups[$group]` will be defined at runtime.

interessting effect: if we remove the phpdoc from the array-property, rector skips the snippet

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/rectorphp/rector/issues/8264

### CODE REVIEW

File: rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    public const DEFAULT_GROUP = 'default';
+
+    /**
+     * @var array<string, list<self>>
+     */
+    private static $groups = [];
+
+    public static function getFootnotes($group = self::DEFAULT_GROUP): array
+    {
+        if (! empty(self::$groups[$group])) {
```
Comment (staabm) [inline rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: since [we already skip "regular" dim fetch](https://github.com/staabm/rector-src/blob/dim-fetch/rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_dim_fetch.php.inc), I think it makes sense to also skip it for this example

Comment (samsonasik) [reply rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: is it possible to to check native ArrayDimFetch type for this case?

```php
if ($foreachExpr instanceof Expr\ArrayDimFetch) {
   $nativeType = $this->nodeTypeResolver-getNativeType(...
}
```

Comment (staabm) [reply rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: Do you have a test case in mind which fails atm?

Comment (samsonasik) [reply rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: something like assign in prev stmt:

```php
self::$groups[$group] = ["foo"];

if (! empty(self::$groups[$group]))

Comment (staabm) [reply rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: fixed with https://github.com/rectorphp/rector-src/pull/5166/commits/0edaf2da087f9ea3c01ad95f89d01e01ea702e48

Comment (samsonasik) [reply rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: could you fix phpstan notice? thank you.

Comment (staabm) [reply rules-tests/DeadCode/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_property_dim_fetch.php.inc:16]: good catch :-). fixed.

**Comment by samsonasik** [comment]
Thank you @staabm
