### PR TITLE
[PHPStanStaticTypeMapper] Do not crash on numeric string on ReturnTypeDeclarationRector

### LINKED ISSUE #6896: Exception thrown when using `ReturnTypeDeclarationRector::class` and bcmath extension
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.9            |

When running rector set to PHP 8.1, and using the `SetList::TYPE_DECLARATION` an exception is thrown for ~~`@return numeric-string`~~ (Edit: I've just tried this with `@return string` and the same still applies so I'm not sure what at all is happening here). I've tried to recreate the problem using the demo below, however this doesn't show an exception, it just returns the page with no output whereas normally there would be a rector output saying "no changes".

## Minimal PHP Code Causing Issue

Demo: https://getrector.org/demo/1ec68b36-cdab-6cc4-99a7-55325363ad15
(Edit: I don't think this demo is helpful and it could be just because the bcmath extension is not included in demo)

## Expected Behaviour

Rector should not throw an exception and should either refactor the code, report an error for me to change my code, or it should skip it.

## Further information

The specific error in console is:
```
> rector process
  118/1138 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
In PHPStanStaticTypeMapper.php line 57:

  Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper::mapToPhpParserNode for PHPStan\Type\Accessory\AccessoryNumericStringType  


process [-o|--output-format [OUTPUT-FORMAT]] [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--no-progress-bar] [--no-diffs] [--clear-cache] [--port PORT] [--ide
ntifier IDENTIFIER] [--] [<source>...]

Script rector process handling the rector event returned with error code 1
```

and the full exception when debugging:
```
PHP Fatal error:  Uncaught Rector\Core\Exception\NotImplementedYetException: Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper::mapToPhpParserNode for PHPStan\
Type\Accessory\AccessoryNumericStringType in /home/ise/projects/creativecow/stratum-monorepo-php/vendor/rector/rector/packages/PHPStanStaticTypeMapper/PHPStanStatic
TypeMapper.php:57
```

Thank you for making rector, I hope I will give back in contributions over time.

### PR DESCRIPTION
**Pull request by samsonasik**
It previously got the following error:

```
There was 1 error:

1) Rector\Tests\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector\Php81RectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\NotImplementedYetException: Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper::mapToPhpParserNode for PHPStan\Type\Accessory\AccessoryNumericStringType
```

This PR Fixes https://github.com/rectorphp/rector/issues/6896

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

File: rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+namespace Rector\Tests\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector\FixtureForPhp81;
+
+class DoNotCrashOnNumericString
+{
+    public function run(): string
+    {
+        return bcadd('10', '5');
+    }
+}
```
Comment (TomasVotruba) [inline rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: Could you add test fixture withotu `): string` return type and the other half that adds it? So we're sure this type is completed.

```php
<?php

namespace Rector\Tests\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector\FixtureForPhp81;

class DoNotCrashOnNumericString
{
    public function run()
    {
        return bcadd('10', '5');
    }
} 

?>
-----
<?php

namespace Rector\Tests\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector\FixtureForPhp81;

class DoNotCrashOnNumericString
{
    public function run(): string
    {
        return bcadd('10', '5');
    }
} 

?>
```

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: New PHPStan 1.3 just released https://github.com/phpstan/phpstan/releases/tag/1.3.0 and as we use `^1.2` in composer.json, it will automatically updated and https://github.com/rectorphp/rector-src/pull/1589 and make error as new PR https://github.com/rectorphp/rector-src/pull/1589

I will pin to PHPStan 1.2 and add new fixture for it.

Comment (TomasVotruba) [reply rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: > I will pin to PHPStan 1.2 and add new fixture for it.

Thanks :+1:

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: @TomasVotruba I applied:

- temporary pin phpstan to 1.2 as 1.3 cause error like in PR https://github.com/rectorphp/rector-src/pull/1589 as currently we use `^1.2`

- add new fixture for no return declaration, it seems currently cause different result diff:

```diff
-    public function run(): string
+    public function run()
```

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: oh, it seems because `bcadd()` function not exists, so no return type is expected.

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: Fixed with add the missing function and add string handling https://github.com/rectorphp/rector-src/pull/1588/commits/50a27aa601de9cb26629cfa14754b932d476ed27 so it can add return type declaration.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

File: packages/PHPStanStaticTypeMapper/TypeMapper/AccessoryNumericStringTypeMapper.php [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    {
+        return AccessoryNumericStringType::class;
+    }
+
+    /**
+     * @param AccessoryNumericStringType $type
+     */
+    public function mapToPHPStanPhpDocTypeNode(Type $type, TypeKind $typeKind): TypeNode
+    {
+        return new IdentifierTypeNode('string');
```
Comment (staabm) [inline packages/PHPStanStaticTypeMapper/TypeMapper/AccessoryNumericStringTypeMapper.php:34]: Phpstan also supports `numeric-string`.. not sure this would be correct to use here though

See https://phpstan.org/developing-extensions/type-system

**Comment by TomasVotruba** [comment]
Rebase on `main` is needed now

File: rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc (hunk 1 above)
Comment (TomasVotruba) [reply rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81/do_not_crash_on_numeric_string.php.inc:11]: Thank you :+1:

File: packages/PHPStanStaticTypeMapper/TypeMapper/AccessoryNumericStringTypeMapper.php (hunk 2 above)
Comment (TomasVotruba) [reply packages/PHPStanStaticTypeMapper/TypeMapper/AccessoryNumericStringTypeMapper.php:34]: The PHP doc is also for PHPStorm, that understands only `string` type.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by internalsystemerror** [comment]
@samsonasik @TomasVotruba thank you both!
