### PR TITLE
[BUGFIX] Ensure proper reprint with attributes for finalized classes

### LINKED ISSUE #8080: FinalizeClassesWithoutChildrenRector removed newline before `final` when class has Attributes
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.17.6            |

The `FinalizeClassesWithoutChildrenRector` rector removes newlines when the class has and attribute in the line above.

## Minimal PHP Code Causing Issue

```php
#[Attribute]
class Dummy
{
}
```

will get corrected to 

```
#[Attribute]final class Dummy
{
}
```

When I add the line break before `final` again and rerun rector, I get no changes, so it doesn't seem to have anything to do with e.g. the length of the lines.

## Expected Behaviour

I'd expect rector to not remove the line break before the `final` keyword.

Or "spoken" in PHP ;-)

```php
#[Attribute]
final class Dummy
{

}
```

### PR DESCRIPTION
**Pull request by cngJo**
Previously, a finalized class would be printed on the same line as the attribute above, like this:

```php
#[SomeAttribute]final class ClassWithAttribute
{
}
```

for the new provided test case.

---
Fixes [#8080](https://github.com/rectorphp/rector/issues/8080)

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @cngJo

File: rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/class_with_attribute.php.inc [hunk 1]
```diff
@@ -0,0 +1,21 @@
+<?php
+
+namespace Rector\Tests\Php82\Rector\Class_\ReadOnlyClassRector\Fixture;
```
Comment (samsonasik) [inline rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/class_with_attribute.php.inc:3]: oh, the namespace need to be changed based on the test namespace, I will change that :)

Comment (cngJo) [reply rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/class_with_attribute.php.inc:3]: ah damit, totally missed that. Thank you for taking care of that.

**Comment by cngJo** [comment]
wow that was fast, thank you 🎉

File: rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/class_with_attribute.php.inc (hunk 1 above)
Comment (samsonasik) [reply rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/class_with_attribute.php.inc:3]: https://github.com/rectorphp/rector-src/pull/4586

**Comment by TomasVotruba** [comment]
Thank you @cngJo :+1:
