### PR TITLE
[Php74] Mirror comment on Closure return to ArrowFunction expr on ClosureToArrowFunctionRector

### LINKED ISSUE #6916: ClosureToArrowFunctionRector drops the docblock on `return`
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector fee8a47d1a627b01bfba2d85293c84692715506a                 |

ClosureToArrowFunctionRector drops the docblock on `return`.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec6e7f1-7c0f-684e-9843-a7cd56252edf
https://github.com/rectorphp/rector-src/pull/1641

## Expected Behaviour

The docblock should be kept.

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #1641 
Fixes https://github.com/rectorphp/rector/issues/6916

### CODE REVIEW

File: rules-tests/Php74/Rector/Closure/ClosureToArrowFunctionRector/Fixture/skip_arrow_function_already_with_comment.php.inc [hunk 1]
```diff
@@ -0,0 +1,9 @@
+<?php
+
+fn() =>
+    /**
+     * comment
+     */
+    // something
+    // @psalm-suppress UndefinedFunction
+    ff();
```
Comment (samsonasik) [inline rules-tests/Php74/Rector/Closure/ClosureToArrowFunctionRector/Fixture/skip_arrow_function_already_with_comment.php.inc:9]: this tweak on `BetterStandardPrinter::p()` currently make duplicate comment for existing arrow function:

```diff
      */
     // something
     // @psalm-suppress UndefinedFunction
-    ff();
+    /**
+     * comment
+     */
+// something
+// @psalm-suppress UndefinedFunction
```

which incorrect.

Comment (samsonasik) [reply rules-tests/Php74/Rector/Closure/ClosureToArrowFunctionRector/Fixture/skip_arrow_function_already_with_comment.php.inc:9]: resolved by add new AttributeKey to flag if comment is mirrored https://github.com/rectorphp/rector-src/pull/1677/commits/6f29de7282a7abafe9c26c205b85ea6c62739724

File: rules-tests/Php74/Rector/Closure/ClosureToArrowFunctionRector/Fixture/keep_docblock_on_return.php.inc [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+function() {
+    /** @psalm-suppress UndefinedFunction */
+    return ff();
+};
+?>
+-----
+<?php
+
+fn() => /** @psalm-suppress UndefinedFunction */
```
Comment (samsonasik) [inline rules-tests/Php74/Rector/Closure/ClosureToArrowFunctionRector/Fixture/keep_docblock_on_return.php.inc:11]: keep start comment on current line is on purpose to avoid make creating a tab spaces which will fail on compare in test.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:
