### PR TITLE
fix: OOM crash in RemoveUnusedVariableAssignRector

### LINKED ISSUE #9733: Excessive memory usage during analysis
# Bug Report

| Subject        | Details                                            |
| :------------- | :------------------------------------------------- |
| Rector version | v2.4.0 |
| PHP | 8.4.19 and 8.5.4 |

When Rector analyzes the code example below, it quickly uses up all available memory. The `memory_limit` setting in php.ini does not seem to take effect in this case.

## Minimal PHP Code Causing Issue

```php
<?php

function willExhaustMemory()
{
    $result = \Carbon\CarbonPeriod::create();

    return $result->first();
}
```

## Expected Behaviour

Normal analysis

### PR DESCRIPTION
**Pull request by calebdw**
Closes https://github.com/rectorphp/rector/issues/9733

### Problem
The `NoDiscard` attribute check used `AstResolver::resolveClassMethodOrFunctionFromCall()` which, for each call expression, would:
1. Parse the target class's source file into a full AST
2. Run PHPStan scope analysis on every node (attaching heavy `MutatingScope` objects)
3. If the method wasn't found directly, recursively parse ALL traits via `getTraits(true)`
4. Retain all parsed ASTs in memory indefinitely via `$parsedFileNodes` cache
For classes like `Carbon\CarbonPeriod` with deep trait hierarchies, this caused unbounded memory growth leading to OOM.

### Fix
I replaced the expensive AST-based resolution with PHPStan's lightweight ReflectionProvider API, this checks `NoDiscard` via PHPStan's reflection layer without parsing any source files.

### CODE REVIEW

**Comment by samsonasik** [comment]
@calebdw could you rebase latest main branch so all e2e test can green, thank you.

File: rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php [hunk 1]
```diff
@@ -306,4 +298,71 @@ private function shouldSkipVariable(Variable $variable, string $variableName, ar
...
+    private function isNoDiscardCall(Expr $expr): bool
+    {
+        if ($expr instanceof FuncCall) {
+            if (! $expr->name instanceof Name) {
+                return false;
+            }
+
+            $scope = ScopeFetcher::fetch($expr);
+
+            if (! $this->reflectionProvider->hasFunction($expr->name, $scope)) {
```
Comment (samsonasik) [inline rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: Function call can have namespaced, this should use:

```suggestion
            if (! $this->reflectionProvider->hasFunction(new Name((string) $this->getName($expr)), $scope)) {
```

File: rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php [hunk 2]
```diff
@@ -306,4 +298,71 @@ private function shouldSkipVariable(Variable $variable, string $variableName, ar
...
+                return false;
+            }
+
+            return $this->hasNoDiscardAttribute(
+                $this->reflectionProvider->getFunction($expr->name, $scope)
```
Comment (samsonasik) [inline rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: Function can have namespaced, this should use:

```suggestion
                $this->reflectionProvider->getFunction(new Name((string) $this->getName($expr)), $scope)
```

File: rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php (hunk 1 above)
Comment (samsonasik) [reply rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: see `FuncCallNameResolver`, pass the `$expr` to `$this->getName($expr)`.

https://github.com/rectorphp/rector-src/blob/c03bb57aa2dadd48639eac8d8f9c55ce771498c4/src/NodeNameResolver/NodeNameResolver/FuncCallNameResolver.php#L19

**Review by samsonasik — CHANGES_REQUESTED** [review]
one more change :)

https://github.com/rectorphp/rector-src/pull/7964#pullrequestreview-4070031568

File: rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php (hunk 2 above)
Comment (calebdw) [reply rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: This seems unnecessary---I'm passing the `Name` node and the `Scope` to the method: PHPStan should be quite capable of figuring this out

Comment (samsonasik) [reply rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php]: the `NAMESPACED_NAME` attribute can be from just auto imported name, that filled after imported so scope can read different name.

The `getName()` helper handle that :), create new variable for avoid repetitive `getName()` usage.

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @calebdw
