### PR TITLE
 [e2e] Add e2e for parallel process with current directory contains space 

### LINKED ISSUE #7202: Running Rector on CWD with space does not work
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.13.3  |

Running `vendor/bin/rector process` inside a project where the CWD contains a space, yields fatal errors.

Example `/users/bruno/my projects/some-project/`

## Minimal PHP Code Causing Issue

Just have a project where the CWD contains a space.

## Expected Behaviour

Some versions ago, it was working but i was not able to pinpoint which version started to cause this issue.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7202

### CODE REVIEW

**Comment by samsonasik** [comment]
It currently got the following error:

```
  
{"fatal_errors":["File \"/home/runner/work/rector-src/rector-src/e2e/parallel\" was not found"]}
Error: ] Could not process some files, due to:
         "Child process error: ".
Error: Process completed with exit code 1.
```

when running parallel on current directory has space.

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @brunogaspar

**Comment by brunogaspar** [comment]
Amazing, thank you!

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

File: packages/Parallel/Command/WorkerCommandLineFactory.php [hunk 1]
```diff
@@ -93,7 +93,7 @@ public function create(
 
         if ($input->hasOption(Option::CONFIG)) {
             $workerCommandArray[] = '--config';
-            $workerCommandArray[] = $input->getOption(Option::CONFIG);
+            $workerCommandArray[] = escapeshellarg($input->getOption(Option::CONFIG));
```
Comment (TomasVotruba) [inline packages/Parallel/Command/WorkerCommandLineFactory.php]: Could you add not to "why"? This might be copied later, so we knout about this issue.

Also what OS is it related, for future debugging :)

Comment (samsonasik) [reply packages/Parallel/Command/WorkerCommandLineFactory.php:96]: on parallel, the command generated is:

```
```

Comment (samsonasik) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: Note added: https://github.com/rectorphp/rector-src/pull/2421/commits/52d6f969908ba0080825aa5c2a21d6715ec972fe

On parallel, the command generated is:

```bash
'/opt/homebrew/Cellar/php/8.1.6/bin/php' '/Users/samsonasik/www/rector-src/e2e/../bin/rector' worker --dry-run --autoload-file '/Users/samsonasik/www/rector-src/e2e/../vendor/autoload.php' --clear-cache --port 51751 --identifier 'd449b0syyq' --output-format 'json' --no-ansi --config /Users/samsonasik/www/rector-src/e2e/parallel with space/rector.php
```

without the `escapeshellarg`, the `--config` as above, got the following:

```bash
--config /path/e2e/parallel with space/rector.php
```

which cause error:

```
Run php ../e2eTestRunner.php
{"fatal_errors":["File \"/home/runner/work/rector-src/rector-src/e2e/parallel\" was not found"]}
```

like in https://github.com/rectorphp/rector-src/runs/6723373768?check_suite_focus=true#step:8:9

the escaped result is:

```
--config '/path/e2e/parallel with space/rector.php'
```

tested in macOs (local) and Ubuntu (Github action).

Comment (TomasVotruba) [reply packages/Parallel/Command/WorkerCommandLineFactory.php]: Thank you 😊

**Review by TomasVotruba — APPROVED** [review]
