### PR TITLE
fix: Strip left spaces from opening tags when comparing output for changes

### LINKED ISSUE #8533: Minor indentation bug with template php code where statements have comments to the right.
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.2 (maybe other versions)        |

Hi, this is a bit of a weird one but on the legacy code I'm upgrading there's a a lot of comments after if statements etc. for inline php in HTML templates, such as:

```php
<ul>
    <?php if (true) { // comment ?>
    	<li><a href="/test">test</a></li>
    <?php } ?>
</ul>
```

Rector runs over the code fine but it changes the indentation of the closing tag for some reason. 
It's to do with the comment being there as removing the comment in the code fixes it. 

Resulting diff from running rector:
```diff
@@ -1,5 +1,5 @@
 <ul>
     <?php if (true) { // comment ?>
     	<li><a href="/test">test</a></li>
-    <?php } ?>
+<?php } ?>
 </ul>
```

## Minimal PHP Code Causing Issue

Examples with each type of comment that results in indentation change:
https://getrector.com/demo/4565e8a3-8ca6-458d-bb9f-a88dc83935ee
https://getrector.com/demo/a25d56d0-c6ad-43de-b5d6-29a389e3a7e6
https://getrector.com/demo/5f58a4fc-7888-4d5c-891b-4c8735085310

Example without comment where it doesn't change indentation:
https://getrector.com/demo/b1f7573b-445c-4666-b3ce-12141dca9b50

Above examples show it happening to if statements but tested and I believe all similar block statements have this issue, such as foreach: https://getrector.com/demo/1cf98379-d3e1-4310-90fe-ca75c009588f

## Expected Behaviour

Is it possible to have Rector skip this change?
Has anyone else run into a similar issue?

I can resolve by removing the comments if needed but there's many throughout this project that'd need switching to either remove or show the comment above where it's needed. 

I wonder if there's a way to have Rector skip changes like this where no other issue were spotted in that diff? 

Thank you.

### PR DESCRIPTION
**Pull request by stilliard**
When checking for changes, spaces can be temp removed from before the opening PHP tags in both the original and new content to cut down on whitespace only changes. 

Fixes: https://github.com/rectorphp/rector/issues/8533

Should be safe & unit tests pass, however I could wrap this in a config check and make it an opt in thing to ignore whitespace before opening tags if needed?

Let me know what you think, thanks.

### CODE REVIEW

File: src/Application/FileProcessor.php [hunk 1]
```diff
@@ -27,6 +27,12 @@
 
 final readonly class FileProcessor
 {
+    /**
+     * @var string
+     * @see https://regex101.com/r/llm7XZ/1
+     */
+    private const OPEN_TAG_SPACED_REGEX = '/^[ \t]+<\?php/m';
```
Comment (samsonasik) [inline src/Application/FileProcessor.php]: use `##` delimiter for consistency:

```suggestion
    private const OPEN_TAG_SPACED_REGEX = '#^[ \t]+<\?php#m';
```

File: src/Application/FileProcessor.php [hunk 2]
```diff
@@ -143,9 +149,10 @@ private function printFile(File $file, Configuration $configuration, string $fil
              * On very first content level
              */
             $originalFileContent = $file->getOriginalFileContent();
-            $ltrimOriginalFileContent = ltrim($originalFileContent);
+            $ltrimOriginalFileContent = preg_replace(self::OPEN_TAG_SPACED_REGEX, '<?php', ltrim($originalFileContent));
+            $ltrimNewContent = preg_replace(self::OPEN_TAG_SPACED_REGEX, '<?php', ltrim($newContent));
 
-            if ($ltrimOriginalFileContent === $newContent) {
+            if ($ltrimOriginalFileContent === $ltrimNewContent) {
```
Comment (samsonasik) [inline src/Application/FileProcessor.php:160]: the origininal compare need to be used first, compare regex version in next if as regex can be expensive

File: src/Application/FileProcessor.php [hunk 3]
```diff
@@ -143,9 +149,10 @@ private function printFile(File $file, Configuration $configuration, string $fil
              * On very first content level
              */
             $originalFileContent = $file->getOriginalFileContent();
-            $ltrimOriginalFileContent = ltrim($originalFileContent);
+            $ltrimOriginalFileContent = preg_replace(self::OPEN_TAG_SPACED_REGEX, '<?php', ltrim($originalFileContent));
+            $ltrimNewContent = preg_replace(self::OPEN_TAG_SPACED_REGEX, '<?php', ltrim($newContent));
```
Comment (samsonasik) [inline src/Application/FileProcessor.php]: you can use `\Nette\Utils\Strings::replace($subject, $pattern, $replacement)` usage for consistenty, you can search how `Strings::replace(` usage on codebase

File: src/Application/FileProcessor.php (hunk 2 above)
Comment (stilliard) [reply src/Application/FileProcessor.php:160]: Good point, splitting it out to 2 steps now. Sorry for the delay there btw.

File: src/Application/FileProcessor.php (hunk 3 above)
Comment (stilliard) [reply src/Application/FileProcessor.php]: Ah sure, switching it to this now thanks

**Comment by stilliard** [comment]
Hi @samsonasik 
Thanks for reviewing the code earlier. 
I believe the changes are now made and I've run it through phpunit again to make sure it still passes.
Let me know if there's anything else I can improve with it, thanks!

File: src/Application/FileProcessor.php [hunk 4]
```diff
@@ -142,10 +149,16 @@ private function printFile(File $file, Configuration $configuration, string $fil
              * Handle new line or space before <?php or InlineHTML node wiped on print format preserving
              * On very first content level
              */
-            $originalFileContent = $file->getOriginalFileContent();
-            $ltrimOriginalFileContent = ltrim($originalFileContent);
+            $ltrimOriginalFileContent = ltrim($file->getOriginalFileContent());
+            $ltrimNewContent = ltrim($newContent);
```
Comment (samsonasik) [inline src/Application/FileProcessor.php]: no need ltrim on `$newContent` as before, php-parser v4 already ltrim it, on php-parser v5, the ltrim will no longer needed that we can re-work when upgrade to php-parser v5

Comment (stilliard) [reply src/Application/FileProcessor.php]: Good to know, fixing this now thanks

**Comment by stilliard** [comment]
Thanks @samsonasik, just pushed a fix for that.

**Review by samsonasik — APPROVED** [review]
Looks good to me 👍

**Comment by samsonasik** [comment]
@TomasVotruba let's merge it, thank you @stilliard
