### PR TITLE
[TypeDeclaration] Handle crash on concat param append returned used on Arg on StrictStringParamConcatRector

### LINKED ISSUE #8130: Return value must be of type ?PhpParser\Node\Expr\Variable, PhpParser\Node\Expr\AssignOp\Concat returned"
## Reproduction:
Try to refactor:

```php

if ( ! function_exists('formatSizeUnits')) {
    function formatSizeUnits($bytes): string
    {
        if ($bytes >= 1_073_741_824) {
            $bytes = number_format($bytes / 1_073_741_824, 1).' GB';
        } elseif ($bytes >= 1_048_576) {
            $bytes = number_format($bytes / 1_048_576, 1).' MB';
        } elseif ($bytes >= 1024) {
            $bytes = number_format($bytes / 1024, 1).' KB';
        } elseif ($bytes > 1) {
            $bytes .= ' bytes';
        } elseif (1 === $bytes) {
            $bytes .= ' byte';
        } else {
            $bytes = '0 bytes';
        }

        return $bytes;
    }
}
```

```
[ERROR] Could not process "/var/www/app/modules/CMS/src/Helpers/functions.php" file, due to:                 
         "System error:                                                                                                 
         "Rector\TypeDeclaration\Rector\ClassMethod\StrictStringParamConcatRector::resolveVariableConcattedFromParam(): 
         Return value must be of type ?PhpParser\Node\Expr\Variable, PhpParser\Node\Expr\AssignOp\Concat returned"
```

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://getrector.com/demo/36fc83c8-43ca-48a8-84cd-4500f534aa29
Fixes https://github.com/rectorphp/rector/issues/8130

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @smortexa

File: rules-tests/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector/Fixture/concat_param_append_returned.php.inc [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+?>
+-----
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\StrictStringParamConcatRector\Fixture;
+
+class ConcatParamAppendReturned
+{
+    function formatSizeUnits(?string $bytes): string
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector/Fixture/concat_param_append_returned.php.inc]: @smortexa hm.., the `$bytes` seems should be possibly `float` or `string` if any possible concatted.

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector/Fixture/concat_param_append_returned.php.inc]: I think for safer, it should be skipped when used as Arg.

Comment (samsonasik) [reply rules-tests/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector/Fixture/concat_param_append_returned.php.inc]: Fixed by skip it 👍

File: rules-tests/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector/Fixture/skip_concat_param_append_returned_used_as_arg.php.inc [hunk 2]
```diff
@@ -0,0 +1,25 @@
+<?php
+
+namespace Rector\Tests\TypeDeclaration\Rector\ClassMethod\StrictStringParamConcatRector\Fixture;
+
+class SkipConcatParamAppendReturnedUsedAsArg
+{
+    function formatSizeUnits($bytes): string
+    {
+        if ($bytes >= 1_073_741_824) {
+            $bytes = number_format($bytes / 1_073_741_824, 1).' GB';
```
Comment (samsonasik) [inline rules-tests/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector/Fixture/skip_concat_param_append_returned_used_as_arg.php.inc:10]: here `$bytes` re-assign and used as `Arg` need to be float, that's why it need to be skipped as possible non string type.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by smortexa** [comment]
@samsonasik Thanks. The issue is fixed.

File: rules/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector.php [hunk 3]
```diff
@@ -153,6 +159,14 @@ private function resolveVariableConcattedFromParam(
         return $variableConcatted;
     }
 
+    private function isVariableInArg(Arg $arg, string $paramName): bool
+    {
+        return (bool) $this->betterNodeFinder->findFirst(
+            $arg->value,
+            fn (Node $subNode): bool => $subNode instanceof Variable && $this->isName($subNode, $paramName)
+        );
+    }
```
Comment (samsonasik) [inline rules/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector.php:168]: @TomasVotruba I think we can move this handling to a guard service to be reused when parameter used as Arg value in diferent rules, another rule that has same issue is:

- https://github.com/rectorphp/rector/issues/8091

Comment (samsonasik) [reply rules/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector.php:168]: Variable Param reassign check probably better instead of Arg check, I will check tomorrow.

Comment (samsonasik) [reply rules/TypeDeclaration/Rector/ClassMethod/StrictStringParamConcatRector.php:168]: https://github.com/rectorphp/rector-src/pull/4775
