### PR TITLE
[fix] skip already dim fetch variable on OrdSingleByteRector

### LINKED ISSUE #9503: OrdSingleByteRector rule replaces parameter when it shouldn't
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v2.2.8            |

## Minimal PHP Code Causing Issue

While running rector with php8.5, I got this

```
    ---------- begin diff ----------
@@ @@
         while ($i < strlen($encodedPolyline) && count($points) < 2) {
             $shift = $result = 0x00;
             do {
-                $bit = ord($encodedPolyline[$i++]) - 63;
+                $bit = ord($encodedPolyline[$i++][0]) - 63;
                 $result |= ($bit & 0x1F) << $shift;
                 $shift += 5;
             } while ($bit >= 0x20);
@@ @@
         while ($i < strlen($encodedPolyline)) {
             $shift = $result = 0x00;
             do {
-                $bit = ord($encodedPolyline[$i++]) - 63;
+                $bit = ord($encodedPolyline[$i++][0]) - 63;
                 $result |= ($bit & 0x1F) << $shift;
                 $shift += 5;
             } while ($bit >= 0x20);
    ----------- end diff -----------
```

The `$encodedPolyline[$i++]` is already a single byte, no need to add an extra `[0]`

Weirdly enough, this does not happen on the demo instance: https://getrector.com/demo/7b48d1f0-c0f1-4bac-898b-614658e5d266

Live demo in a GitHub action of mine: https://github.com/robiningelbrecht/statistics-for-strava/actions/runs/19574398963/job/56055773761

## Expected Behaviour

In this case, to not alter the code .

### LINKED ISSUE #9512: Incorrect behavior of OrdSingleByteRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See 

- https://getrector.com/demo/f1da135c-6dc8-4544-882a-4baa6a7f2e45
- https://getrector.com/demo/310f3ee1-cccf-4918-bb27-7c072c44429f

```php
<?php

final class Guid
{
    public static function generate(): string
    {
        if (function_exists('com_create_guid')) {
            return trim(com_create_guid(), '{}');
        }

        $data    = random_bytes(16);
        $data[6] = chr(ord($data[6]) & 0x0F | 0x40); // set version to 0100
        $data[8] = chr(ord($data[8]) & 0x3F | 0x80); // set bits 6-7 to 10

        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }
}
```

### Responsible rules

* `OrdSingleByteRector`

## Expected Behavior

Not sure what this rule is trying to do, but it should definitely not keep trying to add `[0]` to the array

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes https://github.com/rectorphp/rector/issues/9503, closes https://github.com/rectorphp/rector/issues/9512

Related RFC: https://wiki.php.net/rfc/deprecations_php_8_5#deprecate_passing_string_which_are_not_one_byte_long_to_ord

### CODE REVIEW

File: rules/Php85/Rector/FuncCall/OrdSingleByteRector.php [hunk 1]
```diff
@@ -65,12 +67,9 @@ public function refactor(Node $node): ?Node
         }
 
         $args = $node->getArgs();
+        $firstArg = $args[0];
 
-        if (! isset($node->args[0])) {
```
Comment (samsonasik) [inline rules/Php85/Rector/FuncCall/OrdSingleByteRector.php:69]: isset is needed in case someone for whatever doesn't have argument, or have remove argument via custom rule, this will cause error undefined index 0 and error:

```
Trying to get property 'value' of non-object
```

in php 7.4, it just warning, but not error

https://3v4l.org/batdI#v7.4.33

Comment (samsonasik) [reply rules/Php85/Rector/FuncCall/OrdSingleByteRector.php:69]: see PR:

- https://github.com/rectorphp/rector-src/pull/7682

Comment (TomasVotruba) [reply rules/Php85/Rector/FuncCall/OrdSingleByteRector.php:69]: I see. Didn't know older Php version allow less args. Thanks 👌
