### PR TITLE
[Visibility] Does not turn abstraction into static from implicit public abstractions in ExplicitPublicClassMethodRector (#7483)

### LINKED ISSUE #7483: Incorrect result of the rule ExplicitPublicClassMethodRector
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.2             |

## Minimal PHP Code Causing Issue
 ```
class SomeClass
 {
-    abstract function foo();
+    public static function foo();
 }
```
## Expected Behaviour

 ```
class SomeClass
 {
-    abstract function foo();
+    public abstract function foo();
 }
```

### PR DESCRIPTION
**Pull request by Goral64**
Incorrect result of the rule ExplicitPublicClassMethodRector

Fixes https://github.com/rectorphp/rector/issues/7483

### CODE REVIEW

**Comment by Goral64** [comment]
resend new

File: rules/Privatization/NodeManipulator/VisibilityManipulator.php [hunk 1]
```diff
@@ -38,13 +50,13 @@ public function makeAbstract(ClassMethod | Class_ $node): void
     /**
      * @api
      */
-    public function makeNonStatic(ClassMethod | Property $node): void
+    public function makeNonAbstract(ClassMethod | Property $node): void
     {
-        if (! $node->isStatic()) {
+        if (!($node instanceof ClassMethod) || ! $node->isAbstract()) {
```
Comment (JohJohan) [inline rules/Privatization/NodeManipulator/VisibilityManipulator.php]:
```suggestion
        if (! $node instanceof ClassMethod || ! $node->isAbstract()) {
```
Wont this work?

Comment (Goral64) [reply rules/Privatization/NodeManipulator/VisibilityManipulator.php]: OK. Done.

Comment (JohJohan) [reply rules/Privatization/NodeManipulator/VisibilityManipulator.php]: Looks good

**Comment by samsonasik** [comment]
Please update PR title to something like:

```bash
[Visibility] Do not remove abstract from implicit public static on ExplicitPublicClassMethodRector
```

**Review by JohJohan — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

File: rules-tests/Visibility/Rector/ClassMethod/ExplicitPublicClassMethodRector/Fixture/fixture.php.inc [hunk 2]
```diff
@@ -1,5 +1,32 @@
...
+    
+    protected static function protectedVisStatic()
+    {
+    }
+    
+    private static function privateVisStatic()
+    {
+    }
+}
+
```
Comment (TomasVotruba) [inline rules-tests/Visibility/Rector/ClassMethod/ExplicitPublicClassMethodRector/Fixture/fixture.php.inc]: Could you extract this fixture to own file? That way we have mininal reproducer and can easily backtrack the issue to specific fixture file in case of regression in the future.

Thanks :slightly_smiling_face:

**Review by JohJohan — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:
