### PR TITLE
[DeadCode] Skip Array Callable dynamic method using __CLASS__ with constructor (no default args) on RemoveUnusedPrivateMethodRector

### LINKED ISSUE #8577: Incorrect behavior of RemoveUnusedPrivateMethodRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/2012b4c2-deb0-410a-b2cc-799e09b77dd0

```php
<?php

class Service
{
    public function __construct($msg)
    {
    }

    public function getSnake($sentence): string|array|null
    {
        return preg_replace_callback('/([A-Z])/', [__CLASS__, 'convertToSnakeCase'], $sentence);
    }

    private function convertToSnakeCase($c) {
        return "_" . strtolower($c[1]);
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior
* Rector should skip it.

### Similar Case
* https://github.com/rectorphp/rector/issues/8574

### PR DESCRIPTION
**Pull request by hogejiro**
fix https://github.com/rectorphp/rector/issues/8577

### CODE REVIEW

File: src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php [hunk 1]
```diff
@@ -188,9 +189,9 @@ private function resolveClassConstFetchType(
 
     private function resolveCallerType(Expr $expr, Scope $scope, ?string $classMethodName): Type
     {
-        if ($expr instanceof ClassConstFetch) {
-            // static ::class reference?
-            $callerType = $this->resolveClassConstFetchType($expr, $scope, $classMethodName);
+        if ($expr instanceof ClassConstFetch || $expr instanceof Class_) {
+            // class context means self|static ::class or __CLASS__
+            $callerType = $this->resolveClassContextType($expr, $scope, $classMethodName);
```
Comment (hogejiro) [inline src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php:194]: (note)
I wanted to avoid using the abstract term `'context'`.
But I couldn't think of a better way to express it...

File: rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_magic_constant_with_constructor.php.inc [hunk 2]
```diff
@@ -0,0 +1,27 @@
+<?php
```
Comment (hogejiro) [inline rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_magic_constant_with_constructor.php.inc:1]: (note)
This code case showed me unexpected result.

### `rectorphp/rector` skip
* Do nothing.
* https://getrector.com/demo/ceed39e6-2078-42b3-84be-54a0f2035bb6

### `rectorphp/rector-src` do not skip
* Remove the used method. ( State of commit ff0705b )
<details close>
<summary>PHPUnit result</summary>

```
$ vendor/bin/phpunit -d --enable-pretty-print rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php
PHPUnit 10.5.15 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.3
Configuration: /path/to/rector-src/phpunit.xml

....................F..................                           39 / 39 (100%)

Time: 00:01.575, Memory: 90.00 MB

There was 1 failure:

1) Rector\Tests\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector\RemoveUnusedPrivateMethodRectorTest::test with data set #20 ('...')
Failed on fixture file "skip_array_callables_magic_constant_with_constructor.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@

         return $array;
     }
-
-    private function sort($a, $b)
-    {
-        return $a <=> $b;
-    }
 }

/path/to/rector-src/src/Testing/PHPUnit/AbstractRectorTestCase.php:248
/path/to/rector-src/src/Testing/PHPUnit/AbstractRectorTestCase.php:164
/path/to/rector-src/rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php:16
```
</details>

File: src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php [hunk 3]
```diff
@@ -201,4 +202,16 @@ private function resolveCallerType(Expr $expr, Scope $scope, ?string $classMetho
...
         return $callerType;
     }
+
+    private function isRequiredClassReflectionResolution(string $classConstantReference): bool
+    {
+        if ($classConstantReference === ObjectReference::STATIC) {
+            return true;
+        }
+        $magicConstantClassName = (new Class_())->getName();
+        if ($classConstantReference === $magicConstantClassName) {
```
Comment (samsonasik) [inline src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php]: just compare with `__CLASS__` string is enough:

```suggestion
        if ($classConstantReference === '__CLASS__') {
```

Comment (hogejiro) [reply src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php]: Thanks. I will fix it.

**Review by samsonasik — APPROVED** [review]
Looks good to me

**Comment by samsonasik** [comment]
Thank you @hogejiro

**Comment by samsonasik** [comment]
@hogejiro it seems cause running rector on rules got error:

```
➜  rector-src git:(main) bin/rector process rules
 638/638 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process                                                                                              
         "/Users/samsonasik/www/rector-src/rules/CodingStyle/Rector/String_/UseClassKeywordForClassNameResolutionRector.
         php" file, due to:                                                                                             
         "System error:                                                                                                 
         "Rector\NodeCollector\NodeAnalyzer\ArrayCallableMethodMatcher::isRequiredClassReflectionResolution(): Argument 
         #1 ($classConstantReference) must be of type string, int given, called in                                      
         src/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php147"                                              
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 206
```

I will take a look :)

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/5780

**Comment by hogejiro** [comment]
@samsonasik 
Oh sorry. Thank you for fixing it 🙇
