### PR TITLE
[Php56][Php70] Handle infinite loop on TernaryToNullCoalescingRector+AddDefaultValueForUndefinedVariableRector

### LINKED ISSUE #7889: Rector hangs with no output
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.15.24             |

I'm trying to update the php version for a legacy project written in cackephp 2, rector seems to hang on some files, it's very hard to debug. But after disabling the parallel execution I was able to found the problematic file.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/289e4c81-adae-4062-8a7a-2ad51c53c711

## Expected Behaviour

I'm not sure on how this file should be changed but rector should not hang.

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector/issues/7889
Ref https://getrector.com/demo/289e4c81-adae-4062-8a7a-2ad51c53c711

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed :tada: /cc @nerones

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

File: rules/Php56/NodeAnalyzer/UndefinedVariableResolver.php [hunk 1]
```diff
@@ -142,19 +142,19 @@ private function isAssign(Node $parentNode): bool
...
             return true;
         }
 
-        if ($this->issetOrUnsetOrEmptyParent($parentNode)) {
+        if ($this->isAssign($parentNode)) {
             return true;
         }
 
-        if ($this->isAsCoalesceLeftOrAssignOpCoalesceVar($parentNode, $variable)) {
+        if ($this->issetOrUnsetOrEmptyParent($parentNode)) {
```
Comment (staabm) [inline rules/Php56/NodeAnalyzer/UndefinedVariableResolver.php:157]: @samsonasik I think it could make sense to re-order the skipchecking methods so e.g. doing AST traversing only after cheaper checks have been done

Comment (samsonasik) [reply rules/Php56/NodeAnalyzer/UndefinedVariableResolver.php:157]: This patch is to ensure no infinite loop by check coalesce early, which check coalesce later cause infinite loop, see https://getrector.com/demo/289e4c81-adae-4062-8a7a-2ad51c53c711 

feel free to provide improvement PR 👍

**Comment by nerones** [comment]
Amazing job, thanks.

I really like this tool I hope that at some point I will able to contribute something.

File: rules/Php56/NodeAnalyzer/UndefinedVariableResolver.php (hunk 1 above)
Comment (samsonasik) [reply rules/Php56/NodeAnalyzer/UndefinedVariableResolver.php:157]: @staabm I created PR https://github.com/rectorphp/rector-src/pull/3643 for that.
